### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#10]
add keyboard shortcuts for selection, menu, action, etc.

**Comment by willrett** [comment]
keyboard shortcuts

**Comment by willrett** [comment]
testing adding comments

**Comment by martinjoconnor** [comment]
More detailed issues her: https://github.com/metadatacenter/cedar-project/issues/751,
https://github.com/metadatacenter/cedar-project/issues/752
