### ISSUE TITLE
saved instance isn't valid, can't OpenView

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1020]
When I open https://cedar.metadatacenter.org/instances/edit/https://repo.metadatacenter.net/template-instances/80202ea6-3cf7-4c24-a1ec-d89d617a0f92 it is valid, when I save it it becomes unvalid.

When I enable OpenView it doesn't show any metadata.

**Comment by graybeal** [comment]
When I copy the source template for the above into a new template and save that, it saves without errors. When I try to create metadata with that new template, saving the metadata fails with a 400 error.

**Comment by martinjoconnor** [comment]
I have patched the template and instance. 

It seems that there may be subtle problems with very old templates that our current validation software is not handling. See metadatacenter/cedar-model-validation-library#23

**Comment by martinjoconnor** [comment]
Fixed template and instance uploaded by Marcos.
