### ISSUE TITLE
Support category search in template designer

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#1026]
Currently, only interactive tree-based search is supported. 

Will enable searching for CDEs when adding fields to a template or element/

See metadatacenter/cedar-resource-server#76

**Comment by marcosmro** [comment]
Done. See below a screenshot of the new modal that can be used from the Template/Element Designer to search for fields and elements using the category tree, and includes several other enhancements and bug fixes.

![Screen Shot 2020-08-28 at 5 56 21 PM](https://user-images.githubusercontent.com/7634440/91626278-7491cb00-e962-11ea-872c-f27532eea342.png)
