### ISSUE TITLE
Back arrow sometimes takes you to your home folder rather than back to the folder you came from

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#105]
it should take you to the current folder

**Comment by willrett** [comment]
not sure how to make this happen.  it seems like it is working now.

**Comment by willrett** [comment]
if you search and then open a document listed in the search results,  the back arrow will take you back to the folder you were on before the search.   this is the way it should work.

**Comment by martinjoconnor** [comment]
Likely related to metadatacenter/cedar-template-editor#

**Comment by martinjoconnor** [comment]
Likely related to metadatacenter/cedar-template-editor#504

**Comment by willrett** [comment]
fixed a bug with the finder changing the current folder.  maybe this is the whole problem, or it may just be one part of it.
