### ISSUE TITLE
CDE lookup issues

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1055]
i'm trying to work with CDEs for the demo Monday, there are a couple of issues with the indexing it appears.
Here are the CDEs I'm working with, but I'm sure the attendees may search for their own.

I'm searching from within the Template Designer's search (magnifier glass) option.
```
6341138	RELEASED   -- finds 3, middle one creates an error and can't be selected
6412753	DRAFT NEW  -- finds 0
6409556	DRAFT NEW  -- finds 0
6412768	DRAFT NEW  -- finds 0
6343384	DRAFT NEW  -- finds 0
6380048	RELEASED -- finds 2, either one chosen first will display correctly, second one chosen shows 404 error (either order)
6380049	RELEASED -- finds 2, same pattern
6380045	DRAFT NEW -- finds 0
6343385	RELEASED -- finds 3, bottom one can't be selected
6412736	DRAFT NEW -- finds 0
6412503	RELEASED -- finds 2, top one always generates error, bottom one never does
```

**Comment by marcosmro** [comment]
1. Our ingestion process is limited to "RELEASED" CDEs, so you won't be able to find any CDE with a "DRAFT NEW" status.
2. Yesterday morning I started a full reindexing to ensure that all previous CDEs were properly removed from the index and that all the new CDEs are indexed as well. The reindexing task finished today, early in the morning, so you shouldn't see more than one result for the following search queries: 
- 6341138
- 6380048
- 6380049
- 6343385
- 6412503

**Comment by graybeal** [comment]
goes away when indexing is complete. another task exists (and is mostly complete) to support in-parallel indexing.
