### ISSUE TITLE
first saves that include CDE controlled terms fail

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1056]
I just tried saving a just-entered metadata instance based on a just-created template with 6 or 7 CDEs in it. The save error message was
```
Status: 400, Bad Request
URL: https://resource.metadatacenter.org/template-instances?folder_id=https%3A%2F%2Frepo.metadatacenter.org%2Ffolders%2Fc421416d-dfbf-4981-86aa-d5267fa72f6b
Method: POST
Message:
Error key:
Exception:
Stack trace:
```

The message is
```
Status: 400, Bad Request
URL: https://resource.metadatacenter.org/template-instances?folder_id=https%3A%2F%2Frepo.metadatacenter.org%2Ffolders%2Fc421416d-dfbf-4981-86aa-d5267fa72f6b
Method: POST
Message:
Error key:
Exception:
Stack trace:
```

Template is `https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/5bf8d2bf-2f1c-4d77-a399-a2222157d894`

Instance is, well, it doesn't exist yet. CEDAR Devs should have read/write access to the folder (https://repo.metadatacenter.org/folders/c421416d-dfbf-4981-86aa-d5267fa72f6b)

**Comment by graybeal** [comment]
Further testing (10/10) reveals that it seems to always fail if a controlled vocabulary term was filled out before the first time hitting the Save button; it never fails if no controlled vocabulary term was filled out before hitting the Save button.

**Comment by graybeal** [comment]
This is CDE-related. If a new template is created with non-CDE fields, the controlled terms are not an issue.

If the new template has a CDE field, and in the instance that field is filled before the first save, there is an issue.

If the new instance is saved before filling out the CDE field, the CDE field can be filled out after that.

It appears that a new instance that gets filled out with a non-CDE field (but not saved) does not yet have any instance metadata, but that when it is saved that instance metadata is generated.  

A new instance that gets filled out with a CDE field can not be successfully saved, and so the instance metadata is not successfully generated (a corrupt one may be generated).  Apparently nothing that happens afterwards can rescue the situation.

**Comment by graybeal** [comment]
Here is the difference between filling out a field "Gender (parens)" and filling out a CDE "Gender Code (2179640)".  This is the only difference in the fiel; the first one will save successfully, and the second one will not.

Field:
```
  "Gender Code (2179640)": {},
  "Gender (parens)": {
    "@id": "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C160940",
    "rdfs:label": "Gender Fluid"
  }
}
```
CDE:
```
  "Gender Code (2179640)": {
    "@id": "https://cadsr.nci.nih.gov/metadata/CADSR-VS/bc6c327429f1dec67b999dac78ceb37bd6be204d",
    "rdfs:label": "Female",
    "skos:notation": "2"
  },
  "Gender (parens)": {}
}

**Comment by graybeal** [comment]
So, to sum up:

1. A newly generated instance doesn't have any instance attributes in the JSON-LD. 
2. Typically, the first save creates those instance attributes. 
3. However, if any CDE content (i.e., filled-out values) exists before the first save, it blocks a successful save. (Crazy guess: skos:notation, or something, isn't in schema correctly.)  So the instance metadata is never initialized and the CDE content keeps preventing initialization. 
4. If the CDE content is removed, the save is not blocked by it, the instance metadata is generated successfully, and after that the CDE content can be added and will save successfully. 

I'm not sure what the interaction could be whereby instance metadata makes CDE content 'OK'. But there is one. Perhaps the validation process in that case is stopped, doesn't recognize an error in the CDE section, or correctly doesn't report errors that it sees.

**Comment by marcosmro** [comment]
The cause of this issue is that the schema of the CDE fields does not allow a skos:notation attribute at the same level than rdfs:label and @id. We have to fix the CDE fields generator to include skos:notation for fields constrained to values from value sets.
