### ISSUE TITLE
CDE folder display is slow

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1060]
Clicking on Categories > NCI caDSR shows the first list reasonably quickly, but I can't scroll to the next 100 results for maybe 30 seconds, and the bottom of the screen reads Displaying "1 - 200 of 47619" After 30+ seconds the screen 'refreshes', but each subsequent search takes quite a while. Maybe always done the latter (slow searches after the first 200), but the former is new.

**Comment by marcosmro** [comment]
Duplicate of https://github.com/metadatacenter/cedar-project/issues/1061
