### ISSUE TITLE
Category search for NCI caDSR seems greedy

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1061]
If I click on the NCI caDSR category drop down, the total number eventually reads 60208. Maybe that's a tiny bit high (?—thought we were at 59K plus a little bit a day or two agao), but there are weird additions, like a folder called Training Folder and a template I created called 1 Introduction to CEDA Talk. 

Any thoughts on why these are showing up in this search?

![Screen Shot 2020-02-02 at 6.09.25 PM.png](https://images.zenhubusercontent.com/5cc9bdc26c1fd80bacaab82a/a55970df-f85a-49c9-a8c9-89b7166c9cf8)

**Comment by marcosmro** [comment]
Atti has taken a look at this issue. It's a pagination bug. He'll try to fix it today and release it tomorrow to staging, together with other enhancements that have been completed in the past couple of months.

**Comment by martinjoconnor** [comment]
Check that is same as #1043
