### ISSUE TITLE
can't enter numeric field values

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1066]
In the folder https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2Fbea02f48-8cf2-4f96-9efa-ce576915a20d, there is a template called Small Molecule (https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/8c5d52db-8f7e-48f6-9380-0744c3c40b99) which has recently been updated.

There are several numeric fields in the template. If you try to create metadata for this template, you can not enter the values for those fields, they are not preserved.

Note this is a LINCS template that may have been automatically created, and we may not have conveyed to them any recent changes to the schema.

**Comment by graybeal** [comment]
When I duplicated the template and modified the option for the number type (set it to anything but Any Number), it started working. Then I could set it back to Any Number and it would keep working. 

Unfortunately it doesn't work if the number you enter is 0 (!), it changes that to a blank. Filed as #1067 .

**Comment by graybeal** [comment]
I created https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/ad6c3559-e4a8-4af5-8f20-ff84c1c24975 as a copy of the above template, in case they modify the original and we can't see what it looked like. Suggest we move the copy somewhere that it isn't writeable by everyone (as the whole folder is writeable by everyone).

**Comment by marcosmro** [comment]
I've taken a look a the template and fixed it. There were some issues in the schema of the numeric fields that the validator was not able to detect. @graybeal, please take a look at the fixed template and close this issue if you think that it behaves as expected (except for #1067).

**Comment by graybeal** [comment]
Marcos has fixed that template in place, but turns out there are multiple templates that need fixing. We're awaiting a list, and I've proposed they will need to fix their auto-generator anyway, so we'll negotiate this in the morning. They are in a bit of a hurry.
