### ISSUE TITLE
numbers that are 0 are left blank

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1067]
Entering 0 in any number field causes the field to be left blank.

**Comment by egyedia** [comment]
Fixed. Available now on Staging and Production as well.

**Comment by dusicav** [comment]
In the template: 
https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Frepo.metadatacenter.org%2Ftemplates%2F8c5d52db-8f7e-48f6-9380-0744c3c40b99&data=02%7C01%7CDVidovic%40med.miami.edu%7C2dc8aaece1754e28697508d7b656baf5%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637178355939851076&sdata=bxyEWaxbOzxich8POFRpCpxqGk2F31nB3T%2Fvhl80cFM%3D&reserved=0

the '0' is not getting preserved for dvidovic@miami.edu user. I tried different browsers (Chrome, FireFox) on windows and mac, and it never got preserved. 
Tested fields: 'Molecular_weight', 'logP/hydrophobicity', 'Water_solubility' and 'Purity'.

**Comment by graybeal** [comment]
The template to which @dusicav refers is known to us as https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/8c5d52db-8f7e-48f6-9380-0744c3c40b99. It is in the same place as before, [/Shared/IDG/Templates from API](https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2Fbea02f48-8cf2-4f96-9efa-ce576915a20d). 

I can't duplicate this issue either. @dusicav, can you try clearing your cache? For example on Chrome, in the Metadata Editor with an empty form, bring up the Chrome Developer Tools (under View menu), then hold down on the reload button until you see "Empty cache and hard reload". Select that option, then try filling out the metadata again.

**Comment by dusicav** [comment]
I just tried again today without clearing the cache or changing anything on my end and it worked fine. So, not sure what happened on Friday but will consider it resolved now. Thanks!
