### ISSUE TITLE
identity provider not recognized

### ISSUE THREAD

**Issue by akoleti** [metadatacenter/cedar-project#1068]
Hi,

We have previously registered our realm 'keycloak-oidc-idg' but, for some reason it is not allowing users to Establish single sign on any more. Attaches is the error that that users see. 
![image](https://user-images.githubusercontent.com/12258558/75283814-893dac80-57e1-11ea-859e-931a9d01e380.png)

**Comment by graybeal** [comment]
Amar, let's set up a time to talk about what it is that you're doing.  I think we need to be a bit more systematic about supporting the various tasks you need to do, otherwise we will have resource allocation issues.  I'll try you on Slack.

**Comment by graybeal** [comment]
Amar reports this was previously registered and working in 2019, but has stopped working since.

**Comment by graybeal** [comment]
reference https://github.com/metadatacenter/cedar-project/issues/970 for previous setup

**Comment by graybeal** [comment]
It isn't clear what caused this issue for recent users, but Atti was able to clear it up,  I think by directly manipulating keycloak entries. So I think this can be signed off, if no one is seeing it.
