### ISSUE TITLE
search fails to find COVID template 

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1082]
Trying to search for 'COVID' I don't find the template Martin created which has that in the name.

https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2Fc46dd7d8-5a12-4e16-9768-53ef32ff806a

Other searches work fine.

**Comment by martinjoconnor** [comment]
Did this get resolved? I think Atti could not reproduce it.

**Comment by graybeal** [comment]
Atti reproduced it (see -- hey! oh, it was in email, appending here). He was never sure why it had happened, but indexing fixed it. So can close it as far as I'm concerned, until we see it again.

> I was looking into this, and I was not able to find the problem yet.
> I tried to reproduce this on my local system, and I was able to do so.
> I tried to see what is the content of the search index, but something is wrong there. I see two options:
>   We messed up something, and actually no search queries should work at all
>   I forgot something, and I am unable to remember how this works, and I am missing an important point, and that is why  I can not figure this out.
> I really hope it is number 2.
 
> So at this moment I started a full search reindex on production.
> I will dig deeper into the code and data, to see what am I missing.
 
> But as a workaround, John, I was wondering if you could possibly do the demo that you need to do with the cedar-admin in the meantime.
> Or share the given folder with everybody. I really hope that that will work.
>
> As I said, I am waiting for the reindex to finish, and also investigating in the meantime.
