### ISSUE TITLE
properties not working in fields

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1083]
When I select a property in a field, the selected property does not get saved. 

(Note this is after multiple searches for classes, and there are known bugs when class search is called repeatedly.)

**Comment by graybeal** [comment]
Here's how I duplicated this.

1) Create a field, it defaults to a term.
2) name the term, I used Search Field for Creators
3) Click on Values tab -> Add button.
4) Click on a matching item. (I clicked on the first one I think. Movie available.)
5) Close the widow (don't bother selecting a term).
6) Now (in the field editor) click on the Property link for the field.
7) Note the first bug, we are still seeing classes in the search. (That's another ticket already.)
8) Click on Start Over.
9) Reenter the search term, I think I entered "Search Field".
10) Select the property that it finds. 
11) Click on the Add Property button.
12) Now (back in the field editor) hover over the Property link for the field. It should show a value, but it doesn't.

**Comment by egyedia** [comment]
Does it matter if you do steps 3 ... 5 before?
I am asking this because I was trying to add a Property to a field, and I was not able to do so at all.
Can you do that, can you add a property?

**Comment by martinjoconnor** [comment]
I'm also not able to add a property even in the simple case.

(1) Create (text) field
(2) Click on Add Property icon.
(3) Search for a random property (for me, the search only shows properties from BioPortal)
(4) Add property

On return from the property selection, there is no property actually attached (JSON Schema view also confirms this)

**Comment by egyedia** [comment]
Fixed on develop.
