### ISSUE TITLE
Bad JSON-LD in artifact

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1095]
(This ticket was created because the RDF at https://openview.metadatacenter.org/template-instances/https:%2F%2Frepo.metadatacenter.org%2Ftemplate-instances%2F562c6553-14b1-4c4b-840f-9210381a28f5 not being filled in.)  

The original "VODAN-COVID-Migrants-Tunisia metadata 22" artifact at https://cedar.metadatacenter.org/instances/edit/https://repo.metadatacenter.org/template-instances/a3908d5c-a79c-43c1-a11a-045b934bd070?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F6ab640b2-942e-40e4-bbd3-458b26e0a907&search=VODAN&t=1598736918915 (and its shared-with-CEDAR-Dev-Team copy at https://cedar.metadatacenter.org/instances/edit/https://repo.metadatacenter.org/template-instances/a3908d5c-a79c-43c1-a11a-045b934bd070), both of which use the template (aso shared with CEDAR Dev Team) at https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/1988902f-9fc0-46bf-8cee-aeec54539cac?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F6ab640b2-942e-40e4-bbd3-458b26e0a907&search=VODAN&t=1598737273352, does not produced JSON-LD which can be parsed at https://json-ld.org/playground/.  The reported parsing error is `jsonld.SyntaxError: Invalid JSON-LD syntax; term in form of IRI must expand to definition.`

Interestingly, although there is RDF produced within the CEDAR metadata editor, the RDF at the OpenView instance of the metadata instance is empty.  (OpenView instance not appended because metadata may be sensitive.)

**Comment by egyedia** [comment]
Fixed, and updated production.
The JSON-LD chexcked on json-ld playground is still invalid, because one of the fields has a forward slash in its name:
"date/time precision"
Removing or replacing that character results in a valid json-ld file.

**Comment by marcosmro** [comment]
We've removed the forward slash from the "date/time precision" field in both the template and the instance. The instance's JSON-LD and RDF representations are valid now. Here is the link instance in OpenView mode: https://openview.metadatacenter.org/template-instances/https:%2F%2Frepo.metadatacenter.org%2Ftemplate-instances%2F562c6553-14b1-4c4b-840f-9210381a28f5

To prevent this issue from happening again, we'll create a new issue to disable forward slashes in field names.
