### ISSUE TITLE
problem with field

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1098]
Johanne reports:

For some reason WMO does not work for me.. I get an error message when I want to save the Field.. See attached image

![Screen Shot 2020-09-09 at 10.55.24 AM.png](https://images.zenhubusercontent.com/5cc9bdc26c1fd80bacaab82a/240ce144-26d1-4475-b262-11a72343704b)

Info about the content:

the repository in CEDAR where the issue is:
https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F1f65953d-a733-4244-88fc-cf4e76e4c0b7
In the field "Grib_code". The error occurs when I add the WMO ontology. The link to the error is: https://resource.metadatacenter.org/template-fields/https%3A%2F%2Frepo.metadatacenter.org%2Ftemplate-fields%2F96cdfb08-e7f0-499f-b7c8-406b1039581c

**Comment by graybeal** [comment]
OK, further diagnostics reveals the following:
* When you set the Values to be the whole WMO ontology:
  * no values get saved (for reasons unknown)
  * the field can't be saved because it created an array for the ontology values, but there are none there, so the field has a JSON syntax violation

If we add a new value the syntax error is still there; but if we delete the WMO ontology the field saves just fine.

Adding one value at a time from WMO works fine—CEDAR can see all the classes, it just can't see them when making the final request.

WMO has known interesting behaviors in BioPortal as well, so while `http://data.bioontology.org/ontologies/WMO/classes` works fine to retrieve all the classes, it's likely that other calls may not work as expected. (Because there's no hierarchy, just a bunch of classes.)

**Comment by graybeal** [comment]
I think we have a call to make about whether there are any changes appropriate to CEDAR here. Depending on the details of what exactly is going wrong, maybe CEDAR needs a defensive check against this kind of result from BioPortal.

**Comment by marcosmro** [comment]
I've taken a look at this issue and it seems that the metrics regeneration completed by Jennifer fixed it. I tried both constraining a field to the full WMO ontology and to just some classes, and both cases worked for me. I've shared with Everybody a folder with the artifacts that I used to do these checks: https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2Ff3bdb503-76ea-4a26-a3bb-63d7b141e341 @graybeal Feel free to close this issue if you also think is solved.

**Comment by graybeal** [comment]
ok, this is weird. when I constrain to full WMO it only finds 5 classes as shown on the ADD display. But if I actually use the system it clearly is seeing way more than 5 classes, likely all of them.

So this would be a minor issue, that the count is incorrect. We could close this and create a new issue for counts if that seems like the right thing to do.

**Comment by marcosmro** [comment]
The problem is that the count is incorrect in BioPortal (see the screenshot below), and that's what CEDAR shows.

![Screen Shot 2020-09-10 at 6 55 28 PM](https://user-images.githubusercontent.com/7634440/92841443-34394080-f397-11ea-8318-255b00d82a62.png)

**Comment by graybeal** [comment]
This is confirmed to not be a CEDAR issue. (The count of 5 is truly the number of classes in the ontology. All the other 'classes' that CEDAR sees are individuals that have been punned as classes.)
