### ISSUE TITLE
Spreadsheet tool

### ISSUE THREAD

**Issue by cebriggs7135** [metadatacenter/cedar-project#1099]
@graybeal 

I'm a new user (from the HuBMAP Consortium at Harvard Med School, DBMI) and can't find your spreadsheet tools.

BTW, contacts on this page:
https://more.metadatacenter.org/tools-training/support
don't work (email bounces back, FORM button is broken).

**Comment by graybeal** [comment]
Thanks for all the feedback Chris. We'll try to fix those connections asap.

 I'm not sure what you are referring to when you say "your spreadsheet tools"—it may be a specific reference on a particular page?  

The CEDAR Workbench itself is not a spreadsheet tool, it has some spreadsheet capability in that certain repeating elements can allow metadata entry using spreadsheet-like tables. The application is at https://cedar.metadatacenter.org, and there are various kinds of documentation referenced at https://metadatacenter.org/references.

Please let me know what you're hoping to find and hopefully I can provide better help.

**Comment by cebriggs7135** [comment]
Thanks for your reply. I've already made a couple of templates myself. I then copied the **Antibody Metadata metadata**  resource type you see one of the screenshots below. When I open this, it has a toggle between list & table format. How do I get the table format for my own templates? There are numerous reference docs on the page you linked and I have already spent a couple of hours looking through a few and trying to use the search tool to find instructions on making spreadsheet template. No such & this is taking too much time. Why can't I find anything  on CEDAR spreadsheets?
![Screen Shot 2020-09-18 at 3 21 07 PM](https://user-images.githubusercontent.com/8284878/93636862-a080f900-f9c2-11ea-88c7-a82eb252db70.png)
![Screen Shot 2020-09-18 at 3 21 13 PM](https://user-images.githubusercontent.com/8284878/93636869-a5de4380-f9c2-11ea-91ec-a312deb8de7f.png)

**Comment by graybeal** [comment]
The spreadsheet view is presented when the following conditions are met:
- the fields for the spreadsheet are contained  as a flat list in an element (i.e., no elements within that element)
- the element has the MULTIPLE setting allowing more than one entry

I'm sorry this isn't more fully documented, and especially that it has been time-consuming for you—I know that's really irritating. CEDAR is a free and open source research project that we are steadily improving, and I'll keep this documentation need front of mind when get my next chance to add to the documentation. Of course you are also welcome to contribute pull requests to code or documentation if there is something you want to add. 

WIth respect to spreadsheets, it is important to note that this capability is provided via third-party software, and we have struggled to have a fully operational and graceful integration with the CEDAR platform. We have several tickets about spreadsheets that describe issues or possible improvements, and we're open to suggestions as to how we might overcome the issues with a reasonable amount of work.

**Comment by cebriggs7135** [comment]
That's great. Thanks for this information. I'll try it out.
Right now, I'm stuck on some error messages when I try to submit a template
I created in CEDAR. I may reach out to you next week if still stuck.
Chris

**Comment by graybeal** [comment]
issues with the connection email and form were addressed per https://github.com/metadatacenter/cedar-metadata-form/issues/12.

**Comment by graybeal** [comment]
Documented the spreadsheet view more clearly in https://metadatacenter.github.io/cedar-manual/sections/a5/2_filling_out_metadata/, and described how to create the template appropriately in https://metadatacenter.github.io/cedar-manual/sections/c2/3_adding_elements/.
