### ISSUE TITLE
Unable to view NCI caDSR CDEs in the CATEGORIES tree

### ISSUE THREAD

**Issue by jvendetti** [metadatacenter/cedar-project#1102]
Steps to reproduce:

1. Log into CEDAR Workbench with a non-administrative account (e.g., I used my own account of Jennifer Vendetti).
2. Drop down the NCI caDSR tree under the CATEGORIES heading on the left-hand side of the page.
3. Try selecting any of the CDEs in the tree, and notice that the center pane says "Nothing found".

![Screen Shot 2020-10-14 at 12 23 00 PM](https://user-images.githubusercontent.com/1696923/96035872-7f23f900-0e18-11eb-9915-0cffbc68d30b.png)

**Comment by egyedia** [comment]
@jvendetti could you please reproduce the error again, and send a screen capture of the DeveloperConsole's "Console" and "Network" tabs, please.

**Comment by jvendetti** [comment]
Screenshot of the Network tab after clicking on the category entitled "ABTC":

![Screen Shot 2020-10-21 at 10 56 19 AM](https://user-images.githubusercontent.com/1696923/96759007-52c62a80-138c-11eb-80e5-461f42ceec35.png)

The Console window is empty - nothing is output for clicks on any of the categories in the tree. Tried using Firefox 82.0 and Chrome Version 86.0.4240.111.

**Comment by egyedia** [comment]
Category search results for: 'NCI caDSR » ABTC » CRF CDEs » 30-Day Follow-Up'
The URL in question is:
https://resource.metadatacenter.org/search?category_id=https:%2F%2Frepo.metadatacenter.org%2Fcategories%2F464e4f98-5cd7-4618-8048-ef60535c817c&limit=100&offset=0&publication_status=all&resource_types=element,field,instance,template,folder&sort=-lastUpdatedOnTS&version=latest

**Comment by egyedia** [comment]
There was an error in the permission computation when the data was prepared for elastic search indexing.
Fixed on develop.
