### ISSUE TITLE
can't save instances

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1117]
User reports: I have an additional question related to CEDAR template https://cedar.metadatacenter.org/templates/edit/https:/repo.metadatacenter.org/templates/3258a592-a0a0-4822-9eda-5cd757e28926. It shows this error below when I try to populate with just very few  metadata -   it: Server Error

(This is a template called COVID Project Content, in All / Shared / COVID Training ZonMW M4M Workshops / Project Metadata Template.)

![image.png](https://images.zenhubusercontent.com/5cc9bdc26c1fd80bacaab82a/1137b124-23d8-4525-9e5a-2cafd134ffba)

this is the error:

![image.png](https://images.zenhubusercontent.com/5cc9bdc26c1fd80bacaab82a/c238feea-1490-4827-a924-d0b217a061a0)

**Comment by marcosmro** [comment]
Find attached another example of template that had this issue, as well as the diff that shows how we fixed it at: https://www.diffchecker.com/9ZJtsLs5

[Covid project content template backup.json.zip](https://github.com/metadatacenter/cedar-project/files/6275128/Covid.project.content.template.backup.json.zip)

**Comment by marcosmro** [comment]
I've fixed it. It was the same issue described at https://github.com/metadatacenter/cedar-project/issues/1107. I've attached the broken template as an example to that issue, as well as a diff that shows how to fix it.
