### ISSUE TITLE
The "Version -> Latest" toggle button seems not working

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-project#1193]
I see no UI changes when playing with the toggle button. I'd expect the old versions will be hidden and the UI only shows the latest version.

**Comment by muakdogan** [comment]
@johardi is this the "Embeddable editor" toggle you are mentioning? Which server did you check this on? Did you try opening a template or an instance after toggling on the new UI?

**Comment by johardi** [comment]
Here's the screenshot to illustrate the bug and it's not the embeddable editor @muakdogan 

<img width="1348" alt="Screenshot 2023-10-04 at 3 09 23 PM" src="https://github.com/metadatacenter/cedar-project/assets/5062950/b0a650d9-ba8e-4d14-a79d-ec092290335f">

**Comment by johardi** [comment]
This feature seems to work as intended. It does show the latest version but along with the latest draft. I will argue showing only the latest draft is a better UX but I'll leave the decision to the project owner. Feel free to close this ticket as needed.
