### ISSUE TITLE
Can't read in-field titles/prompts

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#120]
(Thought this was entered previously, but can't find.)

1) The names within the CEDAR fields are in light gray and unreadable under many circumstances
2) The type of field is very big and bold -- this is marginally useful information and should not be visually strong at all
3) Where does the help text go for a field?

Suggest instead
A) Field name is in top row (big and bold)
B) Prompt text can be help text for now, and also available in mouse-over of Field name
C) Link should be available to extended help (can be linked from top area (?) too
D) Get rid of wasted space in this area

**Comment by martinjoconnor** [comment]
New forms address these issues.
