### ISSUE TITLE
new look and feel shows "Help text" for tips that have no text

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#1202]
In the new look-and-feel of the metadata editor, the help text (tip) button for data entry shows "Help text" when the field has not been configured with help text. This is unfortunate for the UX if there aren't many help text fields filled out.

![Screenshot 2024-02-04 at 6 21 12 PM](https://github.com/metadatacenter/cedar-project/assets/1266896/3efd28bf-044e-474b-9c53-e46c911ed4cb)

**Comment by muakdogan** [comment]
Thanks for reporting this issue!
I opened [this issue](https://github.com/metadatacenter/cedar-template-editor/issues/967) to distribute it under the corresponding project so closing this one.
