### ISSUE TITLE
Fields in read-only templates behave strangely

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#121]
When you click on a field (in the entry box) in a read-only template, the entry box disappears, so now you don't know what the field name is. Or why it disappeared. (Clicking on another field reveals the first.)

The editing should be disabled but the field shouldn't close.

**Comment by willrett** [comment]
can't duplicate.  please be more specific and give me a screen shot.

**Comment by graybeal** [comment]
Damn. Can't duplicate here either. You can sign it off.

Originally used the link Martin provided for his copy of the BioCADDIE template,  https://cedar.metadatacenter.net/dashboard?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F7f0a0f3e-f0e5-4c29-85fa-e646e0fbee22

But behavior doesn't happen any more, at least in FireFox.  May have been caching issue, too.

Sign it off.
