### ISSUE TITLE
Metrics of number of artifacts

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#122]
Need to keep count of how many of each artifact type (shared and not shared would be nice too).

**Comment by martinjoconnor** [comment]
At a minimum we should have a REST summary call. We can the later decide if we want a pretty summary display in the GUI.

**Comment by willrett** [comment]
Add a dashboard page showing repository status which does not require login.

**Comment by martinjoconnor** [comment]
Will be tackled by https://github.com/metadatacenter/cedar-project/issues/51
