### ISSUE TITLE
Scalable solution for filtering of search results

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#126]
Complete solution for partial 0.8 solution in #125.

**Comment by marcosmro** [comment]
A possible solution would be to add user access information to the index. Each resource would include the list of users that have access to it. By doing this, it would be possible to filter the resources at search time, instead of filtering them later.

**Comment by martinjoconnor** [comment]
Verify that following bugs are gone on completion:

metadatacenter/cedar-project#238
metadatacenter/cedar-project#247
