### ISSUE TITLE
View to see resources shared with users

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#145]
We need a way of quickly seeing all resources that are shared with a user.

**Comment by martinjoconnor** [comment]
Several options, including:

(1) share with me folder in use home folder
(2) Google Drive-like area showing popular public resources (which we previously had specified and partially implemented; we referred to this as the 'Populate a Form' area.

**Comment by graybeal** [comment]
Maybe this can be implemented in a way that the first view is rather minimalist, containing only a few resources and 'see more' button, or equivalent.  I think our conclusions from the last go-round, that it was taking up too much space and most people won't need to see it regularly, are still valid.  but I like the idea of having it easily available.


On Sep 22, 2016, at 4:13 PM, martinjoconnor <notifications@github.com<mailto:notifications@github.com>> wrote:


Several options, including:

(1) share with me folder in use home folder
(2) Google Drive-like area showing popular public resources (which we previously had specified and partially implemented; we referred to this as the 'Populate a Form' area.

**Comment by martinjoconnor** [comment]
Corresponding back end task: #220.
