### ISSUE TITLE
Sample data to define calls to PubChem REST API

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#182]
Based on email from Ray (below) look at small molecule verification code and experiment with an initial quick-and-dirty invocation of this validation functionality from CEDAR.

Repo: https://github.com/rterryn/smiles2cid_verify

Basecamp:  https://3.basecamp.com/3464236/buckets/1508912/todos/236183478#__recording_240467527

```
Hello All. I made a repository on my public git for the small molecule verification (structure-to-CID-to-name) pipeline code. 
There is a very general readme and an example input. My git username is 'rterryn' and the repository is named 'smiles2cid_verifiy'. 
It works for 99% of the inputs we receive, but there is another component I need to write that deals with multiple fragment inputs, this will probably be about 6-8 hours of work to get done. 
Internally we use a commercial software solution so I have not needed to build my own until now. Let me know if you want me to send you the code directly, or submit it to a different repository. Thanks. -Ray
```

**Comment by martinjoconnor** [comment]
PubChem REST API: https://pubchem.ncbi.nlm.nih.gov/pug_rest/PUG_REST_Tutorial.html#_Toc458584411

See BaseCamp CEDAR-LINCS threads here:

https://3.basecamp.com/3464236/buckets/1508912/message_boards/236086357

**Comment by rsgoncalves** [comment]
Changed task to be more fine-grained. It is now meant for experimenting with PubChem API with sample data file provided by LINCS.

**Comment by rsgoncalves** [comment]
Progress with PubChem API calls and results is reported @ https://3.basecamp.com/3464236/buckets/1508912/messages/258334527

**Comment by rsgoncalves** [comment]
After receiving the corrected sample data from LINCS, I re-tested the PubChem calls and all the provided details align now; the compound name, CID, and SMILES structure. The test results and PubChem calls used are in the spreadsheet provided in the Basecamp thread linked above.
