### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#183]
Possible improvements: 
- Results ordered by relevance (Lucene score)
- Exact string matching using quotes

Note that we are using the Lucene Query Parser Syntax: https://lucene.apache.org/core/2_9_4/queryparsersyntax.html

**Comment by marcosmro** [comment]
Point 1 from the following: https://docs.google.com/document/d/1UOOADd9bVKKmL8or4W_CuubaucQruKsIZTKkWmMnGZA/edit

**Comment by graybeal** [comment]
Included text from point 1 so it doesn't go away:

Basic improvements. 
- Keyword-based search for resource name, description, field names and field values. 
- Highlight the matches found. 
- Results ordered by relevance.
- Csongor suggested to group the search results into different categories: “found in template title”, “found in field name”, “found in field value”, etc. (these categories would be similar to what Csongor already suggested to Debra, to categorize search result in “templates”, “template elements” and “instance”).
-

**Comment by martinjoconnor** [comment]
Many search improvements since this issue created
