### ISSUE TITLE
Model fixes

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#185]
Model fixes for 1.0.

(1) Correct  the Template Model to use term URIs for element/field types instead of BioPortal URLs

Our templates/elements use the following JSON Schema structure to constrain the values of the @type fields:

```
 "@type": {
    "oneOf": [
      {
        "type": "string",
        "format": "uri",
        "enum": [
          "http://data.bioontology.org/ontologies/SNOMEDCT/classes/http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNOMEDCT%2F703503000"
        ]
      }, {
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://data.bioontology.org/ontologies/SNOMEDCT/classes/http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNOMEDCT%2F703503000"
          ]
        },
        "uniqueItems": true
      }
    ]
  }
```

This is not right. We should not use BioPortal URLs to represent types. Ontology term URIs should be used instead (e.g., http://purl.obolibrary.org/obo/BFO_0000035). However, we still need some way of storing the name of the ontology where the user found the term. A possible solution would be to define an _typeInformation field that would contain the ontology name corresponding to each @type value and any other additional useful information about the annotation.

(2) In CEDAR resources, the `schema:isBasedOn`, `pav:createdOn`, `pav:createdBy`, `pav:lastUpdatedOn`, and `oslc:modifiedBy` fields are effectively represented as strings.

For example:

```
{
   "schema:isBasedOn": "https://repo.metadatacenter.org/template/4343",
   "pav:createdOn": "2016-06-29T10:58:26-0700",
   "pav:createdBy":  "https://repo.metadatacenter.net/users/6d21a887",
   "pav:lastUpdatedOn": "2016-06-29T10:58:26-0700",
    "oslc:modifiedBy": "https://repo.metadatacenter.net/users/6d21a887",
   ...
}
```

However, the `schema:isBasedOn`, `pav:createdBy`,  and `oslc:modifiedBy` fields should be represented as URIs and the `pav:createdOn` and `pav:lastUpdatedOn` fields should be represented as `xsd:dateTime` fields.

We can do this by expanding the current `@context` field to include:

```
@context {
  ...
  "xsd": "http://www.w3.org/2001/XMLSchema#",
  "schema:isBasedOn": { "@type": "@id" },
  "pav:createdBy": { "@type": "@id" }
  "oslc:modifiedBy": { "@type": "@id" }
  "pav:createdOn": {  "@type": "xsd:dateTime" },
  "pav:lastUpdatedOn": {  "@type": "xsd:dateTime" }
}
```

(3) Fields deleted in editor remain in template. (Previously metadatacenter/cedar-project#21)

(4) Some field names are stored as UUIDs. In spreadsheet mode this UUID is displayed instead of the field name. (Previously #318).

(5) Front allows invalid names for fields. e.g., ".." (Previously metadatacenter/cedar-template-server#9.)

(6) The "required" field sometimes has duplicates (which confused some validators, e.g., http://www.jsonschemavalidator.net/).

(7) Add XML schema data types to instances (e.g., xsd:decimal for numeric fields).

(8) Generate "@type": "@id", "@id": "URI1" instead of "@value":"URI1".

(3-6 merged from metadatacenter/cedar-template-editor#531.)

**Comment by martinjoconnor** [comment]
This `_typeConstraints` field would specify additional information for types attached to templates, elements, and fields. 

It could contain an array of objects, each of which would contain additional information for each type specified for a resource. 

A `_typeConstraints` field for a resource containing types `http://purl.obolibrary.org/obo/BFO_0000035` and `http://www.ebi.ac.uk/efo/EFO_0000408` could look as follows:

```
"_typeConstraints": [
  {
      "terminologyServerName": "BioPortal",     
      "terminologyServerURI": "http://bioportal.bioontology.org/",
      "terminologyAcronym": "OBO",
      "resourceURI": "http://data.bioontology.org/ontologies/OBO/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO%2F70000035"
  },
  {
      "terminologyServerName": "BioPortal",     
      "terminologyServerURI": "http://bioportal.bioontology.org/",
      "terminologyAcronym": "EFO",
      "resourceURI": "http://bioportal.bioontology.org/ontologies/EFO?p=classes&conceptid=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000408"
  }
]
```

**Comment by marcosmro** [comment]
I've fixed (2), (3), and (6).

**Comment by marcosmro** [comment]
I fixed (7) and (8). The issues that still need to be fixed are: (1), (4), and (5).

**Comment by martinjoconnor** [comment]
Remaining tasks (1,4,5) moved to #336.
