### ISSUE TITLE
Provide RDF representation of CEDAR instances through REST APIs

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#188]
Provide RDF representation of CEDAR's (JSON-lD-encoded) instances.

See: https://github.com/metadatacenter/cedar-docs/wiki/CEDAR-Template-Instances#representing-template-instances-as-rdf

**Comment by martinjoconnor** [comment]
Worth looking at.

Could link nicely with JSON-LD stripping task  (#315) and help on exploration of schema.org work.

**Comment by johardi** [comment]
A hint for the algorithm development: https://www.w3.org/TR/2014/REC-json-ld-api-20140116/#rdf-serialization-deserialization-algorithms

The JSON-LD 1.1 draft has a further discussion: http://json-ld.org/spec/latest/json-ld/#serializing-deserializing-rdf

**Comment by martinjoconnor** [comment]
Not immediately clear looking at this what the enhancements 1.1 will provide. We definitely need to keep track of it.

**Comment by martinjoconnor** [comment]
Ah - spoke to soon. Here: 

http://json-ld.org/spec/latest/json-ld/#changes-since-1.0-recommendation-of-16-january-2014

Lot of stuff that is not directly relevant to us at the moment since we do not use @graph, force URIs everywhere, and generally limit the JSON-LD we generate to be very simple.

**Comment by johardi** [comment]
I found this nice library https://github.com/jsonld-java/jsonld-java

**Comment by martinjoconnor** [comment]
Nice discovery. Looks like it is actively maintained too.

**Comment by johardi** [comment]
I think I just completed this task :D
The API is superb such that we could write our own RDF serializer. I just implemented the function using the default serializer (NQuadTripleCallback)

**Comment by martinjoconnor** [comment]
Great! Always best to steal code if possible.
