### ISSUE TITLE
Api request get users not working

### ISSUE THREAD

**Issue by akoleti** [metadatacenter/cedar-project#208]
curl -H "Content-Type: application/json" -H "Authorization: apiKey <replaceWithApiKey>" -X GET "https://resource.metadatacenter.net/users/15454a92-caae-4968-86f8-dcec94208873"

**Comment by egyedia** [comment]
The proper call is:
curl -i -H "Content-Type: application/json" -H "Authorization: apiKey abc..." -X GET "https://user.metadatacenter.net/users/15454a92-caae-4968-86f8-dcec94208873"

**Comment by akoleti** [comment]
Thanks it works.
