### ISSUE TITLE
Search totalCount field has incorrect values

### ISSUE THREAD

**Issue by akoleti** [metadatacenter/cedar-project#209]
curl -X GET --header  'Authorization: apiKey 75b7516a-7d7c-4cca-bc56-95e91d91cb28' 'https://resource.metadatacenter.net/search?q=*&limit=10&template_id=https://repo.metadatacenter.net/templates/52f832d1-981e-40be-b261-0ad61785f64e'

**Comment by egyedia** [comment]
It seems like a bug in our code.
As a temporary solution, I would suggest to omit the "limit" parameter, that way the "totalCount" will return the correct value.
We will try to fix this ASAP.

**Comment by martinjoconnor** [comment]
New search approach will help address this

**Comment by egyedia** [comment]
The new search + permission approach solved this.
