### ISSUE TITLE
Deleting fields from the template gui does not remove them from the template json

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#21]

**Comment by martinjoconnor** [comment]
@willrett, is this still true?

**Comment by martinjoconnor** [comment]
Still true. See medatacenter/cedar-template-editor#302

**Comment by egyedia** [comment]
The fields are deleted, but the field names are there in the @context and required.

**Comment by martinjoconnor** [comment]
Merged into metadatacenter/cedar-template-editor#491
