### ISSUE TITLE
Search paging field has incorrect values

### ISSUE THREAD

**Issue by akoleti** [metadatacenter/cedar-project#210]
curl -X GET --header  'Authorization: apiKey 75b7516a-7d7c-4cca-bc56-95e91d91cb28' 'https://resource.metadatacenter.net/search?q=*&limit=5&template_id=https://repo.metadatacenter.net/templates/52f832d1-981e-40be-b261-0ad61785f64e'

**Comment by egyedia** [comment]
Solved by the new search + permissions approach
