### ISSUE TITLE
Searching is flaky #2

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#247]
Not sure if this is the same as #238 or not. I did a search in the folder at 
  https://cedar.metadatacenter.net/dashboard?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2Fd60c4908-cb01-471a-b9ca-c6f71b20501e
and it found 300+ matches. A few minutes later I tried the search again, and got an error message (well, 2 -- maybe I did two searches in a row), details appended:

:
SearchCedar
Search Results For: ''

       
FILTERRESET
TYPE
 Title Created Modified
 2183360 : Laboratory Test Result Numeric Value 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3357530 : Colorectal Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Distant Metastasis M Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3357531 : Colorectal Cancer American Joint Committee on Cancer (AJCC) Edition 7 Group Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3357527 : Colorectal Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Regional Lymph Node N Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3357528 : Colorectal Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Regional Lymph Node N Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3357529 : Colorectal Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Distant Metastasis M Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3357525 : Colorectal Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Tumor T Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3357526 : Colorectal Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Tumor T Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 2453215 : Off-Treatment Study Follow-Up Code 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3436556 : Prostate Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Tumor T Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3436561 : Prostate Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Regional Lymph Node N Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 2003315 : Zubrod Performance Status Score 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3436562 : Prostate Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Distant Metastasis M Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3436563 : Prostate Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Tumor T Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3436564 : Prostate Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Regional Lymph Node N Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3436565 : Prostate Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Distant Metastasis M Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3745011 : Lung Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Tumor T Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3745014 : Lung Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Tumor T Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3745012 : Lung Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Regional Lymph Node N Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3745015 : Lung Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Regional Lymph Node N Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3745013 : Lung Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Distant Metastasis M Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 3745016 : Lung Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Distant Metastasis M Stage 11/28/16 10:03 PM 11/28/16 10:03 PM 
 2180158 : Lansky Performance Status Score 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3122696 : Surgical Resection Procedure Other Specify Text 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3122572 : Surgical Resection Procedure Type 11/28/16 10:02 PM 11/28/16 10:02 PM 
 2179777 : Concomitant Agent Name 11/28/16 10:02 PM 11/28/16 10:02 PM 
 2003870 : Concomitant Agent Concomitant Intervention or Procedure Reason 11/28/16 10:02 PM 11/28/16 10:02 PM 
 2004106 : Dose Limiting Toxicity Ind 11/28/16 10:02 PM 11/28/16 10:02 PM 
 2182832 : Noncompliant Reason Text 11/28/16 10:02 PM 11/28/16 10:02 PM 
 2179986 : Concomitant Medication Use Ind-3 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3419387 : Breast Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Tumor T Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3419391 : Breast Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Distant Metastasis M Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3419407 : Breast Cancer American Joint Committee on Cancer (AJCC) Edition 7 Group Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 88 : Performance Status Assessment Eastern Cooperative Oncology Group Scale 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3419389 : Breast Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Regional Lymph Node N Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3655869 : Breast Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Regional Lymph Node N Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3419406 : Breast Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Distant Metastasis M Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986323 : Duodenum/Ampulla/Jejunum/Ileum Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Clinical Tumor T Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986326 : Duodenum/Ampulla/Jejunum/Ileum Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Tumor T Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3419393 : Breast Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Tumor T Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986350 : Duodenum/Ampulla/Jejunum/Ileum Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Regional Lymph Node N Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986325 : Duodenum/Ampulla/Jejunum/Ileum Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Clinical Distant Metastasis M Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986351 : Duodenum/Ampulla/Jejunum/Ileum Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Distant Metastasis M Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986324 : Duodenum/Ampulla/Jejunum/Ileum Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Clinical Regional Lymph Node N Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986358 : Digestive System Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Group Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986352 : Colon or Rectum Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Clinical Tumor T Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986353 : Colon or Rectum Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Clinical Regional Lymph Node N Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986357 : Colon or Rectum Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Distant Metastasis M Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986356 : Colon or Rectum Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Regional Lymph Node N Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986355 : Colon or Rectum Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Tumor T Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3131309 : Specimen Collection Method Name 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986354 : Colon or Rectum Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Clinical Distant Metastasis M Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986298 : Stomach Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Clinical Regional Lymph Node N Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986311 : Stomach Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Clinical Distant Metastasis M Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986314 : Stomach Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Regional Lymph Node N Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986315 : Stomach Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Distant Metastasis M Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986312 : Stomach Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Tumor T Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 4986297 : Stomach Neuroendocrine Tumor American Joint Committee on Cancer (AJCC) Edition 7 Clinical Tumor T Stage 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3782594 : Withdrawal by Subject Reason Text 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3123079 : Surgical Margin Distance Surgeon Measurement 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3782616 : Patient Notification Treating Site Consent Amended Date 11/28/16 10:02 PM 11/28/16 10:02 PM 
 2182671 : Other Body System/Site Text 11/28/16 10:02 PM 11/28/16 10:02 PM 
 2184691 : Screen Date 11/28/16 10:02 PM 11/28/16 10:02 PM 
 2960675 : Clinical Trial Screening Indicator 11/28/16 10:02 PM 11/28/16 10:02 PM 
 2960860 : Clinical Trial Screening Ineligibility Reason Text 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3021572 : Post Clinical Trial Treatment Type 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3783584 : Witness Confirmation Patient Withdraw Quality of Life Consent Date 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3836018 : Person Imaging Agent Fasting Drink Exercise Required Complete Yes No Unknown Indicator 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3380276 : Emission Scan Start Time 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3380277 : Emission Scan Stop Time 11/28/16 10:02 PM 11/28/16 10:02 PM 
 2718366 : Emission Scan Acquisition Mode Type 11/28/16 10:02 PM 11/28/16 10:02 PM 
 3916051 : Emission Scan Post Radioactivity Start Time 11/28/16 10:01 PM 11/28/16 10:01 PM 
 2002895 : Body System Type 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3916052 : Emission Scan Post Radioactivity Stop Time 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3916053 : Emission Scan Post Radioactivity Acquisition Duration Minute Number 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3916058 : PET Emission Scan with CT or MRI Yes No Unknown Indicator 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3781754 : Patient Informed Consent Cancel Withdrawal Other Paperwork Text 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3775411 : Patient Informed Consent Cancel Withdrawal Paperwork Type 11/28/16 10:01 PM 11/28/16 10:01 PM 
 4983471 : Adrenal Cortical Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Tumor T Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 4983474 : Adrenal Cortical Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Tumor T Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 4983475 : Adrenal Cortical Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Regional Lymph Node N Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 4983472 : Adrenal Cortical Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Regional Lymph Node N Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 4983473 : Adrenal Cortical Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Distant Metastasis M Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 65078 : Specimen Fixative Type 11/28/16 10:01 PM 11/28/16 10:01 PM 
 4983476 : Adrenal Cortical Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Distant Metastasis M Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 4983477 : Adrenal Cortical Cancer American Joint Committee on Cancer (AJCC) Edition 7 Group Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3437201 : Ovarian Cancer American Joint Committee on Cancer (AJCC) Edition 7 Group Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3447422 : Fallopian Tube Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Distant Metastasis M Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3447365 : Fallopian Tube Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Tumor T Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3447421 : Fallopian Tube Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Regional Lymph Node N Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3447466 : Fallopian Tube Cancer American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Distant Metastasis M Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3447467 : Fallopian Tube Cancer American Joint Committee on Cancer (AJCC) Edition 7 Group Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3447364 : Fallopian Tube Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Tumor T Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3447420 : Fallopian Tube Cancer American Joint Committee on Cancer (AJCC) Edition 7 Clinical Regional Lymph Node N Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 2230047 : Specimen Accession Number 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3447309 : Uterine Adenosarcoma American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Distant Metastasis M Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3447310 : Uterine Adenosarcoma American Joint Committee on Cancer (AJCC) Edition 7 Group Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3447304 : Uterine Adenosarcoma American Joint Committee on Cancer (AJCC) Edition 7 Clinical Tumor T Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3447305 : Uterine Adenosarcoma American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Tumor T Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 3447307 : Uterine Adenosarcoma American Joint Committee on Cancer (AJCC) Edition 7 Pathologic Regional Lymph Node N Stage 11/28/16 10:01 PM 11/28/16 10:01 PM 
 Standard CDEs
Typefolder
Location/Users/Kathryn Collins/Standard CDEs
OwnerKathryn Collins
Modified11/28/16 9:48 PM by Kathryn Collins
Created11/28/16 9:48 PM by Kathryn Collins
Can readtrue
Can writefalse
Can change ownerfalse
 
Technical details of error

Status: 500, Internal Server Error
URL: https://resource.metadatacenter.net/search?limit=100&offset=0&q=:&resource_types=element,field,instance,template,folder&sort=-lastUpdatedOnTS
Method: GET

Message: all shards failed
Exception: Failed to execute phase [query], all shards failed; shardFailures {[6-twHrpKTjOSCIwkMBKdYg][cedar-search-1479858591401][0]: RemoteTransportException[[Penance][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"size":100,"query":{"bool":{"must":[{"query_string":{"query":":","fields":["info.name"]}},{"bool":{"should":[{"term":{"info.nodeType":"element"}},{"term":{"info.nodeType":"field"}},{"term":{"info.nodeType":"instance"}},{"term":{"info.nodeType":"template"}},{"term":{"info.nodeType":"folder"}}]}}]}},"sort":[{"info.lastUpdatedOnTS":{"order":"desc"}}]}]]; nested: QueryParsingException[Failed to parse query [:]]; nested: ParseException[Cannot parse ':': Encountered " ":" ": "" at line 1, column 0. Was expecting one of: ... "+" ... "-" ... ... "(" ... "*" ... ... ... ... ... ... "[" ... "{" ... ... ... "*" ... ]; nested: ParseException[Encountered " ":" ": "" at line 1, column 0. Was expecting one of: ... "+" ... "-" ... ... "(" ... "*" ... ... ... ... ... ... "[" ... "{" ... ... ... "*" ... ]; }{[6-twHrpKTjOSCIwkMBKdYg][cedar-search-1479858591401][1]: RemoteTransportException[[Penance][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"size":100,"query":{"bool":{"must":[{"query_string":{"query":":","fields":["info.name"]}},{"bool":{"should":[{"term":{"info.nodeType":"element"}},{"term":{"info.nodeType":"field"}},{"term":{"info.nodeType":"instance"}},{"term":{"info.nodeType":"template"}},{"term":{"info.nodeType":"folder"}}]}}]}},"sort":[{"info.lastUpdatedOnTS":{"order":"desc"}}]}]]; nested: QueryParsingException[Failed to parse query [:]]; nested: ParseException[Cannot parse ':': Encountered " ":" ": "" at line 1, column 0. Was expecting one of: ... "+" ... "-" ... ... "(" ... "*" ... ... ... ... ... ... "[" ... "{" ... ... ... "*" ... ]; nested: ParseException[Encountered " ":" ": "" at line 1, column 0. Was expecting one of: ... "+" ... "-" ... ... "(" ... "*" ... ... ... ... ... ... "[" ... "{" ... ... ... "*" ... ]; }{[6-twHrpKTjOSCIwkMBKdYg][cedar-search-1479858591401][2]: RemoteTransportException[[Penance][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"size":100,"query":{"bool":{"must":[{"query_string":{"query":":","fields":["info.name"]}},{"bool":{"should":[{"term":{"info.nodeType":"element"}},{"term":{"info.nodeType":"field"}},{"term":{"info.nodeType":"instance"}},{"term":{"info.nodeType":"template"}},{"term":{"info.nodeType":"folder"}}]}}]}},"sort":[{"info.lastUpdatedOnTS":{"order":"desc"}}]}]]; nested: QueryParsingException[Failed to parse query [:]]; nested: ParseException[Cannot parse ':': Encountered " ":" ": "" at line 1, column 0. Was expecting one of: ... "+" ... "-" ... ... "(" ... "*" ... ... ... ... ... ... "[" ... "{" ... ... ... "*" ... ]; nested: ParseException[Encountered " ":" ": "" at line 1, column 0. Was expecting one of: ... "+" ... "-" ... ... "(" ... "*" ... ... ... ... ... ... "[" ... "{" ... ... ... "*" ... ]; }{[6-twHrpKTjOSCIwkMBKdYg][cedar-search-1479858591401][3]: RemoteTransportException[[Penance][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"size":100,"query":{"bool":{"must":[{"query_string":{"query":":","fields":["info.name"]}},{"bool":{"should":[{"term":{"info.nodeType":"element"}},{"term":{"info.nodeType":"field"}},{"term":{"info.nodeType":"instance"}},{"term":{"info.nodeType":"template"}},{"term":{"info.nodeType":"folder"}}]}}]}},"sort":[{"info.lastUpdatedOnTS":{"order":"desc"}}]}]]; nested: QueryParsingException[Failed to parse query [:]]; nested: ParseException[Cannot parse ':': Encountered " ":" ": "" at line 1, column 0. Was expecting one of: ... "+" ... "-" ... ... "(" ... "*" ... ... ... ... ... ... "[" ... "{" ... ... ... "*" ... ]; nested: ParseException[Encountered " ":" ": "" at line 1, column 0. Was expecting one of: ... "+" ... "-" ... ... "(" ... "*" ... ... ... ... ... ... "[" ... "{" ... ... ... "*" ... ]; }{[6-twHrpKTjOSCIwkMBKdYg][cedar-search-1479858591401][4]: RemoteTransportException[[Penance][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from":0,"size":100,"query":{"bool":{"must":[{"query_string":{"query":":","fields":["info.name"]}},{"bool":{"should":[{"term":{"info.nodeType":"element"}},{"term":{"info.nodeType":"field"}},{"term":{"info.nodeType":"instance"}},{"term":{"info.nodeType":"template"}},{"term":{"info.nodeType":"folder"}}]}}]}},"sort":[{"info.lastUpdatedOnTS":{"order":"desc"}}]}]]; nested: QueryParsingException[Failed to parse query [:]]; nested: ParseException[Cannot parse ':': Encountered " ":" ": "" at line 1, column 0. Was expecting one of: ... "+" ... "-" ... ... "(" ... "*" ... ... ... ... ... ... "[" ... "{" ... ... ... "*" ... ]; nested: ParseException[Encountered " ":" ": "" at line 1, column 0. Was expecting one of: ... "+" ... "-" ... ... "(" ... "*" ... ... ... ... ... ... "[" ... "{" ... ... ... "*" ... ]; }

Stack trace:

org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:228)<br />org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:174)<br />org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)<br />org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)<br />org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)<br />org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)<br />org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)<br />java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)<br />java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)<br />java.lang.Thread.run(Thread.java:745)

OK

**Comment by egyedia** [comment]
The new search + permissions approach probably solved this. I will close it. If it appears again, please report it.
