### ISSUE TITLE
Create folder for each group?

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#249]
(Moved from #246) 
I think we should have a place for folders that correspond to certain groups. Maybe it is analogous to the /Users folders -- every group gets a folder under /Groups, and the contents are visible to everyone in that group, but not anyone else (unless they are shared more widely). in other words, the folder contents are really a view on what artifacts are readable or writeable by members of that group. Any artifacts shared with that group that are also shared with everyone will be visible to everyone.
  This needs a little more thought but it feels like it could be intuitive.

**Comment by martinjoconnor** [comment]
No subsequent requests for this feature
