### ISSUE TITLE
Initial requirements for versioning/provenance/resource references

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#253]
Implementation tasks:

metadatacenter/cedar-project#57
metadatacenter/cedar-template-server#6
metadatacenter/cedar-project#203

**Comment by graybeal** [comment]
I think I should put the spreadsheet into a Google sheet and continue filling it out there, yes?  I'll add the sheet URI to this thread, if that makes sense.

**Comment by martinjoconnor** [comment]
Yup - I will link it here shortly. And create link in main provenance task.

**Comment by martinjoconnor** [comment]
This will feed in to the first class references requirements task (#300).
