### ISSUE TITLE
template branding/certification

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#257]
For a given template, give groups the ability to associate that template to their group (ideally with group logo) so that people can tell the template has been certified by the group. 

This provides a way to indicate a template is 'official', a la 'official home pages' on the web. So people can distinguish the one that is approved, vs other copy-cats that have not been approved.

(Requested: Leslie Derr, NIH)

**Comment by martinjoconnor** [comment]
Already implemented for NCI CDEs
