### ISSUE TITLE
Investigate BioPortal concept centric support requirements

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#266]
Even though we do not plan to add support for concept centric classes to CEDAR for 1.0 we should determine some initial requirements so that work could potentially start on the BioPortal side.

**Comment by marcosmro** [comment]
More info at: https://docs.google.com/document/d/120nZDBwNQAJV2M8lKMTJcztH4ulBmfSrKePmMRiTc5A/edit#
