### ISSUE TITLE
Error when making a copy of a writable resource

### ISSUE THREAD

**Issue by rsgoncalves** [metadatacenter/cedar-project#269]
Share a resource with user X, and give 'write' permission.
Login as user X.
Go to shared file (currently by navigating to the folder of the user who shared the file), and try to make a copy.
The following error occurs:

    Status: 403, Forbidden
    URL: https://resource.metadatacenter.orgx/command/copy-resource-to-folder
    Method: POST

    Message: The user has no write access to the target folder:https://repo.metadatacenter.orgx/folders/b47bba12-d658-4bc5-842d-326a0a2425d1

**Comment by egyedia** [comment]
The frontend should use the currentUserPermissions array for current folder to selectively disable the "Make a copy" menu item if the current folder is not writeable.

**Comment by graybeal** [comment]
Not sure I'm following how this is supposed to work. If I have read access to a shared document, I may be in a non-writeable folder, but still I should be able to make a copy, so the menu item should be enabled. Perhaps the correct action is to prompt me for what folder to make the copy into?

**Comment by martinjoconnor** [comment]
The 'Copy to...' menu option (which is pending: https://github.com/metadatacenter/cedar-template-editor/issues/511) will handle this. 'Make a Copy' is a quick link to make a copy in the current directory.

**Comment by willrett** [comment]
make a copy is hidden if current folder is not writable

**Comment by rsgoncalves** [comment]
According to the title, the folder was writable, hence the surprise :)

**Comment by rsgoncalves** [comment]
I see. What folder is one in after doing a search?

**Comment by willrett** [comment]
If you are on a writable folder you can make a copy of a writable resource.  If you are in  Shared with Me mode  and copy a writable resource, it gets copied to the active folder, i.e. the the last folder you looked at.  If that is writable, the Make a Copy is visible.
