### ISSUE TITLE
Search apparently does not find resources with long names

### ISSUE THREAD

**Issue by rsgoncalves** [metadatacenter/cedar-project#272]
To replicate:
* Create folder named "SharedFolder7328392896".
* Search for "SharedFolder7328392896" and notice that no results come up.
* Now search for "SharedFolder73283928" and notice that the folder shows up as a result.

**Comment by marcosmro** [comment]
The cause of this issue is that the max_gram parameter in Elasticsearch was initially set to 20. Because of performance reasons, it is a good practice to keep this value as small as possible. I have increased it to 40. This value should be enough to satisfy our users' needs.
