### ISSUE TITLE
User dumped back to home folder on exit from instance and element

### ISSUE THREAD

**Issue by chung88** [metadatacenter/cedar-project#282]
The back arrow next to the name of the template and/or element takes the user back to the location where the template or element was created and not the location where it has been moved to.

**Comment by martinjoconnor** [comment]
We don't understand the moving  part. The back button behaves as expected for us after a move.

Can you list the steps needed to reproduce this problem.

**Comment by chung88** [comment]
I recorded into a movie (backButtonCedar.mov) the back arrow behaviour.


________________________________

**Comment by martinjoconnor** [comment]
Thanks for the movie. We thought we had fixed this but it seems to have come back. We will take a look at it.
