### ISSUE TITLE
Details sidebar should show correct owner after ownership changes

### ISSUE THREAD

**Issue by rsgoncalves** [metadatacenter/cedar-project#290]
To replicate:
* Create a new folder
* Select folder and change ownership to some other user
* Open the sidebar with the folder selected
* Notice that the owner is still the original creator

Notice also that, as expected, the value for 'Can change owner' becomes 'false'.

**Comment by egyedia** [comment]
The backend had a bug, which could be related to this, but that is fixed now.
However it is true, that after changing the permissions of a folder, we should reload the summary of that folder. This way the info panel data will be updated.
