### ISSUE TITLE
Revisit Dependency Injection framework

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-project#3]
Guice probably

**Comment by graybeal** [comment]
what's a DI framework?

**Comment by martinjoconnor** [comment]
Dependency injection. Primarily needed to support a central configuration mechanism for a deployment on a machine (though has many other advantages). Can then be used to facilitate quick deployment of new instances.

**Comment by martinjoconnor** [comment]
Mostly done. Needed in a a few remaining servers.

**Comment by martinjoconnor** [comment]
Implemented via Guice but not very flexible.

**Comment by martinjoconnor** [comment]
Dropwizard upgrade address this.
