### ISSUE TITLE
Inconsistent behaviour of "Make a copy"

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-project#301]
The below is not 100% critical, but we should think about it.
And also, it is consistent, just not totally transparent for the average user.

In case of a success, Make a copy says "The resource was copied to the current folder"

If we are in the "Shared with me" view, and we are making a copy of a shared object, the outcome is dependent on the previous folder that we were in:
	1) If we were in a folder for which we have write access, the make a copy will succeed
	2) If we were in a folder without write access, it will fail.

The same is true if we do a "Make a copy" in a search result.

"Make a copy" really means "Clone" for us. Maybe we should not allow it in non-folder views:
	in search
	in shared with me

Or we could rename it "Make a copy into my home folder" if we are in Search or Shared with me.

If we are in somebody's folder, only readable for us, we could disable the context menu totally, or make it say "make a copy into my home folder".

Or pop up a dialog, and say: 'You can not copy it here, do you want to make a copy into your home folder'?

**Comment by graybeal** [comment]
Or could we make shared with me view not impact the current folder, name of which could be viewed even during SWM mode? Then when I turn off SWM, I'm back where I started -- indeed if I ever left. And copy destination context is always clear.


________________________________

**Comment by willrett** [comment]
The copy destination is always known to the user in the copy modal.  The modal also now has a quick link to the user's home folder, so that makes it easier go get there.   I recommend leaving the dialog as it is until we get user feedback to suggest otherwise.
