### ISSUE TITLE
Make a Copy revisions

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#305]
The resource server calls for copyResourceToWorkspace and copyResource will include the new title in the "title" field, not "titleTemplate".  Also it will already be translated to the correct language.

**Comment by egyedia** [comment]
I suggest we address this after the 1.0.0 release.
Our current solution works well with the UI, however it could be not straightforward for the REST API user. We can solve this by documenting the call.

**Comment by martinjoconnor** [comment]
I'll assign it to milestone 1.1.

**Comment by martinjoconnor** [comment]
No longer relevant - code has long since evolved.
