### ISSUE TITLE
Resource owner does not have write permissions in some situations

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#310]
I don't know how it happened, but the metadata says I'm the owner of this file. But I don't have write permission on it. How can the owner not have write permission? (I suspect I am not really the owner of the file.)

https://cedar.metadatacenter.net/elements/edit/https://repo.metadatacenter.net/template-elements/7e0b8390-fe6f-488a-a42f-661ec6a0ebfc

![screen shot 2017-02-10 at 6 14 01 pm](https://cloud.githubusercontent.com/assets/1266896/22850375/27210914-efbd-11e6-80ca-edc3cbca4875.png)

**Comment by egyedia** [comment]
The file actually belongs to Daniel Cooper. 
You can check this if you open the sharing dialog.
The info panel had a bug, and was always showing the current user as the owner of the resources. This is fixed, it works as expected on staging. It will be fixed on production once we do a release.
