### ISSUE TITLE
swagger doc links no longers work

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#312]
CEDAR REST APIs documentationn page at https://github.com/metadatacenter/cedar-docs/wiki/CEDAR-REST-APIs links to REST API documentation e.g., at https://resource.metadatacenter.net/, but that page just displays 
{"name":"CEDAR Resource Server"}. How to get to swagger docs?

**Comment by martinjoconnor** [comment]
Need wiring for Dropwizard: https://github.com/metadatacenter/cedar-project/issues/264

**Comment by martinjoconnor** [comment]
Now incorporated by cedar-project#264
