### ISSUE TITLE
Deleting one's home folder should not result in corrupted workspace

### ISSUE THREAD

**Issue by rsgoncalves** [metadatacenter/cedar-project#317]
I've just deleted the home folder of 'Test User 2' by accident (being logged in as 'Test User 2'), and the system allowed me to do it. If this is by design, then there should be some way to recover from it, because afterwards a new home folder cannot be created (no write permissions to '/Users/'), and so the system becomes unusable afaict (with the exception of shared items that can still be used).

**Comment by egyedia** [comment]
User home folders can not be deleted anymore. This was fixed in the last two weeks
