### ISSUE TITLE
List of folders in 'Move To' dialog is not complete

### ISSUE THREAD

**Issue by rsgoncalves** [metadatacenter/cedar-project#320]
The items presented are limited to 100, just like the workspace, but the list does not expand to show subsequent items.

**Comment by willrett** [comment]
Need to add paging to the list of destinations returned for move to and copy to dialogs.  Sort also?

**Comment by egyedia** [comment]
I just modified the defaults on the server side. Default is 100 everywhere, max is 500.
This is valid for browsing, searching, shared with me, everything.
I guess the REST call will support the paging.
