### ISSUE TITLE
Folder content / search result totalCount should be updated during paging

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-project#327]
I did the following: I had a background task, which was POSTing instances in the background.
In the UI I was watching the target folder. I was able to scroll down several times, and the auto scrolling picked up the instances that were created in the background.
The REST responses had a proper - increasing - totalCount in them. The frontend was not updated, so you could arrive at a point where it said:
Displaying 1 - 500 of 345

The totalCount should be updated after every load.

**Comment by willrett** [comment]
fixed
