### ISSUE TITLE
Add clone templates/elements ability

### ISSUE THREAD

**Issue by rdshankar** [metadatacenter/cedar-project#33]
In order to create a new template/element based on an existing template/element, support cloning an element

**Comment by martinjoconnor** [comment]
Related to metadatacenter/cedar-project#12

**Comment by martinjoconnor** [comment]
Some text from @amrapalijz:

Another way of duplicating an element or even a template could be by just copying the JSON description from one element and creating a new element and then just pasting that JSON. This feature is available in google refine to performing the operations done on one file on to another file: https://github.com/OpenRefine/OpenRefine/wiki/History.

**Comment by willrett** [comment]
You are suggesting this:  "Copy that JSON off to the clipboard. Then in the second project, in the undo/redo history, click Apply... and paste in that JSON".   What is the problem that we are trying to solve exactly?

**Comment by martinjoconnor** [comment]
Make a copy now exists.
