### ISSUE TITLE
New subdomains in DNS

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-project#333]
Please add the following two subdomains to our production server DNS zone:

worker.metadatacenter.net
submission.metadatacenter.net

Also please double check that staging and production have the same list of subdomains.

**Comment by alexskr** [comment]
added two subdomains.
I also created a helper script for manually renewing and expanding letsencrypt certificates to include new subdomains

**Comment by martinjoconnor** [comment]
Great. Thanks. Can you point us to the script.
