### ISSUE TITLE
Server Side Configuration

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#339]
Separate configuration for the servers, have some common config, and dedicated configs

Upgrade Keycloak

Upgrade Neo4j

Configure nginx logging to the same folder as the app logs

Introduce CEDAR_VERSION environment variable, us it in the js tests, index.html replacement with gulp and possibly in the build process

Think again about the Keycloak event listener. Try to minimize work performed at a login or page refresh

**Comment by egyedia** [comment]
The CEDAR_VERSION env var is done.
I entered the other issues as separate entries.
