### ISSUE TITLE
CREATE NEW does not work from the Elements List page

### ISSUE THREAD

**Issue by rdshankar** [metadatacenter/cedar-project#34]
Clicking the CREATE NEW button on the 'All Elements list' page (https://cedar.metadatacenter.net/elements/list) does not do anything.

**Comment by martinjoconnor** [comment]
Ignore for the moment because the new search and browse functionality will replace this.

**Comment by martinjoconnor** [comment]
Probably should try to fix because we will still use this for Portland demo.
