### ISSUE TITLE
BioPortal property search endpoint

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#340]
Implement the following BioPortal endpoints:

1) Property search. Search for properties by label and by id. 
- For labels, support substring search (e.g., find ‘hasDisease’ when searching for ‘disease’).
- Optionally, filter results by ontology

2) Find property by ontology id and property id.

**Comment by martinjoconnor** [comment]
Needed for 1(b-f) here:

https://docs.google.com/document/d/1Qs-t3_BN5-Ktspfb7A51a_Hj-rZX9P0T9T29TpJZkCM/edit
