### ISSUE TITLE
BioPortal property tree endpoint

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#341]
Implement BioPortal endpoints to:

1) Get property tree for a particular ontology.
2) Get property tree expanded for a certain property id.

**Comment by martinjoconnor** [comment]
Optionally needed for 1(b-f) here:

https://docs.google.com/document/d/1Qs-t3_BN5-Ktspfb7A51a_Hj-rZX9P0T9T29TpJZkCM/edit
