### ISSUE TITLE
Rename template and folder server

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-project#344]
It is a minor thing, but I think we could rename these two servers to better reflect their actual role.

I would suggest:
* template renamed into "document"
* folder renamed into "filesystem", or even "drive" if that will not lead to a lawsuit.

We should talk about this next week as well.

**Comment by martinjoconnor** [comment]
Will rename cedar-folder-server to cedar-workspace-server. We will keep cedar-template-server as is.
