### ISSUE TITLE
Ownership transfers shouldn't leave resources orphaned

### ISSUE THREAD

**Issue by rsgoncalves** [metadatacenter/cedar-project#345]
* create a folder "test" as User 1
* share "test" with User 2 and give ownership permission
* switch User 1's permissions from "can write" to "can read"
* logout and login as User 2
* delete the folder "test"
* logout and login as User 1
* notice the folder still appears under "Shared with me", but now nothing can be done to it as the owner deleted it, and no other user has write access.

I tried to replicate the above, but after transferring ownership the resources wouldn't appear under 'Shared with me'.

**Comment by willrett** [comment]
cannot reproduce
