### ISSUE TITLE
Improve performance of Protractor tests

### ISSUE THREAD

**Issue by rsgoncalves** [metadatacenter/cedar-project#349]
Currently the permissions tests exceed the maximum amount of build time that Travis CI allows for open source projects. See [https://travis-ci.org/metadatacenter/cedar-template-editor/builds/211135966](https://travis-ci.org/metadatacenter/cedar-template-editor/builds/211135966).

**Comment by egyedia** [comment]
Is it possible - just for now - to split the tests in more batches?
I did some refactoring on a branch which I would really like to merge to develop.
But before doing this, I would like to run as many tests as possible.
It would be really nice if we would have these tests on develop.

**Comment by rsgoncalves** [comment]
Not sure I follow re: batches. The issue is with their cumulative build time on Travis. The tests can be ran locally, or against staging as there are no build time restrictions. I'll merge with develop tomorrow so that you can run them yourself.

**Comment by egyedia** [comment]
Thank you for the merge in advance.
Yes, now that I gave it a second thought, I do not know how I would split the tests in batches to go around this timeout. 
Probably it could work if we would have several branches with batches of tests.
But I don't think this is the path that we want to follow.

**Comment by martinjoconnor** [comment]
Effectively addressed for quite a while now.
