### ISSUE TITLE
Copying a folder should not throw error

### ISSUE THREAD

**Issue by rsgoncalves** [metadatacenter/cedar-project#350]
To replicate:
* Create `folderA` and `folderB`
* Copy `folderA` into `folderB` (either via more-options or right-click)
* Notice the error:  
Status: 400, Bad Request
URL: https://resource.metadatacenter.orgx/command/copy-resource-to-folder
Method: POST
Error key: unknownNodeType

**Comment by egyedia** [comment]
I fixed this one on the REST side.
For now we do not allow folder copy, since we do not have asynchronous file system operations.
The front end should take this into consideration as well:
     The "Copy to" should be disabled on folders.

**Comment by willrett** [comment]
done, but cannot currently merge with develop
