### ISSUE TITLE
REST instance submission framework

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#354]
Allow template designer to specify URI of REST API to submit instance. Presence of submission URI will indicate that front end should present a submission button. Pressing this button invokes the specified URI with the associated template instance as payload. Based on submission response, front end will indicate successful submission or list of errors and warnings.

Response could look something like:

```
{
  "validates": true,
  "info": [ "message1", "message2" ],
  "errors": [ "message1", "message2" ],
  "warnings":  [ "message1", "message2" ]
}
```

**Comment by willrett** [comment]
LINCS wants to demo feature on May 12th

**Comment by martinjoconnor** [comment]
LINCS feature hard coded for the moment. Generic implementation still pending.

**Comment by martinjoconnor** [comment]
This is rendered moot by new submission approach (https://github.com/metadatacenter/cedar-template-editor/issues/668).
