### ISSUE TITLE
Update tests  to use sharding

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#357]

**Comment by rsgoncalves** [comment]
See (https://github.com/travis-ci/travis-ci/issues/7098)[this issue] about the 50-minute timeout in Travis CI.

**Comment by willrett** [comment]
turning on sharding causes random failures syncing to the page.

**Comment by willrett** [comment]
Getting random error ... Failed: Error while waiting for Protractor to sync with the page: "Cannot read property '$$testability' of undefined"

ShardTestFiles works great without Travis, but gets this error when running with Travis.  Probably needs some change to the .travis.yml config.

**Comment by willrett** [comment]
This was fixed by using Travis stagings for running tests in parallel.
