### ISSUE TITLE
Checkbox Fields Appear Incorrectly for Template Filling

### ISSUE THREAD

**Issue by djc183** [metadatacenter/cedar-project#367]
When filling out a template containing checkbox fields, selections are not displayed - instead, 
{{getValueString(valueElement)}} is the visible text, both before and after any box(es) are selected.

![image](https://cloud.githubusercontent.com/assets/24969261/24213426/c5385ba6-0f08-11e7-8ef9-96e28cd60307.png)

**Comment by marcosmro** [comment]
This issue has been already addressed as part of https://github.com/metadatacenter/cedar-project/issues/362 (7). This fix will be released to production by the end of March, as part of release 1.0.5.
