### ISSUE TITLE
Nested entities not displaying on template expansion

### ISSUE THREAD

**Issue by djc183** [metadatacenter/cedar-project#368]
When building a template based on entities nested at different levels - i.e. template has both template-->entity group-->entity containing fields and template-->entity containing fields, the upper levels do not expand properly:

![image](https://cloud.githubusercontent.com/assets/24969261/24213637/8c80b3a2-0f09-11e7-81ee-cdc858000654.png)

![image](https://cloud.githubusercontent.com/assets/24969261/24213685/b557c41e-0f09-11e7-9c83-03b756d99652.png)

Arrow for "LINCS Small Molecule Metadata" pointed down, but no field displayed.

Only the "Small molecule experimental metadata" portion is displayed in the metadata JSON, but everything is displayed in full template JSON.

![image](https://cloud.githubusercontent.com/assets/24969261/24213776/018ab58a-0f0a-11e7-8b22-8627ab1f44cc.png)

![image](https://cloud.githubusercontent.com/assets/24969261/24213816/27b140c6-0f0a-11e7-8adc-efe2ac1fe84b.png)

**Comment by martinjoconnor** [comment]
Thanks for the bug report. We are looking into this.
