### ISSUE TITLE
Consider changing E2E testing framework from Protractor to Cypress

### ISSUE THREAD

**Issue by rsgoncalves** [metadatacenter/cedar-project#369]
https://www.cypress.io

Some of the advantages that caught my eye:
* Easier debugging within the browser
* Consistent results - It runs inside the browser instead of driving the browser like Selenium. This means less brittle, flaky tests.
* No need for Selenium
* Supposedly significantly faster than Protractor
* Ability to execute a specific test in a suite without the hassle of turning off all the other test suites

**Comment by martinjoconnor** [comment]
Some related links:

http://blog.xebia.com/cypress-dealing-with-flaky-tests/
http://corgibytes.com/blog/2017/02/21/integration-tests-fun/

**Comment by martinjoconnor** [comment]
Think we are now happy with unit test framework for many tests and Protractor will suffice for E2E tests.
