### ISSUE TITLE
Support searching for ontologies, in addition to search for classes

### ISSUE THREAD

**Issue by rdshankar** [metadatacenter/cedar-project#37]

**Comment by martinjoconnor** [comment]
Interface is confusing. You have to select "Browse Ontology" before searching.

<img width="942" alt="screen shot 2016-03-31 at 3 11 07 pm" src="https://cloud.githubusercontent.com/assets/1731323/14192500/d617eb18-f752-11e5-9072-ef9123f01c9c.png">

**Comment by martinjoconnor** [comment]
Issue #130 is now addressing this.
