### ISSUE TITLE
Store user profile in Neo4j

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-project#381]
Currently we store the user profile as a JSON object in MongoDB.
We also have a user Node in the neo for each user. We use this neo node for permissions, group membership.
The Mongo version is not really used, just read and updated some times.
I was wondering if we should keep this user profile in Neo4j as well.

Note: The group has no current representation in Mongo, only in Neo4j

Requires metadatacenter/cedar-resource-server#61

**Comment by martinjoconnor** [comment]
We have decided to put the profile in Neo4j. 

Will simplogy development of the submission server back end in Neo (https://github.com/metadatacenter/cedar-resource-server/issues/61).
