### ISSUE TITLE
Home directory resource copy shortcut

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#387]
When making a copy of a resource, the dialog box should include home directory as a selection (so user doesn't have to navigate up and then down multiple levels).

**Comment by martinjoconnor** [comment]
From @michelleif:

If someone shares a template with me, a common task I'd want to do is to copy that template to my own folder, to then create another template based off it. So I go to "Shared with Me" and find the template. I copy it. CEDAR asks me where I want to put it, and offers the folder the template is already in. If I want to copy it to my own user folder, I have to figure out how to navigate to my own folder. I can't find my own "home" folder.

**Comment by willrett** [comment]
I have added an icon for home which takes to to the home folder.  This is in both the copy and move dialogs.
