### ISSUE TITLE
Shared with Me doesn't show recent items

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#397]
Nancy created a "Sound recording metadata" template and "Sound recording instance" instance of it. I found them by navigating to her folder.

When I search for "Sound" I see them. But when I set "Shared with Me" (without searching) they are not visible in the list.

**Comment by egyedia** [comment]
@graybeal 
I took a look.
I logged in with cedar-admin, I went to Nancy Lorimer's Home folder.
I can see a "Sound recording" template, but no metadata created from this.
The template itself is not shared with anybody.

I am not sure how this happened, but unfortunately I can not reproduce it now.

**Comment by graybeal** [comment]
you try it on staging maybe?

**Comment by graybeal** [comment]
I found the referenced artifacts on staging, but couldn't duplicate the behavior either. The instance is called "Sound recording instance metadata" (that's as confusing as 'template-instance' in our APIs!).  But everything was visible in the Shared With Me view. 

So, good, call it fixed.
