### ISSUE TITLE
Create sub-domains for staging server

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#40]
Need standard subdomains from staging.metadatacenter.net.

As per: 

https://github.com/metadatacenter/cedar-docs/wiki/Configure-host-names-on-RHEL-6.6

**Comment by martinjoconnor** [comment]
Reopening because does not seem to be set up properly for HTTPS.

**Comment by alexskr** [comment]
updated SSL cert to include missing sub-domains for staging env
