### ISSUE TITLE
Browse flat ontologies in tree view

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#407]
Some BioPortal ontologies are "too big to view" as a tree. But with some optimizations this should be possible (for example only show matches for a regex, or do paging), and it would be useful.

**Comment by martinjoconnor** [comment]
@marcos, any ideas on this? Putting in 1.6 so we look at soon.

**Comment by marcosmro** [comment]
For those "big" ontologies, the BioPortal endpoint that returns the root classes of a particular ontology returns an empty array. For example, this call should return the root classes of NDDF: http://data.bioontology.org/ontologies/NDDF/classes/roots. However, it returns "[ ]". I cannot think of any reasonable way of building the tree from CEDAR without that information.

A possible solution, as suggested by @graybeal, would be to add pagination to the BioPortal "roots" endpoint. Then, both BioPortal and CEDAR would be able to build an ontology tree with a "load more" option at the bottom to load the next page.

**Comment by mdorf** [comment]
I can create a separate endpoint in BioPortal (to keep the backwards compatibility of the existing endpoint). This is preferred over modifying the existing endpoint because a paginated result has a different structure from the non-paginated one. This endpoint would work on ALL ontologies and return their roots in a paginated form. And example of such an endpoint would be:

http://data.bioontology.org/ontologies/NDDF/classes/roots_paginated?page=1&pagesize=100

Development Time Estimate: 5 days.

**Comment by graybeal** [comment]
I like that idea, Misha. Here's another one that might be extremely useful in other contexts too.

I assume the reason we do pagination is because it lets us manage the computation and communication load—if we only have to do 100 at a time, say, then we can be sure the computer won't get bogged down for a long time, or try to return a message that is too big for the communication channel. (Right?) One problem with this is that we are introducing overhead, both in the communication channel and in the software development effort for the user, to handle the pagination.

Is this a good time to consider creating an asynchronous notification-based system, that would allow very large requests or messages to be computed off-line, possibly at lower priority, and 'returned' to the caller by sending a notification with the channel where the complete can be found? There are various design patterns for this, but it would be nice to at least think about what this would look like.  I think it could reduce the load on the system tremendously. (And destroy our API metrics, probably. But hey, no progress without sacrifice!)

Unless you say this idea is easy to implement, though, we can just file the idea for now.

**Comment by mdorf** [comment]
There's definitely a place for a system like that in BioPortal, but it doesn't seem trivial to implement. In this specific case, the user (CEDAR) would want an immediate feedback (the roots structure). I think a paginated call would do best in this case.

**Comment by graybeal** [comment]
Ah, right, wasn't thinking about the need for speed.

**Comment by marcosmro** [comment]
We will assume that in FLAT ontologies all terms are at the root level

**Comment by marcosmro** [comment]
Planned for 1.6.

**Comment by mdorf** [comment]
Implemented, deployed to staging:
http://stagedata.bioontology.org/ontologies/NCIT/classes/roots_paged?page=1&pagesize=100
http://stagedata.bioontology.org/ontologies/NDDF/classes/roots_paged?page=1&pagesize=100

**Comment by marcosmro** [comment]
I reopened this issue to do some final testing on CEDAR.

**Comment by mdorf** [comment]
@marcosmro Have you completed your testing? I'll coordinate with Jennifer.

**Comment by marcosmro** [comment]
@mdorf Yes, I've tested it for some 'flat' ontologies (e.g., NDDF) and it works fine. I will wait until it is released to production to start integrating it into CEDAR

**Comment by mdorf** [comment]
Deployed to production:
http://data.bioontology.org/ontologies/NCIT/classes/roots_paged?page=1&pagesize=100
http://data.bioontology.org/ontologies/NDDF/classes/roots_paged?page=1&pagesize=100
