### ISSUE TITLE
Sort terms in ontology tree

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#409]
BIBFRAME ontology tree (at least) is not sorted, so finding things is a bit random. Can we sort each level of terms before putting it up?

**Comment by martinjoconnor** [comment]
@marcosmro , does this require BioPortal work? Putting in 1.6 so we will look at soon.

**Comment by marcosmro** [comment]
It could be addressed by CEDAR's Terminology Server, but ideally it should be fixed at the source (BioPortal backend). As far as I know, the BioPortal backend returns results that are not sorted and they are sorted by the BioPortal frontend. 

Fixing this on the BioPortal backend would benefit BioPortal's frontend, CEDAR, and any other systems relying on the BioPortal API.

**Comment by marcosmro** [comment]
Investigate how the BioPortal UI is sorting the tree

**Comment by marcosmro** [comment]
Planned for 1.6.

**Comment by mdorf** [comment]
I've added sorting to BioPortal "/roots" and "/tree" and endpoints. Unfortunately, a limitation within 4store prevents the roots sorting when pagination is used. In this case, the sorting must be done inside 4store itself on the entire set before returning a specific sorted paged result. I've tested this functionality extensively, and it simply does not work predictably for ALL ontologies.

**Comment by marcosmro** [comment]
Thanks, @mdorf, for addressing this issue and for clarifying that limitation. We might need to solve  that limitation in the future, but for the moment I think that being able to sort results in non-paginated outputs is enough. When do you plan to release this feature to production?
