### ISSUE TITLE
UX comments from Debbie Voloshin, clinical trials manager at NG

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#416]
Usability Issues

Each field has a check, an OK button, and ctrl-enter instructions. All of these options seem redundant and a bit confusing and don’t move you to the next field so they don’t seem like they do anything. The only way to move from field to field is by positioning the cursor. It would be easier to enter data if the Tab key worked to take you to the next field. Currently the key takes you to the very beginning no matter where you are.

Once a section is completed and you move to the next section, clicking OK takes you to the very beginning – the first field of the first section.

Entering data into a template with multiple sections (EX: ImmPort basic_study_design) doesn’t flow very well and can be confusing. After entering the first section and saving, the first section stays open. After you select the next section and click, it expands but it is not in the entry format, when you click on a field a box is displayed and when you click to begin data entry the display then changes to the proper display. It is confusing. When you enter data into subsequent sections, if I click OK at any field, it repositions the cursor at the very first field of the first section.

After saving the way to get to actually enter a template with multiple sections is very confusing.

After Saving, the Save message displays and then goes away but it is confusing as to what to do next as the template remains the same. It should go back or do something.

No checking for required fields or indication of what is required.

Bugs

ImmPort bioSamples: Tried to validate a biosample and got an error. It saved though.

Once a section is completed and you move to the next section, clicking OK takes you to the very beginning – the first field of the first section.

When opening a subsequent section of a multi section template the display is not correct. It is a list of the fields. When you click to enter data a box is displayed and then the display changes to the correct format. This display issue happens sometimes when a new template is opened to populate. (I can’t see any pattern or action that causes the randomness)

There is no logical validation of the data…I was able to enter an end before the start date of

Clicking OK on the first field entry of a template sometimes causes it to go to a different display with a list of the fields. Sometimes it does nothing.

**Comment by willrett** [comment]
1. examine ImmPort basic_study_design_edit template shared with me on production and validate it to make sure it is ok.  ask Josef to validate it.
2.  if an element has required fields, does this show in the template editor?
3. IE maybe doesn't show pagers for multiple instance elements.  test in IE?
4. opening one field in edit mode, opens all of them.

**Comment by graybeal** [comment]
why was this closed? curious particularly because of the OK button issue
