### ISSUE TITLE
call LINCS validation url

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#427]
http://dev3.ccs.miami.edu:8080/dcic/api/dataset-validation

**Comment by willrett** [comment]
Amar:  We would like it to be used on "DSGC Dataset Template 1.0"  here is the URL <https://cedar.metadatacenter.net/templates/edit/https://repo.metadatacenter.net/templates/e32f6c30-c201-4473-87dd-a6a455ee837f?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F66089809-f66e-4031-ac6e-c31213205125>

**Comment by willrett** [comment]
https://submission.metadatacenter.orgx/command/validate-lincs

**Comment by willrett** [comment]
The submission service needs to add /command/validate-lincs  which calls http://dev3.ccs.miami.edu:8080/dcic/api/dataset-validation and returns the JSON response.

**Comment by johardi** [comment]
Closed by https://github.com/metadatacenter/cedar-submission-server/commit/38735cb9eefd01cdbf1249681cb4d60d04bb0afe
