### ISSUE TITLE
Stay in Shared with me mode option

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#429]
in the workspace when you choose "Shared with Me" and then pick something to edit or populate, and then return to the workspace, CEDAR defaults back to "Workspace" instead of what I was expecting which was to go back to "Shared with Me" since that's where I started from

**Comment by michelleif** [comment]
this just tripped me up again. "back" should mean "back to where I just was"

**Comment by willrett** [comment]
fixed
