### ISSUE TITLE
Element instance index should be count

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#430]
User comment:  "...when you are looking at a filled in template that has multiple instances of an element filled out, there is a number in parens next to the name of the element, but it says (1), referring to the first instance, but this makes it look like there is only one instance of that element filled out. I had a filled out template with two instances of an element so I expected that number to say (2), like it was telling me that there are 2 instances hiding here."

**Comment by martinjoconnor** [comment]
@willrett, is this still a thing? I'll label with 1.6 milestone so that we look at in near future.

**Comment by willrett** [comment]
It now says the index and total count, e.g.  (1 of 4)
