### ISSUE TITLE
The OK button is too prominent.

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#433]

**Comment by martinjoconnor** [comment]
@willrett , which ok button?

**Comment by willrett** [comment]
This was a comment I received.  I am closing this without any changes.

**Comment by graybeal** [comment]
If I am not mistaken, it was about the OK button that is underneath the field entry in the metadata editor (for accepting an entry and moving to the next field). 

This also was mentioned in the beginning of https://github.com/metadatacenter/cedar-project/issues/416 (a catalog of issues from the NG tester). 

Ideas for how to fix this, and the surrounding UI elements, are rather thoroughly discussed in https://github.com/metadatacenter/cedar-project/issues/402. So, IMHO not a big deal if this one is closed.
