### ISSUE TITLE
RDF list much shorter than attribute list

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#447]
For resource https://cedar.metadatacenter.net/instances/edit/https://repo.metadatacenter.net/template-instances/c3aef684-1a05-492b-b932-2e41641554e4?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F96ed5738-b694-4c53-9e73-bd2b7eb18b5b&search=62, there are a lot of attributes but only 7 RDF statements shown.

It's possible there may be things wrong with this template/instance pair, but then I'd expect some kind of error to appear.

**Comment by graybeal** [comment]
<img width="802" alt="screen shot 2017-05-06 at 5 56 07 pm" src="https://cloud.githubusercontent.com/assets/1266896/25777042/80c02896-3285-11e7-80d5-5a5387820bb4.png">

**Comment by johardi** [comment]
@willrett So it seems the script only generates CEDAR properties (i.e., provenance and basic info) but not the user-specified fields

**Comment by martinjoconnor** [comment]
Related to https://github.com/metadatacenter/cedar-template-editor/issues/687
