### ISSUE TITLE
Means to get to template from instance

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#448]
Given an instance, there is no way to find its template (or more to the point, look at the template JSON).  Used to be trivial with the template viewer button, but now I have to look at the JSON or RDF of the instance, find the template ID, and figure out how to enter it into CEDAR so I can see it, but sometimes that won't work either. None of this is straightforward for a user that just wants to look up the template.

Note: When I tried it with https://repo.metadatacenter.net/templates/4373d376-c567-40c9-8349-dfa152908aac, I got the following error, which could mean my key had to be included, my key was wrong, my key didn't have sufficient authentication privileges, or I don't know what. Can we actually tell the poor user what has to be fixed for that, in nicely formatted English (not JSON)?  

In this case, I'm not sure why I should need to provideAuthorizationHeader, if that's the answer to the above. I'm logged in to CEDAR, so it already has my authentication information. (I'm not really asking to understand the reason, I'm asking because that's what everyone will ask when they're trying to access some CEDAR entity.)

{"status":"FORBIDDEN","errorType":"authorization","errorKey":"authorizationTypeNotFound","errorReasonKey":null,"message":"Authorization not found.","parameters":{},"suggestedAction":"provideAuthorizationHeader","originalException":null,"sourceException":null,"operation":null}

If there is an access error

**Comment by martinjoconnor** [comment]
Agree that we should include template tab (again) too. 

We will look into the authorization stuff.

**Comment by martinjoconnor** [comment]
Will be addressed by https://github.com/metadatacenter/cedar-template-editor/issues/720
