### ISSUE TITLE
AIRR template generates error

### ISSUE THREAD

**Issue by ahmadchan** [metadatacenter/cedar-project#455]
CEDAR-AIRR instance generates error when we try to validate/save. Click on the link below and try to validate or save. It was working fine two weeks ago. 

https://cedar.staging.metadatacenter.net/instances/edit/https://repo.staging.metadatacenter.net/template-instances/d479c69c-5abe-4e0f-827e-34437b4140c0?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2Ff77e5f5e-0bce-4e52-8415-a684614b9461

**Comment by johardi** [comment]
I got this message "Unable to process JSON". Need to check with @willrett 
```
Status: 400, Bad Request
URL: https://submission.staging.metadatacenter.net/command/validate-biosample
Method: POST
Message: Unable to process JSON
```
