### ISSUE TITLE
CEDAR-AIRR: Duplicate repeatable elements with values

### ISSUE THREAD

**Issue by ahmadchan** [metadatacenter/cedar-project#456]
We are looking for a functionality to add the feature to clone multiple biosample rows with values from the initial row in the CEDAR-AIRR instance

**Comment by martinjoconnor** [comment]
Duplicate. See all AIRR-related tasks here:

https://waffle.io/metadatacenter/cedar-project?label=AIRR

**Comment by ahmadchan** [comment]
We can not replicate the whole biosample part with values. Please look at https://cedar.staging.metadatacenter.net/instances/edit/https://repo.staging.metadatacenter.net/template-instances/d479c69c-5abe-4e0f-827e-34437b4140c0?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2Ff77e5f5e-0bce-4e52-8415-a684614b9461
