### ISSUE TITLE
Date field for AIRR NCBI validation

### ISSUE THREAD

**Issue by ahmadchan** [metadatacenter/cedar-project#457]
NCBI databases do not accept full timestamp. We should modify date field according to NCBI.

**Comment by martinjoconnor** [comment]
You can make this modification here:

https://github.com/metadatacenter/cedar-submission-server/blob/develop/cedar-submission-server-core/src/main/java/org/metadatacenter/submission/AIRRTemplate2SRAConverter.java

As in, this does not require modification to the template editor but the translator code (though we will have a date field).

Feel free to create a new branch with the modification and generate a pull request with the fix.

**Comment by johardi** [comment]
What is the correct format for NCBI?

**Comment by martinjoconnor** [comment]
Not seeing any validation issues at the moment. Moving to 1.5 for later investigation.

**Comment by martinjoconnor** [comment]
Addressed by fixed date generation:

https://github.com/metadatacenter/cedar-project/issues/566
