### ISSUE TITLE
FTP Submission

### ISSUE THREAD

**Issue by ahmadchan** [metadatacenter/cedar-project#458]
In the current CEDAR-AIRR instance, username and passwords are hard coded. We want extend the existing FTP submission with the user account (using a pop-up form for entering name/password). Users should be responsible for their submission and follow up queries, not CEDAR.

**Comment by martinjoconnor** [comment]
Duplicate. See all AIRR-related tasks here:

https://waffle.io/metadatacenter/cedar-project?label=AIRR
