### ISSUE TITLE
Document Let's Encrypt Installation

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#46]
No current documentation for Let's Encrypt on CEDAR Red Hat servers. 

Documentation should explain generation of PEM files (e.g., /etc/letsencrypt/live/auth.staging.metadatacenter.net/privkey.pem;) and explain how these files are related to the host name. On the two current CEDAR servers (staging.metadatacenter.net and metadatacenter.net) the files are called:

staging.metadatacenter.net
auth.metadatacenter.net

which does not seem to be consistent.

Server documentation here:

https://github.com/metadatacenter/cedar-docs/wiki/CEDAR-Server-Install-Guide

**Comment by martinjoconnor** [comment]
Placeholder here: https://github.com/metadatacenter/cedar-docs/wiki/Installing-Let's-Encrypt-on-RHEL-6.6

**Comment by martinjoconnor** [comment]
Any progress on this task?

**Comment by marcosmro** [comment]
I have updated the placeholder with a link to the instructions on how to use Nginx with Let's Encrypt: 
https://certbot.eff.org/#centosrhel6-nginx
