### ISSUE TITLE
Add property popup for elements

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#463]
Add a property to an element in a template.  There is no caret present for the property popup to display and delete the property, as there is for properties added to fields.

**Comment by michelleif** [comment]
see also #431, #549, and #550 before deciding to make this work for elements the same way it works for fields

**Comment by martinjoconnor** [comment]
Perhaps coordinate with Debra to give her feedback on how you would like this to work.

**Comment by willrett** [comment]
fixed
