### ISSUE TITLE
Final docker configuration

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-project#465]
resource server, worker server: certificate check

keycloak event listener not working?

get rid of export CEDAR_KEYCLOAK_CLIENT_ID="cedar-angular-app"
replace in cedar-config and in standalone.xml

try to get rid of:

export CEDAR_RESOURCE_SERVER_USER_CALLBACK_URL="https://resource.${CEDAR_HOST}/command/auth-user-callback"
export CEDAR_RESOURCE_SERVER_ADMIN_CALLBACK_URL="https://resource.${CEDAR_HOST}/command/auth-admin-callback"

and have it written - hardcoded in the standalone.xml

delet from the cedar-config as well.

doublecheck that 

docker network create --subnet=${CEDAR_NET_GATEWAY}/24 --gateway ${CEDAR_NET_GATEWAY} cedarnet

the subnet ending 1 is ok instead of 0

keycloak realm : admin user:
try to replce these two values with just "value" and plain text password, for now taken from the environment variable: CEDAR_ADMIN_USER_PASSWORD

      "hashedSaltedValue" : "QkpIXKXs23Z3MBkNmxthSLvPS0MEhAFd6vmEexpvnA0ls8S5mKuaoDTxBoNMz0pkYlIXo9QJcmlVB+3UxyNb5g==",
      "salt" : "GW1T3HCPbESkDe79obh+FQ==",

try to get rid of the env var:

export CEDAR_ADMIN_USER_API_KEY="0000111122223333444455556666777788889999aaaabbbbccccddddeeeeffff"

this would mean:
	cedar-admin should get a random password as anybody elsse
	cedaradmintool should use cedar-admin/s password to get a Bearer token.
	keycloak event listener should do the same

MYSQL / add a timeout to the beginning.
	install mysql clint and then using that query the avauilabiliuty of the database;

	apt-get install mysql-client

I added a check to keycloak 
                  <ds:check-valid-connection-sql>SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'keycloak'</ds:check-valid-connection-sql>

doublecheck that it works

Hardcode:
export CEDAR_MONGO_APP_DATABASE_NAME="cedar"

remove export CEDAR_NEO4J_USER_NAME="neo4j"
hardcode it

rename the password:

export CEDAR_NEO4J_USER_PASSWORD="changeme"

BOLT transition after the release

rename the PORT variables:

export CEDAR_PORT_FOLDER=9008
export CEDAR_PORT_GROUP=9009

have PORT at the end

Test related ENV vars should go away.
We should read them from a REST endpoint at the beginning of the test execution, if they are really variables. And needed.

get rid of:

export CEDAR_EVERYBODY_GROUP_NAME="Everybody" 

hardcode in the test

Clean up the MicroService ports:

Docker file shoul set the ENV var
should expose the ports 3x

set-env should enumerate all 3 x 11 ports:

-p ${CEDAR_TEMPLATE_HTTP_PORT}:9001 \
-p ${CEDAR_TEMPLATE_MANAGEMENT_PORT}:9101 \
-p ${CEDAR_TEMPLATE_STOP_PORT}:9201 \

we should not pass in the port to the run

get rid of :
export CEDAR_LD_USER_BASE="https://metadatacenter.org/users/"

hardcode it. Really. It should be the same for all CEDAR system

GET rid of :CEDAR_DOCKER_HOST

introduce new ones for folder, user, group, tenplate.

When we go from one server to the other (resource -> template)

		worker -> folder

we should not exit the docker container, we do not want to have the fixed IP.

**Comment by martinjoconnor** [comment]
Additional testing in #464.
