### ISSUE TITLE
debounce is hard to use..revisit this

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#473]

**Comment by martinjoconnor** [comment]
Likely related to this. When the - icon is selected to collapse an element in the Template Editor the element title entry field appears.

<img width="971" alt="screen shot 2017-06-12 at 1 01 19 pm" src="https://user-images.githubusercontent.com/1731323/27052724-7b40a07e-4f6f-11e7-81f7-e757f874779e.png">
