### ISSUE TITLE
DATS metadata workflow (for MDC)

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#477]
Per email from John Lavender, pursue work to achieve something like the following:
1. Have the student grab the BioCADDIE template from the CEDAR repository and copy it to their workspace
2.  Populate the template for each dataset for which they have metadata
3.  When they are done, use the REST web service to download and consume all the metadata entered by the student.
4.  Upload the metadata to the MDC. (Note: This may or may not be exactly parallel to uploading it to BioCADDIE, so some tweaking of the task may be needed to address both.)

**Comment by JohnLevander** [comment]
Regarding #4...

I planned to write a script that connects to the CEDAR web service to download the metadata that the students entered.  I would then populate my application with that data.  I feel like that would work at least in the short term.  Does that make sense?

A feature request that you might consider to solve #4 would be to allow a user to provide a URL in their profile for a "webhook" (or webhooks even) that would be called when they indicate that they are done populating a template (perhaps by pressing a "publish" button).  This would enable a CEDAR user to upload metadata automatically to any service that takes advantage of the webhooks.

**Comment by graybeal** [comment]
Yes, that makes sense. 

Your suggestion is a good one. When Martin has a moment, I'm sure he will consider how the existing implementation(s), which I suspect are similar, might be suitably adapted.

**Comment by martinjoconnor** [comment]
We have the following two tasks that will support a minimal version of this functionality:

https://github.com/metadatacenter/cedar-project/issues/353
https://github.com/metadatacenter/cedar-project/issues/354

They are tentatively scheduled for the 1.4 release (due late July).

**Comment by martinjoconnor** [comment]
Essentially being carried out for CCP work.
