### ISSUE TITLE
Can't rename instance: validation error

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#486]
I have an instance from some long time ago titled "62 : Patient Gender Category" (https://cedar.metadatacenter.net/instances/edit/https://repo.metadatacenter.net/template-instances/73dd50bf-1366-49fc-8afd-5bdd99b061d8?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F835b8468-d486-405c-92df-e82197e68b4b).

I can modify the instance and save it without error. But when I try to rename it, I get the error below.

This inspires many questions:
1) Shouldn't the same test (or non-test, either) be done on Save as is done on Rename?
2) What is the general plan to assure existing content gets upgraded when changes are made to the model? OR How is it that this content lost its critical metadata? 
3) Is there a way to search and flag all the content that is non-validating? (and see 4)
4) Can we support a user-friendlier way to update content to be valid?
5) How do I fix this for my content?
6) Should we try to fix this for all the CDE content?
7) If this is the reason the RDF isn't updating correctly, should the RDF update script replace any existing RDF with a "Can't validate" message? (I think that may overlap with another task....)

Technical details of error

Status: 400, Bad Request
URL: https://resource.metadatacenter.net/template-instances/https%3A%2F%2Frepo.metadatacenter.net%2Ftemplate-instances%2F73dd50bf-1366-49fc-8afd-5bdd99b061d8
Method: PUT

Message: Template instance has a missing property ('schema:isBasedOn')
Error key: invalidInput
Exception:

**Comment by martinjoconnor** [comment]
Looks to be very similar to recent mailing list bug: https://github.com/metadatacenter/cedar-model-validation-library/issues/38

Artifact update script should help tackle: 

https://github.com/metadatacenter/cedar-model-validation-library/issues/22
