### ISSUE TITLE
Search box erasure requires return

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#487]
If I erase the desktop search box but don't hit return, nothing recognizes that the search box is now empty. So the UI visible content and the system behavior are now out of sync, without any way for user to recognize there is still an active search term. 

(This is analogous to how the title URLs in browsers sometimes work (or don't), but that doesn't cause a persisting state change in the system behavior.)

Presumably changes to search box should be auto-entered after a period of non-typing, like 5 seconds.

**Comment by willrett** [comment]
There is an X delete icon to clear the search field and refresh the workspace.  Deleting the search text box with a delete key or backspace  to remove the text does not and should not submit the form and do a new search.

**Comment by graybeal** [comment]
Begging to differ, and seeking to understand how you are saying the system is supposed to work:  

Should deleting the content and hitting return generate a new search? I think yes, because: (a) There is no way to tell that the X delete icon refreshes the workspace, but that deleting the content and hitting return does not delete the workspace; (b) In every other search application I have used in the past 10 years, deleting the content and hitting return will do a new search; and (c) presumably if you backed up one character and hit return, it would redo the search in every case *except* if there was only one character, in which case backing up would, oddly, not work any more.

It is also true that in many dynamic applications, backing up over entered content will redo the search with the remaining content, even without hitting return. But this is not universal, so I don't think we have to support it.
 
Unless there is a particular reason we want to be different from the de facto standard, I think we should support backing up over the content and hitting enter to redo the search.

**Comment by willrett** [comment]
Entering the return key submits the form and  performs a new search.

**Comment by graybeal** [comment]
Yay! Life is good. Thanks.
