### ISSUE TITLE
Search not working if sort by lastUpdated

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#498]
When I enter a search term like 'miaca', I get back a 400 error:

Error

The server is not responding to the request: https://resource.metadatacenter.net/search?limit=100&offset=0&q=miaca&resource_types=element,instance,template,folder&sort=-lastUpdatedOnTS

I've tried deleting all browsing data, using a guest account in Chrome, and searching on other browsers. All produce the same results.

**Comment by graybeal** [comment]
Ah. Problem is the sort key. If sort by Name or by Creation Time is selected, it works.  If sort by Update Time is selected, it fails. Will rename accordingly.

**Comment by egyedia** [comment]
The problem manifested itself only on production.
The cause was that the groovy scripting was not enabled.
