### ISSUE TITLE
Backup MongoDB and Neo4J on CEDAR machines

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#50]
As discussed, hourly backup for 2 weeks on current CEDAR machines (dev1 and dev2).

**Comment by gjmf** [comment]
We're also tracking this here:  https://jira.bmir.stanford.edu/browse/BMIRIT-298

**Comment by martinjoconnor** [comment]
I do not seem to have access when I log in. My JIRA id is sunid.

**Comment by martinjoconnor** [comment]
What is the status of the Neo4j backups?

**Comment by martinjoconnor** [comment]
Also, note JIRA login issue above.

**Comment by gjmf** [comment]
Hi, folks,

Sorry for the delay in responding.  I wasn't receiving notifications from Github.  I've found and fixed the notifications issue.

The backups have been running hourly for approximately two weeks now, with a 2% failure rate.  (For every 49 successful hourly backups, only 1 fails.)   However, restores are failing, and I have been working with the backup vendor (Druva) to identify and resolve the issue, which is decisively on their end.  They released a new version of their software today which may have resolved the issue.I'll update again later today.

**Comment by graybeal** [comment]
This is further along, I think restores are working. Will have Graham update.

**Comment by gjmf** [comment]
Hourly backups to Druva are continuing to succeed, and restores are once again working as well.  The data for restore task in question is attached to cedr-dev-app-01 in a secondary additional disk volume, in /dev/sdb.  Currently I'm reconfiguring the logical volumes for mounting and data copy.

**Comment by martinjoconnor** [comment]
Great. Just to confirm - this is for Neo4j as well as Mongo?

**Comment by martinjoconnor** [comment]
What is the status of the Neo4j backups?

**Comment by graybeal** [comment]
We have hourly backups (for the past week) of the 2 virtual machines. Any of these can be restored and then used to see/grab the system status (for any components as desired, presumably) at that time.


We have successfully restored a VM, and Graham is supposed to contact you any time now, as soon as he has a certificate that will allowed keycloak to work on the restored VM.


Please let me know if that does not seem sufficient for the short term (until Atti's export/import is fully working, at which point we may redesign the process a bit), and let Graham and me know if you have an urgent need.

________________________________

**Comment by cedaradmin** [comment]
Great. The VM solution, as discussed, should be nice.

**Comment by martinjoconnor** [comment]
Now awaiting completion of task #76.

**Comment by graybeal** [comment]
Reference BMIR tracking issue https://jira.bmir.stanford.edu/browse/BMIRIT-298

**Comment by martinjoconnor** [comment]
Can't verify that backup approach works yet. Certificates fine but there are a few mysterious places containing the host name that make some servers unhappy when moved to a new host.  Have contacted Atti to clarify these  so cannot verify a resurrection until then.

**Comment by martinjoconnor** [comment]
Have verified that we can now resurrect a clone. Approach suggested by Alex works very well. See: https://github.com/metadatacenter/cedar-conf/wiki/Resurrecting-CEDAR-on-a-cloned-VM
