### ISSUE TITLE
Editing element 'meta-settings' is flaky

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#510]
The UI model for elements in a higher-level element is intermittent and confusing. 

Create a template that includes two elements. Add a third element. At the bottom of the third element you will see MULTIPLE as an option, but neither of the other two have it.

On good days, you can click in the header (but nowhere else) of one of the already entered elements, and it will go into "edit mode", and allow you to rename it and enter multiples. (Martin and I both saw this.) Most of the time, if you click anywhere else, the containing element intercepts the click (I guess) and forces you to enter the top property name.

And sometimes the MULTIPLE is within the lower-level element, and sometimes within the upper-level element. And sometimes the newly included element is displayed as distinct from the existing collection of elements (see screenshot), and sometimes it is not, but is embedded in the existing set.

The desired behavior is that clicking anywhere on any low-level element lets you edit as many of the settings as is reasonable for that element. If the user wants to edit the setting of an outer element, they need to click in that region.

**Comment by graybeal** [comment]
<img width="912" alt="screen shot 2017-07-11 at 4 27 50 pm" src="https://user-images.githubusercontent.com/1266896/28095248-3822c36e-6656-11e7-931b-deb6168c390f.png">

**Comment by willrett** [comment]
I don't see a problem.  You are editing the first level elements, not nested fields or elements.  The tabbed options appear at the bottom of the element or field being edited.

It is inaccurate to say that it works only on a good day.  Computers are not affected by the weather.

**Comment by willrett** [comment]
If you save the file first, it will work fine.  If the file is unsaved, clicking a nested element will select the parent element instead.

**Comment by graybeal** [comment]
Michelle reported what I think is the same problem (as the first 2 paragraphs) 8/1/2017:

3) I seem to have to click multiple times on an existing field in order to “select” it for editing (this is in template creation mode)

**Comment by michelleif** [comment]
I don't think this is the same as what I reported in Aug 2017 but I can no longer reproduce whatever it was I was reporting.

**Comment by graybeal** [comment]
Point taken. I showed Debra what I was seeing, which is that in a field, clicking on the field name or description box *looks* illegal (big circle-slash), but in fact it opens up the fields. Whereas clicking on the field names in the element looks just as illegal, and in fact doesn't do anything. Since elements and fields look pretty similar, it's hard to know why one works and the other doesn't.

The reported MULTIPLE issue may have mostly been a function of which field or element was open (in which case MULTIPLE is visible). So I think we should ignore that until we get a clearer case.

I was unable to reproduce the confusion about the wrong elements opening up (higher- vs lower-level). So we'll call that "can't reproduce" as well.

**Comment by willrett** [comment]
I believe that I fixed this.   Create a new issue if you find something new.
