### ISSUE TITLE
Spreadsheets controlled term dropdown broken

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#511]
Spreadsheet view does not show the dropdown term options when a CV is available.  The dropdown arrow appears, but clicking on it produces a large blank box (which turns red after another box is clicked, and which can't be deleted). 

Reference for example: https://cedar.metadatacenter.net/instances/edit/https://repo.metadatacenter.net/template-instances/fdba382b-7cc8-4e25-9512-da04fc33b6ed?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2Fdb242545-e2e6-420b-a805-70725aaeaeff

**Comment by willrett** [comment]
the dropdown gets clipped to the size of the spreadsheet.  the code needs to change so the dropdown element is outside the spreadsheet element so it does not get clipped.
