### ISSUE TITLE
Spreadsheet empty row deletion fails

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#512]
If there's an empty spreadsheet row, clicking on the trash from within it does not delete the row visually. Switching to other views shows that for each click of the trash can, one of the earlier rows is deleted.

**Comment by martinjoconnor** [comment]
Trim empty rows at end when exit spreadsheet view.

Show empty row(s) in spreadsheet view.

**Comment by graybeal** [comment]
Not sure if Martin's comment is the proposed solution, or additional requirements. 

To be clear, it is required to delete any row in the spreadsheet view that has been deleted from the model, because otherwise all sorts of bad UX happens. (The user deletes multiple rows thinking they missed the button, the user mislocated their cursor on the desired row to delete, etc.)
