### ISSUE TITLE
Spreadsheet feature won't work on elements

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#514]
For any spreadsheet with nested elements, only the lowest-level elements can be viewed in spreadsheet mode. Even if all the elements in a higher-level element contain simple lists of fields, it appears the fields of the lower-level elements will not show up in spreadsheet view in the metadata editor. 

Elements should be flattened to produce spreadsheet views that work (as long as no multiples are included).

**Comment by graybeal** [comment]
See also template-creator/69

**Comment by willrett** [comment]
only multi-instance fields and elements are currently being edited as spreadsheets.  In addition, the element must not contain multi-instance field types (list, checkboxes...) or elements.

**Comment by martinjoconnor** [comment]
Now being addressed by https://github.com/metadatacenter/cedar-project/issues/534
