### ISSUE TITLE
Multi-element editing loses data

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#515]
(See movie at https://stanfordmedicine.box.com/s/4tpc6mp1992d3trae38jcqielwxu4i4r.) 
 
If have a MULTIPLE element that contains several different element, and I edit the multiple element in vertical mode to add a value in both first and second element instances (movie starts here); then I click on toggle view twice (to get past spreadsheet view, ignoring the fact it doesn't work because that's in #514) and on to the horizontal view); then I click on the arrow to go to the second element instance, my value is no longer there.

Clicking toggle view again to return to vertical mode, and re-opening the containing elements, I can confirm that the element is no longer shown.

**Comment by willrett** [comment]
I believe that I fixed this.   Create a new issue if you find something new.
