### ISSUE TITLE
Internal spreadsheet formatting issues

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#517]
A number of formatting issues in the spreadsheet library:
* display of line breaks not consistent/correct (breaks after first hyphen, sometimes breaks lines and sometimes doesn't)
* right-hand column won't display whole cell, or won't keep content within cell
* resizing of columns inconsistently saved
* no control of cell wrapping (should have same options as Google spreadsheet, ideally)
* no control of decimal places shown (entering integer number is displayed as floating point with 1 decimal place)

**Comment by graybeal** [comment]
![screen shot 2017-07-13 at 3 36 23 pm](https://user-images.githubusercontent.com/1266896/28191047-f1aaa3dc-67e2-11e7-985b-754ed4ce9c2a.png)

**Comment by willrett** [comment]
I addressed items 2 and 5 above.  The rest should be moved to a later release.
