### ISSUE TITLE
Need stats for proposal & site visit

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#519]
Here are CEDAR statistics I'd like to have next week, and each week up to the site visit (to use in proposal and site visit presentation, if they are positive):
 * # users
 * # templates
 * # instances
 * # sessions (Google analytics?)

**Comment by martinjoconnor** [comment]
We don't have functionality to calculate these numbers (Misha's reporting task should address that) buy can work out some numbers.

If we sort the All/Users folder by creation date we can see registrations:

https://cedar.metadatacenter.net/dashboard?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F20f6f4f9-2210-4c0a-afe7-8496f3948ad6

We appear to have 5-6 registrations per week.

Josef just posted artifact numbers from his model update script:

#Template: 187,
#Element: 151,
#Instance: 87

I can look at doing some find/grep magic on our Nginx logs to see if I can find session information (unless someone has a better idea).
