### ISSUE TITLE
import_mode=true returns error 500

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#525]
It happened when making a POST to the following URL: https://resource.metadatacenter.net/templates?import_mode=true

The POST body is available at https://docs.google.com/document/d/1-zPTFCZnCx5R-AQq9_51CN8ZEuNdoko52RBjhVEKvAQ/edit?usp=sharing

**Comment by martinjoconnor** [comment]
Duplicate of https://github.com/metadatacenter/cedar-resource-server/issues/33
