### ISSUE TITLE
Implement 2d spreadsheets

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#534]
Both LINCS and AIRR do no use actual  hierarchical spreadsheets.  solve 2D nested element spreadsheet editing.  LINCS templates need to be updated to remove the extra 1..N designations.

**Comment by martinjoconnor** [comment]
See also description here: https://github.com/metadatacenter/cedar-project/issues/514

**Comment by martinjoconnor** [comment]
We will implement more restricted version of this first for multi-instance attribute/value fields. https://github.com/metadatacenter/cedar-template-editor/issues/702

**Comment by martinjoconnor** [comment]
Superseded by attribute/value field type: https://github.com/metadatacenter/cedar-project/issues/595
