### ISSUE TITLE
Database paper describing submission workflows

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#538]
When we have initial real submissions to LINCS and AIRR repositories write a paper describing submission workflows.

https://academic.oup.com/database

<img width="1224" alt="screen shot 2017-08-10 at 1 46 15 pm" src="https://user-images.githubusercontent.com/18013687/29191372-5af60d68-7dd2-11e7-9bc3-9a1c8250135d.png">
<img width="1236" alt="screen shot 2017-08-10 at 1 46 22 pm" src="https://user-images.githubusercontent.com/18013687/29191376-5d6236d0-7dd2-11e7-9feb-e7eeb05ac3aa.png">
<img width="1153" alt="screen shot 2017-08-10 at 1 46 29 pm" src="https://user-images.githubusercontent.com/18013687/29191381-5ebff382-7dd2-11e7-9ec9-04fd2b0d8401.png">

**Comment by martinjoconnor** [comment]
We should discuss this paper soon. Marcos has done some recent reviewing for this journal and suggests that a strong evaluation would not be required. The journal also has a decent impact factor.

**Comment by marcosmro** [comment]
Aims and Scope of the Database Journal: https://academic.oup.com/database/pages/About

**Comment by martinjoconnor** [comment]
Will now do SWAT4LS paper: #836

May extend to journal paper later.
