### ISSUE TITLE
Template/element/field  @context specification

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#541]
Current @context specification in a template, element, and field is as follows:

```
 "patternProperties": {
        "^(?!pav)(?!schema)(?!oslc)[a-zA-Z][a-zA-Z0-9]*$": {
          "type": "string",
          "format": "uri"
        }
      },
```
which is too restrictive. We should do the following:

```
 "patternProperties": { 
    "*": { "type": "string", "format": "uri" } 
  }
```

**Comment by martinjoconnor** [comment]
Related to allowing any characters for JSON field names ( https://github.com/metadatacenter/cedar-template-editor/issues/659)

**Comment by martinjoconnor** [comment]
Also related to https://github.com/metadatacenter/cedar-model-validation-library/issues/41

**Comment by johardi** [comment]
```
All Unicode characters may be placed within the quotation marks, except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).
```
Source: https://tools.ietf.org/html/rfc7159

**Comment by marcosmro** [comment]
After discussing this issue with Martin, we have decided to remove the "patternProperties" field. Users shouldn't be allowed to add property mappings that haven't been defined in the template.
