### ISSUE TITLE
Auto-generated property URI in @context is broken

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#542]
For example, if we have a field called ```field 1``` (with space) the generated JSON Schema in the template will be:

```
"field 1": {
          "enum": [
            "https://schema.staging.metadatacenter.net/properties/field 1"
          ]
        }
```

The URI here is not valid. We need to map the field name part which is used as the local name to either safe characters or a UID.

e.g.,

```
"field 1": {
          "enum": [
            "https://schema.staging.metadatacenter.net/properties/5454545"
          ]
        }
```

**Comment by martinjoconnor** [comment]
Related to allowing any characters for JSON field names ( https://github.com/metadatacenter/cedar-template-editor/issues/659)

**Comment by marcosmro** [comment]
I have fixed this issue by assigning UIDs to property local names. 

Example:
```
 "treatment": {
          "enum": [
            "https://schema.metadatacenter.orgx/properties/3d096f78-a5d6-4c4d-98d6-d8322277d412"
          ]
        }
```
