### ISSUE TITLE
Create Docker repos on Nexus

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#544]
Latest Nexus server supports Docker.

Requires metadatacenter/cedar-project#818

**Comment by martinjoconnor** [comment]
http://www.sonatype.org/nexus/2016/06/29/using-nexus-3-as-a-private-docker-registry/

**Comment by martinjoconnor** [comment]
Need ports open on Nexus server: https://github.com/metadatacenter/cedar-project/issues/577

**Comment by alexskr** [comment]
one way to deal with odd ports is to put another reverse proxy in front of the nexus server,  something like https://dockerhub1.bmir.stanford.edu to proxy http://nexus.bmir.stanford.edu:8082.  just a though

**Comment by martinjoconnor** [comment]
That makes sense. Let me verify that current approach works and we can discuss.

**Comment by martinjoconnor** [comment]
As per above, waiting on https://github.com/metadatacenter/cedar-project/issues/818

**Comment by martinjoconnor** [comment]
Example:


    docker build -t metadatacenter/cedar-nginx:1.8.10 .

    docker tag metadatacenter/cedar-nginx:1.8.10 cedar-dockerhub.bmir.stanford.edu/metadatacenter/cedar-nginx:1.8.10

     docker push cedar-dockerhub.bmir.stanford.edu/metadatacenter/cedar-nginx:1.8.10

    docker pull cedar-dockerhub.bmir.stanford.edu/metadatacenter/cedar-nginx:1.8.10

**Comment by martinjoconnor** [comment]
Some documentation: https://github.com/metadatacenter/cedar-conf/wiki/Configuring-Docker-to-use-the-CEDAR-Nexus-DockerHub
