### ISSUE TITLE
Error connecting to BioPortal when trying to select field value = Activity class from bibliotek-o

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#546]
When adding values to a field in my template, when I try to select the Class or Branch "Activity" in the bibliotek-o ontology, I get "error establishing connection to BioPortal". The error comes up as soon as I click the term in the list of choices. The same happens for a subclass of Activity (like Author). Other classes in bibliotek-o, like Electronic, and other classes in other ontologies work fine.

**Comment by michelleif** [comment]
![bioportalerror.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46ea9d95338d91bd8ee5ba51b652e2d665043761260ea62864c7b96aea1478575f5e4efd480a0d44a8fa8828a6b638718d545dbec3714d36976345f3e5db55ea43a82a994c84bcbd8f4cc2e13423e58a8a4839191755.png)

**Comment by marcosmro** [comment]
The “activity” class in the BIBLIOTEK-O ontology is returned by the BioPortal search endpoint, but its details are not available.

The following call returns “Activity” as one of the search results:

http://data.bioontology.org/search?q=activity&also_search_provisional=true&ontology_types=ONTOLOGY&suggest=true&ontologies=BIBLIOTEK-O&max_depth=0&include=prefLabel,definition&page=1&pagesize=500&display_context=false&display_links=true 

However, the “self” link returns 404:

http://data.bioontology.org/ontologies/BIBLIOTEK-O/classes/http%3A%2F%2Fbibliotek-o.org%2Fontology%2FActivity

The BioPortal team has been notified about this issue.

**Comment by marcosmro** [comment]
Message from the BioPortal team:
"This is now fixed. It looks like the ontology has not been indexed property. It had statuses: (Parsed, Metrics, Annotator, Error Indexed). I’ve re-indexed it, and the self link should now be working (just don’t click on the “self” link you provided because it has changed in the latest version of BIBLIOTEK-O)."
