### ISSUE TITLE
when entering seemingly valid URL into a link-type field, URL is not accepted

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#548]
My template has a link-type field. When populating template, I try to enter this URL in the field http://viaf.org/viaf/88958529 and CEDAR won't accept it. CEDAR doesn't seem to accept any URLs w subdomains

**Comment by martinjoconnor** [comment]
Will be addressed by https://github.com/metadatacenter/cedar-template-editor/issues/688, which is in the 1.5 milestone so should fixed soon.

**Comment by graybeal** [comment]
Actually I don't think this is a duplicate any more. It is fixed (and was a bug), but https://github.com/metadatacenter/cedar-template-editor/issues/688 is still open—looks like that is being repurposed as the long term 'improve IRI validation' task.
