### ISSUE TITLE
Property window X looks like close

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#549]
The latest description I saw reads: 
"After adding a property I want to be able to see that I added it when I am back in template editing. you can see the property if you click the dropdown triangle, but then I clicked X to close the dropdown, and my property disappeared but I didn’t realize it, so I lost all the property work I did."

The X looks totally like a window close button, but deletes the property with no query and no undo possible, and gives no feedback that it is deleting (has deleted) the property.

See also #431 and #550.

**Comment by graybeal** [comment]
Also (or maybe again)  from LD4P on 8/1: "once you’ve assigned a property to a field, and you click the down arrow to view what’s there, the “X” can be interpreted as “get rid of this value” or “close this little window” and if you interpret it as “close this little window” whoops you just deleted your hard-won property"

**Comment by michelleif** [comment]
I was helping a new CEDAR user today who was showing me a template she had created. "I swear I added a property and now it's gone!" She had clicked the x by mistake and didn't realized she had deleted her property. So another data point for the need to fix this.

**Comment by willrett** [comment]
I added a close X icon in the upper right of the popup.  It should be clear how to close the popup.  I also added a delete tooltip  on the circle-X.
