### ISSUE TITLE
cannot use Web Annotation Ontology in CEDAR

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#556]
Web Annotation Ontology is in BioPortal http://bioportal.bioontology.org/ontologies/OA/
but when I try to find classes or properties from it to use in a CEDAR template, none are found.

**Comment by marcosmro** [comment]
The 'metrics' for that ontology are currently unavailable in BioPortal (http://bioportal.bioontology.org/ontologies/OA/metrics). That's why CEDAR is ignoring it. I will notify the BioPortal team about this.

**Comment by graybeal** [comment]
Odd. The metrics are available at this endpoint for me: http://data.bioontology.org/ontologies/OA/metrics 

Note that when I click your link, it ends up at a different endpoint (with 404 error):
  http://bioportal.bioontology.org/ontologies/OA?p=classes&conceptid=metrics

I'm pretty sure the bioportal path is not the right metrics link.

**Comment by marcosmro** [comment]
That's right. My URL was wrong. I'll take a another look at this issue.

**Comment by marcosmro** [comment]
I refreshed the ontologies cache and now OA is available both in CEDAR staging and production. We plan to get rid of that cache to avoid this kind of issues (details here: https://github.com/metadatacenter/cedar-terminology-server/issues/28).
