### ISSUE TITLE
tooltip (description) doesn't go away

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#557]
while creating a template, clicked description (question mark icon) to see what was there. the tooltip shows up but there's no way to make it go away. when you scroll, the tooltip stays in one place. when you go back to another screen, the tooltip is still there. clicking on a second question mark icon brings up a second tooltip that doesn't go away. (attaching video)

**Comment by michelleif** [comment]
couldn't attach a video but here's a screenshot
![tooltip.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46fc9b952f968ab9cda5fd53b652fa912a5265296b51f52826d5b278be1b79035f0b4dad42585f40fdfe817df5a42062c80d55b98e30063e937f03a6aa8318b500bf208f4f87bfb8894fc5ee3e37aa.png)

**Comment by willrett** [comment]
Disabled popover
