### ISSUE TITLE
can't see FAST-EVENT-SKOS ontology in CEDAR

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#558]
Yesterday I submitted ontology FAST-EVENT-SKOS to BioPortal but I can't see it in CEDAR when I try to use it to constrain a field value.

**Comment by marcosmro** [comment]
Hi Michelle,

The BioPortal information page for FAST-EVENT-SKOS (http://bioportal.bioontology.org/ontologies/FAST-EVENT-SKOS) shows that it has been correctly uploaded, but it has not been processed yet (parsed, indexed, generated metrics, etc.). As a consequence, the terms from that ontology are still not available in BioPortal. If you try, for example, to browse the ontology tree, you will see that it's not available (http://bioportal.bioontology.org/ontologies/FAST-EVENT-SKOS/?p=classes&conceptid=root).

The ontology will be available in CEDAR around 10 hours after BioPortal finishes processing it. If you need to have it in CEDAR immediately after it's available in BioPortal, just let me know and I will force the CEDAR caches regeneration.

**Comment by marcosmro** [comment]
Note that the processing status of the ontology is shown in the submissions table (see screenshot below). When the ontology processing is done "(Uploaded)" will be replaced by "(Parsed, Indexed, Metrics, Annotator)".

![screen shot 2017-08-31 at 10 08 19 am](https://user-images.githubusercontent.com/7634440/29935755-c254d648-8e34-11e7-8b45-335c02ccf2c5.png)

**Comment by marcosmro** [comment]
@michelleif I have decreased the CEDAR caches regeneration delay to 3 hours and applied this fix to the staging and production servers. Now you will 'only' have to wait 3 hours instead of 10 from when BioPortal processing is done.
