### ISSUE TITLE
Scrolling fails when sorting user folders by name

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#561]
1) Go to Users folder
2) Choose Sort by Title
3) Start scrolling down, past the first set of returned folders
4) At some point (see image) the scroll will skip backwards (out of alphabetical order). If you keep scrolling down, this happens again.

(This happened with Safari on an older Mac.)

![screen shot 2017-09-06 at 12 44 28 pm](https://user-images.githubusercontent.com/1266896/30131666-69fc5cfa-9302-11e7-8c6e-c7a3233ff553.png)

**Comment by willrett** [comment]
Can't duplicate. Each scroll past 100 documents will result in a request to the server which should have the same sort order unless the user selects a new order.
