### ISSUE TITLE
pick list vs multiple choice (new?)

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#562]
When entering a template, I found a pick list field type that I hadn't seen before. What is the purpose of this field/why do we need it in addition to radio button and checklist fields?

On the execution side, the UX is awkward. The controls are very wide, making Select All and Deselect All little tags in big boxes (with ambiguous clickability), and the selection check mark indicators are very far from the names. It is impossible to tell whether there is a maximum on the number of selections without clicking. Multiple clicks require re-clicking on the drop-down, instead of leaving the list up for additional clicks.

**Comment by graybeal** [comment]
See also #572

**Comment by marcosmro** [comment]
In response to your first comment, the only difference between pick lists and the other multiple choice fields (checkboxes and radio buttons) is that pick lists show the possible choices using a dropdown. The pick list field is not essential but it may be handy for fields that have more than just a few possible choices (let's say, more than 15 choices).

**Comment by willrett** [comment]
The UX behavior is non-standard and should be removed.  Multiple select should be done using shift and control keys, not with two new buttons.  The list should stay open until the user closes it.
