### ISSUE TITLE
checkbox field entry issues

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#563]
When checkbox field has a default, when the user clicks to enter data, the default option is not selected in the drop-down. If the user choose either higher option, its check box appears, and the default is maintained as a selection but not shown as checked. If the user chooses the final option, nothing changes.

Populate the practice template using https://cedar.metadatacenter.net/instances/create/https://repo.metadatacenter.net/templates/0b1aafe4-4503-42da-a473-f9aad8ce1402?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2Fe3ce3ccc-b5bc-4096-bfc2-26fd99064c2b to test this for yourself.

**Comment by marcosmro** [comment]
Interesting issue. Our checkboxes use ng-true-value to specify the value returned by the checkbox when it is selected. The value provided for the default option in the template ( 'I don't have an opinion (the default)) contains singe quote, which caused a parsing problem. The solution was escaping the single quote (replacing ' with \').

**Comment by willrett** [comment]
This appears to be fixed.
