### ISSUE TITLE
Date field unpredictable

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#566]
Date field has poor handling of dates. text like "nov 3 2010" in the data field is parsed, turned into a semi-random date (03/20/2010 for case above; if "oct " is entered, the current date is immediately entered (?!). Hitting return multiple times after "3/7" does nothing at all, but hitting "OK" after that enters the date.

**Comment by martinjoconnor** [comment]
See also https://github.com/metadatacenter/cedar-template-editor/issues/289

**Comment by martinjoconnor** [comment]
Also reported by LINCS. Will address.

**Comment by willrett** [comment]
The date field in JSON metadata  should be xsd:date,   e.g.   yyyy-mm-dd

"date": {
    "@value": "2018-03-14",
    "@type": "xsd:date"
  }

**Comment by willrett** [comment]
The buggy eonadsan date time picker was removed.  

Dates are stored as xsd:date but allowing invalid values means the @type will be xsd:date but the value can be any string.  Do we want the @type to be xsd:date for invalid dates?
  Valid dates will be in the yyyy-mm-dd format.
