### ISSUE TITLE
Versioning requirements

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#57]
Currently, all elements and fields added to a template or other element are copied as is. We need to support references also.

Significant design work will be required.

Related to resources references (#203).

This task reflects the design phase only.

**Comment by martinjoconnor** [comment]
Marcos has suggested an approach that may greatly simplify this task. Needs more discussion but basically we will continue to inline all fields and elements in addition to keeping the original versioned copies of those fields and elements in our repository. Each element and field has a unique @id which can be used (optionally) to discover later versions of them. Users can (again, optionally) decide to attempt to upgrade to later versions (which may be easy and automatic or hard or impossible). 

We will henceforth refer to this task as 'versioning'  and will disentangle it from the provenance tasks (which is related but somewhat independent).

**Comment by martinjoconnor** [comment]
The auto-save task (metadatacenter/cedar-template-editor#38) is also related. 

A resource is not version-incremented as it is edited in draft mode - its version  is only incremented when is is 'published'.

**Comment by graybeal** [comment]
What does "published" mean in the previous comment?

**Comment by graybeal** [comment]
Reference how versioning can be used to simplify template management for the user in https://github.com/metadatacenter/cedar-project/issues/607.

**Comment by martinjoconnor** [comment]
"Published" above means in final form for its version number. As in with our code, for example. We have 1.5.0-SNAPSHOT during development and publish 1.5.0 when it is completed. We then move to the 1.5.1-SNAPSHOT.

**Comment by martinjoconnor** [comment]
Requirements document here:

https://docs.google.com/document/d/1E-u8zdq9oX5XL1OlZk28g47FlUgljFK-ubfxeSwGd8s/edit#
