### ISSUE TITLE
Old controller term search text replaces newer

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#574]
After a number of other searches and value set building, I entered a search for 'colours', picked my concept. Next field, I entered a search for 'age range'. I started to get those results, then they disappeared, and I was suddenly getting results for Color (one of my previous searches), even though Age Range was still shown as the search term.

![screen shot 2017-09-07 at 7 48 09 pm](https://user-images.githubusercontent.com/1266896/30194083-e9b32cf4-9405-11e7-96a0-030cd5174bb0.png)

**Comment by willrett** [comment]
Your issue may be coming from a slow bioPortal search.  When the dialog is opened, the search term is displayed in the input field and the search is initiated.  It take a little time for it to refresh the table below.    

I was not able to reproduce the issue that you described, but I did fix a problem with the second search on the same field clearing the search term.  If you have a more detailed way to produced the original issue, please update it here.
