### ISSUE TITLE
Use schema.org for schema title and description

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#575]
We are currently using the 'title' and 'description' Json Schema keywords to describe the schemas of templates, elements, and fields. For template instances, we use schema:name and schema:description.

Should we use schema:name and schema:description to describe templates, elements, and fields?

**Comment by marcosmro** [comment]
Discuss with @martinjoconnor

**Comment by marcosmro** [comment]
let's do it

**Comment by willrett** [comment]
I parked my changes in the branch feature/issue-575
