### ISSUE TITLE
Error on empty template description

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#583]
I made a template. I didn't fill out the Template Description field. I tried to Save and got a red error box which I could click on for technical details and the message was "you need to provide a non-null value for the parameter description..."

**Comment by michelleif** [comment]
![cedar_error_upon_save.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46eb919e2290bcac9dfbb0519b48e09b277934723f01e1673295f127b54778154d555ca9470b5944fdf9d822f4e43c24895d08edd1695e73ce6b42bea4905dee5fee7fd616cfe3fe9846d2ea3f2fe68e8f4a391b051b8bfd5832a88b06.png)

**Comment by martinjoconnor** [comment]
Thanks for the report. We will look at this.

**Comment by martinjoconnor** [comment]
Check also for elements.

**Comment by graybeal** [comment]
Do we want to make it a warning rather than an error? I am not sure it is necessary to require a description, as the names are sometimes pretty fully descriptive and it can be irritating to users.

**Comment by willrett** [comment]
There should be no error or warning.
