### ISSUE TITLE
Initial bioSample/SRA submission requirements analysis

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#587]
Investigate requirements for generating a CEDAR-based submission interface for SRA and BioSample.

**Comment by willrett** [comment]
Requirements, notes and links about SRA submission using CEDAR.

https://docs.google.com/document/d/16rQUoS0FcRsyXfFpKpa4Ng8StP4aIjhHqzY9st2ccRo/edit#heading=h.vtcza5sx70ld

**Comment by martinjoconnor** [comment]
We came up with the following initial tasks.

Waffle tasks addressing these (plus others that we will identify) will carry the ```Submission``` label: https://github.com/search?q=user:metadatacenter+label:Submission&type=Issues&state=open

Improve SS (help text, slow cells, general usability)

Optional attributes
Supporting multi-instance optional attributes

Supporting optional attributes in spreadsheets
Supporting multi-instance optional attributes in spreadsheets. Perhaps have attribute name as header. Allow dynamic addition of more.

Videos

Smart clone. Multiple fields in multi-instance element - characterize as cloneable fields or no. Clone but confirm/not. Generate new ID.

Default view in template or element or profile

Question skipping.

Business logic: all 4 field need to be unique

Auto-populate fields from profile
