### ISSUE TITLE
New CEDAR VM with DNS entries

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#59]
We need a new CEDAR VM (cedar-dev3.stanford.edu?) running the latest CentOS 7 with the following DNS entries pointing to it:

auth.dev3.metadatacenter.org
cedar.dev3.metadatacenter.org
folder.dev3.metadatacenter.org
repo.dev3.metadatacenter.org
resource.dev3.metadatacenter.org
schema.dev3.metadatacenter.org
template.dev3.metadatacenter.org
terminology.dev3.metadatacenter.org
user.dev3.metadatacenter.org
valuerecommender.dev3.metadatacenter.org

Is there a way the CEDAR team itself can set up DNS entries?

Do not install LetsEncrypt or any other software.

**Comment by alexskr** [comment]
we created internal Jira ticket to keep track of it: BMIRIT-335

**Comment by alexskr** [comment]
cedar-dev3 is deployed.

**Comment by martinjoconnor** [comment]
Great. Thanks.

**Comment by alexskr** [comment]
please note that i created a wildcard DNS record for *.dev3.metadatacenter.org so any sub-domain should work without having to update DNS.

**Comment by martinjoconnor** [comment]
Would it be possible to convert the other two machine certs to wildcard certs too? Would be one less configuration option to worry about when we add other services.

**Comment by alexskr** [comment]
I have not created any TLS/SSL certs for dev3.  
Currently we use letsencrypt to generate TLS/SSL certs but unfortunately it doesn't provide wildcard certificates so we would need to continue generating cert for each sub-domain used.

**Comment by graybeal** [comment]
CEDAR would be happy to pay for wildcard certificates, to save the time managing individual certs. I'll open a new task for that.

**Comment by martinjoconnor** [comment]
I'll play with Let's Encrypt a little more next week. My experience so far with it is positive so generating a new cert does not seem hard. We can decide then.

**Comment by alexskr** [comment]
we need to put some tooling in place to streamline letsencrypt to make it easier to work with.  It is on my task list already

**Comment by martinjoconnor** [comment]
Sounds good. I really like the control and flexibility that Let's Encrypt
gives us. Money is not really the issue.
