### ISSUE TITLE
Initial analysis of how to extend the CEDAR Workbench to work with multiple BioPortal installations

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#592]
Here we can list some relevant tasks that will have to be completed to extend the Terminology Server, the Template Model, and the Template Editor to work with multiple BioPortal-based ontology repositories: 

1) Use unique ontology identifiers across repositories. Instead of ontology acronyms (e.g., OBI) we will need to use URIs (e.g., http://purl.bioontology.org/ontology/OBI).

**Comment by graybeal** [comment]
Yes, will need to know the repository, the ontology, and the term. The URI will get us the first two.

**Comment by martinjoconnor** [comment]
Here are some analysis notes for this task (erroneously posted to https://github.com/metadatacenter/cedar-template-editor/issues/707 originally): 

https://docs.google.com/document/d/1ec9xIZQk0ERGRWh5pE8Py8SY9xQ7teWp8IF8rix69XA/edit?usp=sharing

**Comment by martinjoconnor** [comment]
Closing this initial analysis task. We will revisit notes above when we decide to prioritize.
