### ISSUE TITLE
Field renaming does not always work

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#593]
Sometimes renaming a field does not have any effect. The user enters a new field name but the old field name stays unchanged (both in the UI and in the model).

**Comment by marcosmro** [comment]
This issue is happening for nested elements too. Sometimes renaming the "propertyLabel" does not work.

**Comment by graybeal** [comment]
May be related to something I saw when searching for a BP match, see https://github.com/metadatacenter/cedar-project/issues/574 (couldn't be duplicated). Maybe there is a race condition that leads to the new term being overwritten?

**Comment by marcosmro** [comment]
Fixed. It was not related to the BP search modal.
