### ISSUE TITLE
Field titles split unnecessarily

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#597]
I don't know why the labels 'label' and 'superclass' are on separate lines here. Ditto 'Submitter\<newline\>email' (unfolder Term Request Submitter in the instance https://cedar.metadatacenter.org/instances/edit/https://repo.metadatacenter.org/template-instances/fa782306-ad9d-40b3-95c5-926070053c5b?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2Feab8895e-b887-4862-948b-1eda3fab7382 )

![screen shot 2017-10-26 at 6 27 03 pm](https://user-images.githubusercontent.com/1266896/32084423-e401a940-ba7d-11e7-9a7d-848ad7ac31f7.png)

**Comment by willrett** [comment]
I think this has been fixed in a prior release.

**Comment by graybeal** [comment]
Sorry, just duplicated the strangeness on staging. 
(1) Go to CAIRR metadata instance, https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/8b14094b-67a6-492b-8520-5373d7859cbd?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2Fb6cb3d33-ad8b-4a2e-bbdb-a237f02cf3d4&search=CAIRR&t=1510630949696. 
(2) Expand your browser view with CMD-+ a few times (twice, for this image, which yields 125% view).

Boom, there we are. First line is wrapped unnecessarily.  If you go down to 110%, the top one unwraps, but the bottom one now wraps! 

![screen shot 2017-11-13 at 7 42 52 pm](https://user-images.githubusercontent.com/1266896/32761954-40d3dc70-c8ab-11e7-8bae-bda94844e769.png)

**Comment by willrett** [comment]
I don't see that but as you zoom it there are some oddities.

**Comment by willrett** [comment]
Cannot duplicate this problem.
