### ISSUE TITLE
Have explanation text for issue triangle in text field

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#598]
The issue triangle in the top field of https://cedar.metadatacenter.org/instances/edit/https://repo.metadatacenter.org/template-instances/fa782306-ad9d-40b3-95c5-926070053c5b?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2Feab8895e-b887-4862-948b-1eda3fab7382
in this screen grab carries no explanation on mouseover. On reflection I realize it is complaining because the label was empty, but not obvious that it was "wrong" before I even started filling it out. Needs a pop-up.

![screen shot 2017-10-26 at 6 21 08 pm](https://user-images.githubusercontent.com/1266896/32084496-52aef654-ba7e-11e7-9edf-68ab6538b523.png)

**Comment by willrett** [comment]
Explanation text for all invalid fields in template goes into pink box at the bottom of the form.   This covers invalid values as well as required fields that are missing.

**Comment by graybeal** [comment]
yes, that is true. Unfortunately that does not help the user who doesn't know that's where to look, or who doesn't want to save yet to generate the error list. And there is a burden that puts on users, long after they may have entered the text that caused the problem, to track back each issue to the specific field causing the issue. It would be very cool if the issues could be mapped back to individual fields. (Even issues from external validations! But that could be Very Hard.)

So it still seems like a useful usability improvement, but if it is expensive maybe not so important.

**Comment by martinjoconnor** [comment]
As per above, I think this may become more pressing with some of the new field constraints we added for CDEs.

For example, when we have a string field that has minLength=5 and maxLength=10 the triangle appears and disappears in a potentially confusing way as the user continues typing.

**Comment by willrett** [comment]
We can add detailed browser-based validation popups, but this means you will not be able to enter invalid values.   This would be a much better idea than what we are doing now.  Then we probably can do away with the pink box at the bottom of the form for field validation items.

**Comment by willrett** [comment]
Fixed
