### ISSUE TITLE
descriptions (tips)(help) pop-up icons missing

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#599]
*love* the new pop-up icons for the help tips (descriptions) in the template editor. But they seem to be missing for 'multiples' (reference) and dates (submission date).

![screen shot 2017-10-26 at 6 56 21 pm](https://user-images.githubusercontent.com/1266896/32084676-668c2286-ba7f-11e7-98b4-e51cccf7f70a.png)

**Comment by willrett** [comment]
Not sure what you mean.  Show a screenshot of the popup.

**Comment by willrett** [comment]
fixed in the feature/attribute-value-pairs branch
