### ISSUE TITLE
Alternate URIs for resource operations

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#60]
Currently CEDAR resource operation URIs are form: `<toolURI>/<ResourceIRI>`

Perhaps also support alternate form:

`<ResourceIRI>/tool`

e.g.,

https://cedar.metadatacenter.net/templates/4343/edit

**Comment by graybeal** [comment]
Using ? as the delimiter is common practice to separate the resource IRI from the additional information (otherwise impossible to tell where the unique identifier ends, as / is not a terminator)

**Comment by martinjoconnor** [comment]
Done
