### ISSUE TITLE
want better description pop-up field

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#600]
Can we have a description pop-up field in the metadata editor that is as cool as the one in the template designer? (See #599 image). I'd sort of like the ? icons to be on every field, but that will be busy, so can the '?' show up when you mouse over the field and then the pop-up show up when you mouse over the '?'  ?

**Comment by willrett** [comment]
The ? will be there if the user defined help text.  When you hover it shows the help text in a tooltip.
