### ISSUE TITLE
when copying a template, the newly created copy should be given a different name than the original

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#606]
I made a copy of a template and accepted whatever was prompted re where to save it and what to call it. I ended up with two templates with the same name which is confusing (it is confusing even though they have different dates). User will expect that the copy will be named something like "[original_name}_copy" or to be prompted "choose a new name".

**Comment by michelleif** [comment]
I would like to label this as an LD4P issue but I don't have permission to assign labels.

**Comment by willrett** [comment]
The template editor renames the file on the copy by appending the string "copy",  but the server is not giving the copy the new name.  Below is an example call and payload.

https://resource.metadatacenter.orgx/command/copy-resource-to-folder

@id:"https://repo.metadatacenter.orgx/template-elements/4cdb18a0-c397-4170-a19f-a88f8fca3e6e"
folderId:"https://repo.metadatacenter.orgx/folders/6649b825-a667-4b70-b561-b6380112d65f"
nodeType:"element"
titleTemplate:"Copy of name"

**Comment by egyedia** [comment]
Fixed on develop
