### ISSUE TITLE
Handle changes to in-use templates

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#608]
(Reference to versioning task: https://github.com/metadatacenter/cedar-project/issues/57)
(Reference LD4-SU task "3.1.5 Better handling of changes to templates that have already been used to create metadata")

In a recently added feature, the user is prevented from editing the template when instances exist using that template. This forces the user to copy the template to a new one, or find all the instances and delete them, even if they are still useful. Without versioning, this approach also loses track of the relationship between the different copies, which are really meant as versions of a single template, and an unmanageable mess will result before long.

A more version-aware implementation will let the user edit the template, after accepting a warning that existing instances will not work with the new template. When the user saves the edits, this produces a _new version_ of the same template. The previously created instances are unaffected, because they point to the _previous version_ of the template (all versions are saved). 

When a user wants to access any previous version, they can select it from a drop-down menu for that template, which shows all the versions of that template, the version dates, and the number of instances that use that version. The default is to always open the current version. By default, intermediate versions (that have no instances associated) are not shown, but they can be shown on request. (Similar to Google docs showing groupings of edits as major versions (the default view in the Revision History), but letting users see all edited versions on request.)

**Comment by graybeal** [comment]
Future work that becomes useful once this is implemented:
* Tool to upgrade existing instances to new version.
* Tool to show differences between versions.
* Warnings when a new version is incompatible with existing instances (e.g., by modifying field types of fields that are already have instance data).
* Tool to identify where a template is used in other templates (when we manage Elements as Templates).
* In-line tool that recognizes when imported elements/templates have been changed, and can help manage upgrading to the most recent version.

**Comment by graybeal** [comment]
Many of these features are being handled with versioning and with recent mods warning about template changes. This should be spun into a new feature.

**Comment by martinjoconnor** [comment]
2.0.0 versioning features address most of these issues.
