### ISSUE TITLE
Duplicate folder dispay

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#611]
When I login with willrett@stanford.edu on staging and click "shared with me" I see two copies of the AIRR folder.  Clicking one selects both of them.

**Comment by michelleif** [comment]
I experience this also: moved one thing into a folder. Then selected another thing to move, and in the box that comes up where I select the destination, that folder is listed twice. The third thing I try to move, it's listed 3 times, and so on and so on.

**Comment by willrett** [comment]
Issue #630 is the error in the copy and move modal.  This issue is with the workspace.

**Comment by michelleif** [comment]
Another user shared a template with me. When I go to "Shared with Me" I see the template listed twice. When I click one, it selects both. When I right-click to get the menu to Populate etc., only a small portion of the menu shows up.
![double.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46ec9b8f218e86ebc3abaf51ab57f5973d047d317c52a07d20d4b329e64079510b5c4faf41585b45fbf1df78b4aa2e32db025fb28c341521842f1bbeba8015be04bb23834687b1b58e4cc1e82f68.png)

**Comment by martinjoconnor** [comment]
Atti discovered that this is a result of multiple sharing paths to resource. For example, if a resource is shared with a user on two different ways (e.g., directly plus through a group) then it will appear twice. With three sharing routes it will appear three times, and so on.
