### ISSUE TITLE
Sample intelligent authoring template

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#614]
Put a template with associated instances in a well known location for demo purposes.

**Comment by marcosmro** [comment]
I have uploaded the BioSample template and approx. 35K instances to the production server (path "All / Shared / CEDAR / BioSample - Intelligent Authoring Demo").

**Comment by graybeal** [comment]
This is GREAT!  Thanks so much. How did you choose the instances, is there anything I can say about the source of the resulting suggestions?

Also, I can't save to that folder once I've created metadata. (Need to create a feature request for that generally, hate to be in the middle and have to throw away everything at that point.)  Can you please give CEDAR team access to the folder?

**Comment by marcosmro** [comment]
I have uploaded the template and the instances to the same path of the staging server ("All / Shared / CEDAR / BioSample - Intelligent Authoring Demo"). The link for staging is:
https://cedar.staging.metadatacenter.org/instances/create/https://repo.staging.metadatacenter.org/templates/7747d0b3-5c93-4ffe-a096-f14d1e2fedec?folderId=https:%2F%2Frepo.staging.metadatacenter.org%2Ffolders%2Fe91e64c4-3d0f-4e19-82d3-2d789334c8c2

I have given the CEDAR Dev team access to that folder, so you should be able to create new instances with your user. However, keep in mind that when saving a new instance, a red box will show up saying that the external BioSample validation failed. We implemented that validation for one of our demos in 2016 and it was a very custom validation that we don't need anymore. I have disabled that validation in the template editor and the red box will disappear once the frontend code is released to staging/production.

All those BioSample instances were generated by Ravi last year using raw metadata from GEO, annotated with ontology terms using the SAP pipeline that he developed. I have updated both the template and the corresponding instances to the latest version of the CEDAR Template Model.
