### ISSUE TITLE
Section break does not work

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#617]
1. I added a section break called SECTION BREAK to a template (see my template, shared with CEDAR Dev team, called "Fun for Testing!"), when I go to populate the template, the section break does not show up anywhere.
2. when I add a section break to an _element_ and then put that element in a template, and then try to populate the template, the section break _does_ show up (see Element 1 in the above template), but it shows up as a clickable field, as if it were expecting me to enter text. I expected Section Break to be just a navigational aid to group fields together, is that what it's for? if so it shouldn't be clickable.

**Comment by michelleif** [comment]
the same points apply to the Rich Text field: Rich Text field in a template does not show up when you populate the template. It does show up if you put it in an element, but why is it clickable?

**Comment by willrett** [comment]
I fixed section break and the other static fields.  I also added page break to bread the form into different pages.  The page will only break at the template level, not inside nested elements, so you can only add a page break to a template.

Static fields will need to be changed at some point soon.  They get added to the following field, but they should be defined when you define the field and not as a free standing field in the form.  Section breaks are actually free standing additions to the form, so section and page breaks can remain they way they are.
