### ISSUE TITLE
Value set does not show up when populating template

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#618]
I tried to create a value set so that my field would have a list of values to choose from when populated. (To see this you can go to my element called "Activity Element for Audio Work: value set didn't work" and shared with CEDAR Dev, and the field is "Type of Activity"). I  clicked Values / Search / Create New Term / Create Value Set and searched for and chose 3 different terms from the bibliotek-o ontology. When I clicked "Create Value Set" to save, I got 3 messages "Error establishing a connection to BioPortal. Please try again later" (all appeared at upper right corner, one after the other).

When I add this element to a template ("Fun for Testing!") and try to populate that template, and click on the "Type of Activity" field, no values are presented.

**Comment by martinjoconnor** [comment]
Is this persistent? As in, happens for all value set creations?

**Comment by michelleif** [comment]
I tried a new value set on a new field in a different template and it still happens. I didn't get the "Error establishing connection" this time, chose the values from other ontologies.
You can take a look, the template is called Test and I shared it with CEDAR-Dev, and there's only one field in it, the field with the value set, which is called "my value set" and is supposed to contain 3 values.

**Comment by marcosmro** [comment]
Addressing https://github.com/metadatacenter/cedar-terminology-server/issues/13 will probably solve this issue too.

**Comment by graybeal** [comment]
@michelleif I believe this is now fixed, I had a similar problem which has just been addressed. If you have a staging account, can you see if it works for you now in staging?

**Comment by michelleif** [comment]
It doesn't work for me in staging. You can see my template "test", I've shared it with CEDAR Dev Team. I made a field called "Untitled". I created a Value Set for the field by searching for and choosing 3 different terms. When I saved the value set I got the message "Error establishing a connection to BioPortal. Please try again later", 3 times, in upper right corner. When I tried to populate the template, that field displays "No results" (before and after trying to type something in the field) and does not show the 3 terms in my value set.

**Comment by marcosmro** [comment]
@michellef @graybeal I have investigated this problem and it was different from #740. I have fixed it and pushed the fix it to our develop branch but it has not been released to staging/production yet. I will wait to close this issue until we release it (probably tomorrow) and Michelle confirms that everything works fine.
