### ISSUE TITLE
copy a shared template to your own folder

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#620]
If someone shares a template with me, a common task I'd want to do is to copy that template to my own folder, to then create another template based off it. So I go to "Shared with Me" and find the template. I copy it. CEDAR asks me where I want to put it, and offers the folder the template is already in. If I want to copy it to my own user folder, I have to figure out how to navigate to my own folder. I can't find my own "home" folder.

**Comment by martinjoconnor** [comment]
Task here: https://github.com/metadatacenter/cedar-project/issues/387

I've folder your text into that issue and added an LD4P label to it.
