### ISSUE TITLE
what is invalid about my template or element?

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#621]
I made an element. A little yellow warning sign appears at upper right saying my element is invalid. I have no idea why it's invalid. I click on a field to check what values are assigned to it (none) and then save, and now my element shows a checkmark and is valid. I go back to my folder of stuff and open the same element again. Now it is invalid again.

**Comment by martinjoconnor** [comment]
Might be related to #603 and #612.

**Comment by martinjoconnor** [comment]
Above validation tasks should address this.

**Comment by martinjoconnor** [comment]
All production templates patched.
