### ISSUE TITLE
when searching for ontology term, search on ID as well as term name

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#623]
I'm setting up a field in a template and as one of the allowed values I wanted to find
http://bibliotek-o.org/1.1/ontology/AudioDisc
so I searched audiodisc and got zero results. I could only find that term searching:
audio disc

**Comment by michelleif** [comment]
![LabelVsID.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46c49598268eb5baa6cdfd0fe64de29b234324676b5ee17e2686b578ee127a580d0d4ef842595c44fcfd882caee06f62964e49bc8f3900299f7744eeaa880dbe06b0218e4e87b6ba894bc0ee3526e699c2.png)

**Comment by martinjoconnor** [comment]
Will get @marcosmro to take a look.

**Comment by marcosmro** [comment]
This issue can be easily addressed by using the 'also_search_properties' flag provided by the BioPortal API (http://data.bioontology.org/documentation#nav_search).

**Comment by martinjoconnor** [comment]
I'll put this in 1.6 since it requires very little work.

**Comment by marcosmro** [comment]
I reopened this issue to do some final testing on CEDAR

**Comment by marcosmro** [comment]
Closing it again, my intention was to reopen a different issue.
