### ISSUE TITLE
Error when saving complex template

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#625]
I made a template with many fields and elements and when I saved I got the attached error. I removed the last element I had added to the template (an element which itself has nested elements), and the template saved fine. I re-added this element, and get the error again.

**Comment by michelleif** [comment]
![error.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46ed86882c90c1e5cdf9ad4cae58f3806b1c65267f07f57b21d5e271bd402b055c5e4dac415c5e43f4afda39baa47e21d40854b088270a36d43703adb1881eba00b820834e8dbfb48b48c7fa70.png)

**Comment by michelleif** [comment]
I played around with the template some more and now it saves ok. Will reopen if I can figure out what I did and it happens again.

**Comment by michelleif** [comment]
the error is back, but although the error was shown, the template seems to have saved successfully.

**Comment by martinjoconnor** [comment]
Reopening. We can try looking through the logs.

**Comment by martinjoconnor** [comment]
Have not seen anything like that since then. Will close and reopen if it reoccurs.
