### ISSUE TITLE
visual indication of which fields possess a description

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#626]
When populating a template, there is no way to know whether when you mouse over the question mark there is going to be a description/help text or not. The user does not want to keep mousing over and then see there is no help/description. Have a visual indication of where there is really help text.

**Comment by martinjoconnor** [comment]
Related to https://github.com/metadatacenter/cedar-template-editor/issues/157

**Comment by willrett** [comment]
I will hide the help ? icon in the metadata editor when there is no description field.

**Comment by michelleif** [comment]
The ? icon seems to be showing up even when the template creator did not add any help text, and when you mouse over it, it says "Help"

**Comment by michelleif** [comment]
sorry bout that, didn't check that this one was marked done!
