### ISSUE TITLE
Metadata recommendations using ARM – Initial experimental evaluation

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#634]
Design and carry out an experiment to evaluate if our ARM-based metadata recommendation approach can be used to generate useful recommendations for a particular template based on metadata from other templates.

For example, we could use metadata from the EBI’s BioSamples database to generate suggestions to populate a CEDAR NCBI’s BioSample template.

This task includes the work needed to finish an initial implementation of our ARM-based approach as part of CEDAR's Value Recommender service.

**Comment by martinjoconnor** [comment]
Paper task: https://github.com/metadatacenter/cedar-project/issues/665
