### ISSUE TITLE
template validation errors with controlled term values

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#635]
I created a template with one field containing a controlled term whose values are from the term tissue in NCIT.  I shared this on staging under "tissue shared".  The template is getting validation errors:

Validation Error: object has missing required properties (['required']) at location /properties/tissue
2create-template.controller.js?v=1.5.0:299 Validation Error: object has missing required properties (['items','minItems']) at location /properties/tissue
create-template.controller.js?v=1.5.0:299 Validation Error: instance value ('https://schema.metadatacenter.org/core/TemplateField') not found in enum (possible values: ['https://schema.metadatacenter.org/core/StaticTemplateField']) at location /properties/tissue/@type

https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.org/templates/84fe0427-b9e4-4e03-ab65-1e0bf99186f8?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2F76bbbd4c-8170-4841-aba1-3953a8f8a12b

**Comment by martinjoconnor** [comment]
Diplicate of https://github.com/metadatacenter/cedar-project/issues/612
