### ISSUE TITLE
Visual indication that user has been successfully added to a group

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#641]
I'm adding users to an existing group in Group Settings. I start searching for the user, jean... and find the one I want. I click the plus sign to add. Now (1) the plus sign is still active and (2) I don't see the user in the list of users in this group because there are already users in the group so the new user got added to the bottom, and (3) the user's name is still in the field. So now I'm wondering, did my user get added?

One way to improve this: after the plus sign is clicked, show a message "userx was added to groupx"(or put the newest user at the top of the list) and then clear the search box.

**Comment by michelleif** [comment]
![was_user_added?.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46ff95891c9790ac9dd6be47a058f4cb6b0a65633b0ba92e7391a172fd172d02595f4fac10510d16fcad8a2aa5b63c748b5b03bb827f4366846c4ff8e7df46f554f832815d84bfb68b49c1eb3a24e58987493d17010ac4.png)
![user_still_in_searchbox.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46fd879f31bd90bd86e5b37cad53cf872c4735702106ac3332c9a138ad4d71040c1b5ca6535d5917faf9882bf7bf6e228a0808ecd26d5f70c73a19faeb9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3f1d02198bfc5d3da89e4fda15.png)

**Comment by willrett** [comment]
I made a couple changes which I think will improve this.  (1) the + icon color when disabled is gray, so now you will see it "appear" when it is enabled.  (2)  After a user is added to the list on the right, they are removed from the input field on the left.  This will disable the + icon.   (3)  Any new addition goes to the bottom of the list on the right and the container is scrolled to the bottom.  This should scroll to the new item.

Try it with these changes, and let me know if you think more work is needed.

**Comment by michelleif** [comment]
(2) and (3) look good. Re (1): If you add a user to the list at right, and then search for the same user again, the + icon is still enabled.
