### ISSUE TITLE
cannot copy a shared element to own user folder

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#644]
I shared an element with a group. Another user in the group navigated to this shared element, chose Copy To, and wanted to copy it to her own folder. She used the left arrow to navigate out of the shared folder, eventually to the Users folder, where she expected to be able to find her own folder, but instead sees only a list of other user folders in alphabetical order, ending in the Ds.

**Comment by michelleif** [comment]
[Uploading UsersEndingAtD.png...]

**Comment by graybeal** [comment]
If she starts scrolling down the user folders, they should update automagically (like when you try scrolling past the end of your LinkedIn suggested connections, it just populates more).  Sometimes there's a brief delay, but rarely more than a split second.

Any suggestion about what the user should see instead would be welcome. 

I think for the user folder list, an autocomplete popup search at the top would be very helpful; and an A-Z index to click on for getting last names starting with that letter.

Regarding the navigation up and down the paths, perhaps we should have a "My home folder" as an obvious option?

**Comment by michelleif** [comment]
We tried this multiple times and nothing came up below the Ds. #387 having a link to one's own home folder, would solve this problem. Yes a search for folders would be helpful also.

**Comment by graybeal** [comment]
oh heck, I see what's going on. It appears #630 is happening in production too now. No idea how that could have happened, but the two together make the interface non-workable within this folder (and almost anywhere). will escalate.

**Comment by martinjoconnor** [comment]
Related to #645

**Comment by graybeal** [comment]
To my knowledge it's patched in production, along with #645. just a matter now of getting the fix into the release.

**Comment by willrett** [comment]
fixed
