### ISSUE TITLE
unable to copy or move a template from user folder to shared folder

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#645]
a user has a template in a folder they made under their own user folder. the user wants to copy or move the template to a shared folder LD4 (which is under my own user folder). User right-clicks template, chooses Copy to (or Move to), then tries to use left arrow to navigate out of user's own folder and find my user folder and the LD4 folder nested there. User navigates to "Users" but cannot find my user folder listed there.
additional problems: 
(1) what order are the user folders listed in? they seem to be in random order, or maybe order in which they were created? user has no idea where in the list to find my user folder.
(2) user navigates all the way to "root" folder, and the left arrow is still active with tooltip "back to parent" even though there is no further folder to go back/up to

**Comment by graybeal** [comment]
This is same issue as #630, but now in production. It's a severe bug.

**Comment by martinjoconnor** [comment]
Related to #644

**Comment by graybeal** [comment]
To my knowledge it's patched in production, along with #646. just a matter now of getting the fix into the release.

**Comment by willrett** [comment]
fixed
