### ISSUE TITLE
Can't view spreadsheet sometimes

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#655]
See video in Box at https://stanfordmedicine.box.com/s/4rghugd0zwksvgqzk199ynbm2qmskemu (in the troubleshooting folder https://stanfordmedicine.box.com/s/3c4ubs8iwg5q2clkb3j2do9r96twtaqz).

On staging, In multi-field element that has MULTIPLE set, if I enter rows of values, at first I can cycle through the different viewing modes. But if I set the item being viewed in the "one at a time" viewing mode to the *second* item, and cycle through the different viewing modes, the spreadsheet view is now not responsive—nothing is displayed for that item. 

Example template and instance are at 
```
https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.org/templates/d7a6872e-2713-4613-9f96-f59e37a76dd6?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2F8ce5e044-a5b0-4313-a903-2a28377e85c9
```
and 
```
https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/b35ef6a5-cac6-4783-9496-4d94befeb3d5?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2F8ce5e044-a5b0-4313-a903-2a28377e85c9
```

**Comment by willrett** [comment]
Fix: 0th index has to be activated before switching back to spreadsheet view.
