### ISSUE TITLE
Top icons in metadata editor missing

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#656]
As seen in the screenshot, the Expand All and Delete icons are missing at the top of the metadata editor window.

Instance is https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/a159e3b9-41d2-4e44-867b-531ff3a591b2?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2Fa4d03ac0-0618-4011-9b7b-32e8fdb96485

<img width="1067" alt="screen shot 2018-01-11 at 8 15 06 pm" src="https://user-images.githubusercontent.com/1266896/34859625-423cd9e2-f70c-11e7-9e81-3254f16db071.png">

**Comment by willrett** [comment]
fixed
