### ISSUE TITLE
can't view multiple items OR spreadsheet

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#657]
In my latest instance, if I fill in 4 cells of data in a 2x2 spreadsheet array (the top multiple element), then I click on the <> icon, it shows the first item. I can't navigate to the second item in that view, and in the next view icon after that, no data is shown at all. When returning then to the spreadsheet icon, only the first two cells have content.

https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/a556fa4b-d81f-4643-8b57-63d68ee8dd10?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2Fa4d03ac0-0618-4011-9b7b-32e8fdb96485

Reference also #655.

**Comment by willrett** [comment]
fixed and will be on staging today
