### ISSUE TITLE
Add easy way to copy a template to the user's workspace

### ISSUE THREAD

**Issue by ssnn-airr** [metadatacenter/cedar-project#668]
To copy the AIRR template to my workspace, I had to right click and then do a few clicks to get to the root directory and then to my home directory. It would be useful to have an easy way to say 'copy to my workspace'.

**Comment by graybeal** [comment]
We will be adding a Home directory button, I think it will be included in the release we are making next week (and on staging later today!).

________________________________

**Comment by ssnn-airr** [comment]
Great!
