### ISSUE TITLE
Save button fades out and stays disabled

### ISSUE THREAD

**Issue by ssnn-airr** [metadatacenter/cedar-project#671]
Filling metadata, once the 'save' button is clicked on, it fades out and stays disabled. To have it back, one has to leave the document and reopen it, losing all edits done after this saving.

**Comment by graybeal** [comment]
I'm not able to duplicate this Susanna. I've seen it happen maybe once or twice in the last year, where the system has some major problem, but right now the button fades to a lighter green when clicked, but turns dark again almost immediately, and can then be reclicked at any time. (I know for larger forms it may sometimes take longer to save, but not terribly long.)

If this is still happening, can you capture a video of it, and/or make a copy of your metadata that you can share with us for testing? Would be great to be able to duplicate this.

**Comment by willrett** [comment]
This was an issues on staging on Friday because of the removal of the validation report header, and  it has been fixed.
