### ISSUE TITLE
Automatic renewal of Let's Encrypt certs

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#68]
[from: https://certbot.eff.org/#centosrhel6-nginx]

Let's Encrypt certificates last for 90 days, so it's highly advisable to renew them automatically! 

You can test automatic renewal for your certificates by running this command:
./path/to/certbot-auto renew --dry-run

If that appears to be working correctly, you can arrange for automatic renewal by adding a cron or systemd job which runs the following:
./path/to/certbot-auto renew --quiet

**Comment by martinjoconnor** [comment]
Hi @alexskr , Did this get addressed with the Nginx cert update you made recently?

**Comment by martinjoconnor** [comment]
Related to #77
