### ISSUE TITLE
the Save button disappeared from my template

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#680]
I made a template and saved it. I populated the template then realized I forgot to add one thing. I went back to the template. The Save button is gone. It seems to flash briefly on the screen when I open the template and then disappears.

**Comment by michelleif** [comment]
![save_disappeared.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46fb958c26bd87a09ce8af53a15ce2912d046b313916ac217586f76ae5002e570c594ead41095616aef9dd28a7b53c708e5d0ce5873e4d68d47f40f2ecdd42e64bef62994597b4bc804dc5e93a25e7888f4e371702189bb2.png)

**Comment by graybeal** [comment]
can you provide the template ID, please?

**Comment by graybeal** [comment]
I think the problem may be that you have an instance that is populated for that template, and our system is mixed up about that (it would be a bug in that case, one we may have already fixed in development. 

you may need to make a copy of the template, the copy would not be affected by the instance.

**Comment by michelleif** [comment]
yes, it was a new template, and the problem occurred after I populated it. and when I made a copy of the template, Save worked fine, and when I populated the copy, the Save button disappeared. This i the ID of the copied, then populated, template:  "@id": "https://repo.metadatacenter.org/template-fields/e435843c-f72d-4c59-8166-428e1b964122"

I opened some older templates and saw the same thing, the Save button appears briefly and then is gone.

**Comment by graybeal** [comment]
Sorry, that isn't the ID of a template, it's the ID of a field. Can you copy the URL that the browser sees, and share the relevant artifacts with the cedar developers group?

**Comment by graybeal** [comment]
I am also having problems, not exactly the same but likely related. See https://github.com/metadatacenter/cedar-project/issues/681

**Comment by michelleif** [comment]
sorry bout that.
https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/f6b2d027-8e6a-465b-a218-394890b67d1e?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F19aa9c11-2c85-4844-aca3-16c4b7f0d6cd
and I shared it with CEDAR Dev Team

**Comment by graybeal** [comment]
I've been working on my problem, if I clear cache it fixed my problem. Can you try clearing your cache (or using a different browser for a test) to see if that fixes it?

**Comment by graybeal** [comment]
Michelle reports this does not fix her problem.

**Comment by michelleif** [comment]
more info: if I delete the metadata instances I created from my template, then open the template again, the Save button is back.

**Comment by willrett** [comment]
Initially we gave a warning when editing a template with instances, but let you edit nevertheless.  Then we changed it so the save button was removed from templates with instances, but you could still view them.  Now we are back to the original warning + edit method.
