### ISSUE TITLE
property is disappearing from field in Elements

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#683]
I made an element. I added a field. I added a property. I clicked save. I went back to the field and tried to examine the property with the dropdown, and the property is empty.

If I try again to add a property and save, the second time it works.

If I then add a second field to the Element, and add a property, and click Save, the property on the second field disappears.

The problem doesn't seem to happen for Templates, just for Elements.

**Comment by michelleif** [comment]
I shared with you an element "Work Element to show LCSH" with one field, and in this field now I can't add any property at all, even doing it the second time, the property does not add, even before saving.

**Comment by willrett** [comment]
fixed
