### ISSUE TITLE
Issues with AIRR submission to NCBI

### ISSUE THREAD

**Issue by hlmeng** [metadatacenter/cedar-project#684]
I have created an instance and now would like to submit data to the NCBI. Here is the link of the instance https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/1a2e5e02-5a38-40c2-9a9c-59bf5e3819f6?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2Fc4335bc0-6259-4ec6-80e5-ef31e43c2e42. It seems to be a permission issue. Can you please help me with this?

**Comment by martinjoconnor** [comment]
We did not realize that you would have sufficient metadata to submit at this point.

We will give you the permissions. Can you post your full user name on CEDAR.

Note that submissions from CEDAR currently go to a test area at NCBI and do not become available on their main site.

**Comment by hlmeng** [comment]
My full name is Hailong Meng.

**Comment by egyedia** [comment]
Hi Hailong,

We granted you the submission permission.
Please confirm that it works for you now.

Regards,
Attila

**Comment by hlmeng** [comment]
Attila,

I am uploading two sequence files to cedar. Each file is a .gz file and include a few fastq files. But uploading is stopped in the middle:

[cid:image001.png@01D39E67.D3D8B090]

Thanks,
Hailong

**Comment by martinjoconnor** [comment]
Can you tell how big each file is?

**Comment by hlmeng** [comment]
3.5G

**Comment by martinjoconnor** [comment]
Thanks. We will take a look with similarly-sized files here.

**Comment by martinjoconnor** [comment]
We discovered that we have disk space issues that prevent the upload of large files. We are addressing this and hope to have the problem fixed by tomorrow. We will post here to let you know.

**Comment by martinjoconnor** [comment]
Please try again and let us know if there any issues.

**Comment by hlmeng** [comment]
It gets better now and seems the file is uploading to your server. But as shown in the figure below, the upload window is frozen there for a few hours and it did not show me if the uploading succeeds or not. I cannot select the other file from the same interface to upload. Could you please check from your end if the uploading is complete or not? The file should be ~3.4G. Thanks.

[cid:image001.png@01D3A02F.933F42A0]

**Comment by martinjoconnor** [comment]
I cannot see the image you uploaded. I think you need to wait for it to upload to Git before pressing 'Comment'.

**Comment by martinjoconnor** [comment]
We have a regular call with the Ahmad at 1/4 PT/ET on Thursdays. Would you like to join us tomorrow to demonstrate the problem? Otherwise we can arrange a separate call.

**Comment by martinjoconnor** [comment]
Are you picking an AIRR metadata instance before clicking on the submit dialog?

Note that you can close the hanging dialog using the Close button or the by clicking on the X.

**Comment by hlmeng** [comment]
Yes, I did pick the AIRR metadata instance before clicking on the submit dialog. I know I can close the hanging dialog using Close button, but I just want to make sure the whole uploading process is complete. The dialog has been there for more than one day. So I just close it.

[cid:image001.png@01D3A0E0.3BB39660]

**Comment by willrett** [comment]
So you are getting errors uploading?  Do you want to send us an image via email?  Or demo the problem on a call?  We have a regular call at 1pm PT on Thursdays.



Debra Willrett

Senior Software Developer, Research

Stanford Center for Biomedical Research | Stanford University

Medical School Office Building | 1265 Welch Drive, X207

Stanford, CA 94305

http://metadatacenter.org

________________________________

**Comment by hlmeng** [comment]
I am attaching the dialog in the attachment. I am in the same office with Ahmad and I can talk briefly when you have meeting.

Hailong

**Comment by willrett** [comment]
TODO:
1. ignore nested elements when switching to spreadsheet mode
2. give access to current and past messages at all times via toolbar
3. show that the upload is complete so the user knows to close the submission dialog

**Comment by willrett** [comment]
fixed
