### ISSUE TITLE
Toggle view for biosample

### ISSUE THREAD

**Issue by hlmeng** [metadatacenter/cedar-project#685]
Toggle view for biosample does not work for this instance: https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/1a2e5e02-5a38-40c2-9a9c-59bf5e3819f6?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2Fc4335bc0-6259-4ec6-80e5-ef31e43c2e42

**Comment by martinjoconnor** [comment]
Can you share this resource (with read access) with the "CEDAR Dev Team" group. 

Right click on it on the workspace and select Share...

**Comment by willrett** [comment]
fixed

**Comment by hlmeng** [comment]
Toggle view now is working

**Comment by hlmeng** [comment]
Now a new problem is that the fastq file and biosample mapping part disappears and I cannot find the place to specify fastq file names.

**Comment by willrett** [comment]
The nested elements, such as the element capturing the fastq file names, will not show in spreadsheet view.  To edit these you will need to switch to one of the other views.  This is a short term workaround until CEDAR supports nested elements using spreadsheet view.
