### ISSUE TITLE
Cannot input data

### ISSUE THREAD

**Issue by hlmeng** [metadatacenter/cedar-project#686]
Cannot input data to field of "Number of Cells per Sequencing Reaction*"

**Comment by martinjoconnor** [comment]
We will look at this. It seems that this field is not of the correct type and is looking for a URI instead of a number.

**Comment by marcosmro** [comment]
We patched the template. @hlmeng: you should be able to enter data into that field now.
Template id: https://cedar.staging.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.staging.metadatacenter.org%2Ffolders%2F5b64cd93-fbde-41b8-837e-0d1965e651ce
