### ISSUE TITLE
toggle doesn't work

### ISSUE THREAD

**Issue by ssnn-airr** [metadatacenter/cedar-project#687]
Nothing happens when I click on the 'Toggle View' button/icon

**Comment by willrett** [comment]
Please link to an example.

**Comment by ssnn-airr** [comment]
Actually, something happens. If there are more that one biosamples, they appear at the bottom. I was expecting Toggle View to open a grid. At least this is what I recall from an old presentation by @ahmadchan 
This is the project I am working on https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/6e69a794-8fe4-4b36-aa36-40e5122c4004?folderId=https:%2F%2Frepo.staging.metadatacenter.org%2Ffolders%2F34ca0f97-e28b-4f42-9a7a-55aa22e0bfef

**Comment by ssnn-airr** [comment]
@willrett  I dind't mean to close this issue. I am on an train and I accidentally ended up hitting close instead of submit.

**Comment by ssnn-airr** [comment]
I have tried from a different computer, and the Toggle View shows a grid. Maybe I am having cache issues.

**Comment by ssnn-airr** [comment]
I confirm after cleaning cache Toggle shows the grid
