### ISSUE TITLE
How to add multiple biosamples and SRA files?

### ISSUE THREAD

**Issue by ssnn-airr** [metadatacenter/cedar-project#689]
I have to add several biosamples to my bioproject. Each biosample has its own pair of fastq files. I am not sure how to represent this in CEDAR. Is it possible? 

The AIRR template doesn't add SRA sections for each additional biosample, neither it provides a way to link manually generated SRA sections to biosamples (for example using the biosample id). Or maybe the library name should match the sample name? 

This is an example of the type of data I need to represent. I have only added the SRA part for the first two samples.

project
|- subject 1: healthy
     |- sample 11: memory B cells --> 11_read1.fastq and 11_read2.fastq
     |- sample 12: naive B cells --> 12_read1.fastq and 12_read2.fastq
|- subject 2: healthy
     |- sample 21: memory B cells --> 21_read1.fastq and 21_read2.fastq
     |- sample 22: memory B cells --> 22_read1.fastq and 22_read2.fastq
|- subject 3: healthy
     |- sample 31  
     |- sample 32
|- subject 4: disease
     |- sample 41
     |- sample 42
|- subject 5: disease
     |- sample 51
     |- sample 52
|- subject 6: disease
     |- sample 61
     |- sample 62

**Comment by ssnn-airr** [comment]
BioSample mappings between NCBI and AIRR:

https://github.com/airr-community/airr-standards/blob/master/NCBI_implementation/mapping_MiAIRR_BioSample.tsv

**Comment by martinjoconnor** [comment]
Email from Suzanna:

```
I confirm the template for submission to SRA uses the field 'sample_name' to link the biosample records to their sequencing records in the SRA metadata file.

So, each biosample, needs this SRA fields (this is NCBI, not AIRR):
- sample_name
- bioproject_accession
- title
- library_ID
- design_description
- library_strategy
- library_source
- library_selection
- library_layout
- platform
- instrument_model
- filetype
- filename1
- filename2

I don't know the architecture CEDAR uses, how the templates work... but I see at least to options:
- everytime you create a biosample, you create a nested SRA section
- you can create independently SRA sections, copying and editing the previous one, but somewhere you will need a validation step that makes sure you are matching all the sample_name correctly and have a perfect intersection between sample_name in the biosamples and in SRA.



--
Susanna Marquez
Department of Pathology
Yale School of Medicine
300 George Street, Suite 505
New Haven, CT 06511-6663
```

**Comment by willrett** [comment]
For now we are using the attribute-value field to capture the file names  and and we added the sample name to the SRA element.   This means our validation step should check that the sample names from the Sample  and SRA elements match up.    Longer term we will use nested elements  once they work well with spreadsheets.
