### ISSUE TITLE
isTabView needs buttons or something to allow the user to go to the previous or the next BioSample

### ISSUE THREAD

**Issue by ssnn-airr** [metadatacenter/cedar-project#690]
As a new user, I have been through a lot of click here and there, watching BioSamples appear and disappear, and thinking the system had deleted the information, until have figured there are 3 visualizations and one of them (isTabView) just shows the first BioSample.

isTabView needs buttons or something to allow the user to go to the previous or the next BioSample and needs to show the number of the current biosample as well as the number of available biosamples (see #688)

**Comment by willrett** [comment]
The tab view should show a pager which lets you pick a page, go back or forward one page, or go the the beginning or end.  Do you see the pager?

**Comment by ssnn-airr** [comment]
No, I don't see the pager

**Comment by graybeal** [comment]
I can confirm I noticed it missing very recently too. This and #688 will be very good to have if we can manage it.
