### ISSUE TITLE
BioProject information disappeared after trying to update a BioSample in spreadsheet view

### ISSUE THREAD

**Issue by ssnn-airr** [metadatacenter/cedar-project#691]
After I tried to update one field in the second BioSample in a bioproject, I am not sure what happened but I went from being in the cell I was editing to being in the BioProject section, in spreadsheet view mode, with an empty spreadsheet. But I can see the information is present in the JSON-LD string.

https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/6e69a794-8fe4-4b36-aa36-40e5122c4004?folderId=https:%2F%2Frepo.staging.metadatacenter.org%2Ffolders%2F34ca0f97-e28b-4f42-9a7a-55aa22e0bfef

**Comment by willrett** [comment]
Please share the resource so we can view it.

**Comment by ssnn-airr** [comment]
I have shared it with you and the development team

**Comment by willrett** [comment]
Please try sharing again and make sure you click the plus sign.

**Comment by ssnn-airr** [comment]
The sharing seems fine in the file. I am going to share also the parent folder, in case this is the problem


--
Susanna Marquez
Department of Pathology
Yale School of Medicine
300 George Street, Suite 505
New Haven, CT 06511-6663


________________________________

**Comment by graybeal** [comment]
It's an instance, so the parent _template_ needs to be shared also (presumably it's the one that's already shared, but just to check).

**Comment by ssnn-airr** [comment]
I see. Now I am sharing everything: the metadata, the template and the shared folder.

**Comment by willrett** [comment]
Please clear your browser cache and let me know if you have any further problems.
