### ISSUE TITLE
Can't fill field "Number of Cells per Sequencing Reaction*"

### ISSUE THREAD

**Issue by ssnn-airr** [metadatacenter/cedar-project#693]
I am trying to write 'NA' in Biosample > Processing > Number of Cells per Sequencing Reaction*, but after I click OK, the NA is deleted.
https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/6e69a794-8fe4-4b36-aa36-40e5122c4004?folderId=https:%2F%2Frepo.staging.metadatacenter.org%2Ffolders%2F34ca0f97-e28b-4f42-9a7a-55aa22e0bfef

Also, I see in the JSON this:
 "Number of Cells per Sequencing Reaction": {
        "@type": "http://data.bioontology.org/ontologies/BAO/classes/http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0000572"
      }

What is this field expecting? I thought this should be a number but it seems it is linked to an ontology?

**Comment by ssnn-airr** [comment]
I tried with a number and that dind't work.
There are other required fields where I could put NA. I think that it would be consistent to leave it required, but allow to use NA as a valid value.

**Comment by willrett** [comment]
Actually it is expecting a URI.  The placeholder text says "enter URI".  It wants a URI because the instance type is set in the template.  Is this correct?



Debra Willrett

Senior Software Developer, Research

Stanford Center for Biomedical Research | Stanford University

Medical School Office Building | 1265 Welch Drive, X207

Stanford, CA 94305

http://metadatacenter.org

________________________________

**Comment by ssnn-airr** [comment]
Yes, that's why I thought the JSON pointing to and ontology was strange. The JSON for required fields for which I can use NA doesn't seem to have a type:

 "Relation Type": {
        "@value": "NA"
      },

      "Age Event": {
        "@value": "NA"
      },

**Comment by willrett** [comment]
We will patch the template to remove the instance type.  Then any text string will be allowed.



Debra Willrett

Senior Software Developer, Research

Stanford Center for Biomedical Research | Stanford University

Medical School Office Building | 1265 Welch Drive, X207

Stanford, CA 94305

http://metadatacenter.org

________________________________

**Comment by marcosmro** [comment]
We've patched the template.
