### ISSUE TITLE
template instance URI refers both to the template instance and to the object the template instance is describing

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#695]
I made a simple template in CEDAR with 2 fields (copyright date and related Work), and I assigned a class (bf:Work) to the template as a whole (using "class picker" at upper right of template designer window).

When I populate the template I get statements about the creation of the instance AND about the bf:Work that the template instance is describing, which doesn't make sense. (I'm using the "view as RDF" feature to look at the data created by CEDAR when I fill in the template)

Statements describing the template instance:

<https://repo.metadatacenter.org/template-instances/52d9a7dd-f94f-4bd4-b6f2-61e5ad323a30> <http://open-services.net/ns/core#modifiedBy> <https://metadatacenter.org/users/3e830739-eaa6-4cc2-8374-e7b72dc01f00> .
<https://repo.metadatacenter.org/template-instances/52d9a7dd-f94f-4bd4-b6f2-61e5ad323a30> <http://purl.org/pav/createdBy> <https://metadatacenter.org/users/3e830739-eaa6-4cc2-8374-e7b72dc01f00> .

Statements that are supposed to be about the thing that this template is describing (an instance of bf:Work)

<https://repo.metadatacenter.org/template-instances/52d9a7dd-f94f-4bd4-b6f2-61e5ad323a30> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.bioontology.org/ontologies/BIBFRAME/classes/http%3A%2F%2Fid.loc.gov%2Fontologies%2Fbibframe%2FWork> .

<https://repo.metadatacenter.org/template-instances/52d9a7dd-f94f-4bd4-b6f2-61e5ad323a30> <http://id.loc.gov/ontologies/bibframe/copyrightDate> "1986" .

<https://repo.metadatacenter.org/template-instances/52d9a7dd-f94f-4bd4-b6f2-61e5ad323a30> <http://id.loc.gov/ontologies/bibframe/relatedTo> "http://id.loc.gov/uri_for_related_work_just_pretend" .

The URI <https://repo.metadatacenter.org/template-instances/52d9a7dd-f94f-4bd4-b6f2-61e5ad323a30>  seems to refer to BOTH the populated instance of the template AND for the thing we're trying to describe.

If the URI  <https://repo.metadatacenter.org/template-instances/52d9a7dd-f94f-4bd4-b6f2-61e5ad323a30> (call it "blob" for shorthand) identifies the populated template instance then it makes sense to say 
"blob" was last updated Jan 26
"blob" was created by Michelle
but it doesn't make sense to say "blob" has copyrightdate 1986

on the other hand if "blob" is identifying the Work, then it makes sense to say
"blob" has copyright date 1986
but it doesn't make sense to say
"blob" was updated on Jan 26.

Now if you take those 2 fields I had in my template, and instead put those in an Element, then put the Element in a template (and don't assign a class to the template), you do NOT have the same problem--instead the URI for the populated element (repo.metadatacenter.org/template-element-instances/...) represents "thing" that the Element is about, and the URI for the populated template (repo.metadatacenter.org/template-instances/..._) represents the populated template itself.

I will attach the RDF from each template, and have shared the templates and metadata instances with CEDAR Dev Team

Template 1 in CEDAR, example of what I think does not work properly: "Work (for RDF test)"
Metadata instance in CEDAR: "Work metadata 1"
Attached file of RDF from filling out this template: "CEDAR_RDF.txt"

Template 2 in CEDAR, using element within a template: "Template with Work Element"
Metadata instance in CEDAR: "Work metadata 2"
Attached file of RDF from filling out this template: "CEDAR_RDF_as_element.txt"

**Comment by michelleif** [comment]
[CEDAR_RDF.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46cbb1be02b0bc9babcffd0fe64de29b234324676b5ee17e2686b578ee127a580d0d4ef842595c44fcfd882caee06f62964e49bc8f3900299f7744eeaa880dbe09b0218e4e8cb0b48b4cc3e83826e499c2.txt)
[CEDAR_RDF_as_element.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46cbb1be02b0bc9babcf8042b762f5982c4b227d3d46ef696097ec22ba416f43554d4baa125e5f45fca88079f4b668738b5f0bedd56c587c906e03b0aac04ee155e57dd205d0f4ae805ec1e13724e28a8649361f051b89fb5a3cb2d4.txt)

**Comment by graybeal** [comment]
Per discussions with Martin:
In the model currently in use, CEDAR describes metadata about the instance, not about the original object itself. This is useful in many CEDAR contexts where much of the metadata is not actually about the original entity, but about (for example) the person filling out the form or submitting the metadata.

It would be possible to implement this capability by allowing the user to specify, for any template or element in an instance, the object that the template or element it is describing, e.g., 
  <element3_in_instance_ID>  <is_representation_of> <authority_id_for_entity>.
CEDAR could then rewrite the RDF (when requested) to make the original object the subject of the relevant triples.

**Comment by marcosmro** [comment]
That's a nice solution. The Semanticscience Integrated Ontology (SIO) contains a "describes" property that could be a good fit for that purpose (http://semanticscience.org/resource/SIO_000563).

**Comment by martinjoconnor** [comment]
Task that could address this here: https://github.com/metadatacenter/cedar-project/issues/783
