### ISSUE TITLE
Typo. Starin should be Strain, in BioSample > Subject

### ISSUE THREAD

**Issue by ssnn-airr** [metadatacenter/cedar-project#697]
In the MiAIRR template, in BioSample > Subject section, the field name 'Starin Name' should be 'Strain Name'. The typo was in the old template, I didn't notice until now.
This is the link to the new template.
https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/824a5e71-641b-44cd-8bc9-37cf47449676?folderId=https:%2F%2Frepo.staging.metadatacenter.org%2Ffolders%2F34ca0f97-e28b-4f42-9a7a-55aa22e0bfef

**Comment by graybeal** [comment]
I have some other suggestions for the template (wording only) that I'm working on today, so maybe we can hold off on making this change until I can offer those too?

**Comment by ssnn-airr** [comment]
Sure
