### ISSUE TITLE
'Cell Subset' should expect a 'cellSubset', not a 'cellType'

### ISSUE THREAD

**Issue by ssnn-airr** [metadatacenter/cedar-project#699]
I am trying to fill the field 'BioSample > Processing > Cell Subset' with the value 'B cell' and it is not accepted. In the old template it did work. The new template is expecting a 'cellType', but it should be expecting a 'cellSubset', like the old one.

This is the current value in the JSON of the modified template:
`"Cell Subset": "https://schema.staging.metadatacenter.net/properties/cellType"`

In the old template it is:
`"Cell Subset": "https://schema.staging.metadatacenter.net/properties/cellSubset"`

https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/824a5e71-641b-44cd-8bc9-37cf47449676?folderId=https:%2F%2Frepo.staging.metadatacenter.org%2Ffolders%2F34ca0f97-e28b-4f42-9a7a-55aa22e0bfef

**Comment by marcosmro** [comment]
It seems a BioPortal issue. The BioPortal team are taking a look at it.

**Comment by marcosmro** [comment]
This issue is fixed. 'B cell' should be available now. It was a BioPortal caching issue.
