### ISSUE TITLE
Consolidate documentation links

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-project#7]
Remove documentation from the README.md files in the following repos:
cedar-template-server
cedar-template-editor
cedar-terminology-server

Just point to the main documentation page:
https://github.com/metadatacenter/cedar-docs/wiki
If relevant information is present on the mentioned pages, integrate those into the main documentation

**Comment by martinjoconnor** [comment]
Resolved by 0.8 document re-org.
