### ISSUE TITLE
error accessing document

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#700]
I was sent a properly shared link but could not open it.  I got a 400 error and No 'Access-Control-Allow-Origin from staging.

**Comment by willrett** [comment]
![Screen Shot 2018-03-08 at 9.07.28 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56c62b4a6023091300bfd113/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454fb6b7191a371f1122c4f5d575edd3c4a4356bcbbd671f3e57862804e0eeb826b5f75c66c18feea824bbc00b9208b4b84b1b4dc1fd2f42f67b6d5db1063474f4dcbed5727a19041c95df44be44f5ca61a356aee702431.png)

**Comment by martinjoconnor** [comment]
Have not seen since so closing.
