### ISSUE TITLE
can't handle characters like umlauts

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#701]
Christian (?) reports that his name has an umlaut, but it couldn't be successfully entered. Also, metadata in the field below (entered by Susanna) has obscure characters that are showing badly. This could be a data entry/translation error, but I think the view is not showing right.

The field is in https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/d49d3530-c075-4883-bf54-d500363475b8?folderId=https:%2F%2Frepo.staging.metadatacenter.org%2Ffolders%2Fade1b1e6-dbdc-421b-be22-cecb633546fb

Look under BioSample[1], Under Processing, field is Tissue Processing. I'll get the original data from Susanna.

**Comment by graybeal** [comment]
Content as displayed, and in JSON-LD, is (in part)
```
d by Ficoll density gradient centrifugation (Lympholyte; Cedarlane Laboratories, SanBio B.V., Uden, The Netherlands). B cells were purified from the PBMC using negative magnetic selection (STEMCELL Technologies SARL, Grenoble, France) according to the manufacturerÃ¢ÂÂs instructions. Purity of the isolated B cells was routinely Ã¢ÂÂ¥ 99.5% as determined by flow cytometry on a FACSAria II flow cytometer (BD Biosciences, Erembodegem, Belgium) following the staining described below. For the isolation of DN and IgD-CD27+ memory B cells, the enriched B cells were stained with anti-human CD27 allophycocyanin (APC, clone M-T271), IgD PE-CF594 (clone IA6-2) (both from BD Biosciences) and CD19 PE-Cy7 (clone HIB19; BioLegend, ImTec Diagnostics, Antwerp, Belgium) during 30 min at 4ÃÂ°C. At least 2 x 104 DN (IgD-CD27-) or class-switched memory (IgD-CD27+) B cells were then sorted on a FACSAria II flow cytometer (BD Biosciences) using single-color gating controls (Supplemental Fig. 1). Sorted cells were pelleted or suspended in RNAlaterÃÂ® Stabilization Solution (ThermoFisher Scientific, Erembodegem, Belgium) before storage at -80ÃÂ°C
```

**Comment by graybeal** [comment]
I'm in a long thread with Susanna about the source of this data. More to come.

**Comment by graybeal** [comment]
sorry, the very first phrase was about Christian entering his name as a user name; I did not make that clear at all. But I think we may have a task on that also?

**Comment by graybeal** [comment]
Near as I could tell, that metadata (per Susanna) came from a long line of possibly-corrupting editors (MS Word on a PC, pasted in from some strange mainframe program, etc.). I'm OK with signing this off. I can talk to Christian about the fact that we are able to enter UTF-8 characters just fine.

**Comment by willrett** [comment]
cannot duplicate
