### ISSUE TITLE
Pasted date is off by one day in table view

### ISSUE THREAD

**Issue by ssnn-airr** [metadatacenter/cedar-project#706]
Date copied from a spreadsheet and pasted to the table view, is off by one day (see screen recording). Paste in the other view works fine, and has different format (see first row in the image).
[date-changes.zip](https://github.com/metadatacenter/cedar-project/files/1803928/date-changes.zip)
![date-changes](https://user-images.githubusercontent.com/20683719/37301198-48ac7096-25fe-11e8-9c60-2ffbcddff2ec.png)

**Comment by willrett** [comment]
fixed
