### ISSUE TITLE
Difficulty with entering data in spreadsheet view

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-project#711]
Sometimes for a repeating field, I can enter an value in the first row, but when I hit return nothing happens, and I have to click multiple times to get to another row. It doesn't always happen. But a common factor seems to be that if it's the FIRST field on a template, it doesn't work properly. There are also issues with entering metadata in spreadsheet mode when you have a repeating Element that has another repeating Element nested within it. I'd be happy to go through some examples in person to help you troubleshoot, because I can't pinpoint why the entry works smoothly sometimes and not others.

**Comment by graybeal** [comment]
Entering a repeating Element with another repeating Element nested within it is not supported in spreadsheet mode. (You can open the spreadsheet, but not edit that part of the data.) This needs to be warned about when the user attempts to do it.

**Comment by graybeal** [comment]
Many of the issues with entering spreadsheet values were related to entering controlled terms, which has been significantly improved recently. Please verify whether this behavior is still happening, if you have access to the original example.

**Comment by michelleif** [comment]
I can't reproduce the problems (the ones unrelated to nesting)

**Comment by graybeal** [comment]
yay, that's good news. For the nested elements, if it is more complicated than simply lack of support for unevenly nested elements (spreadsheet mode only works effectively if all the fields are at the top level), can I suggest opening up a new ticket that includes a screenshot or movie, so we can talk about the exact situation? Then we can sign off this ticket and reference the other issue more clearly.

**Comment by michelleif** [comment]
I think the issue was related to having a repeated field in an element, and then making that element repeatable. As you note above, that is not supported, so #796 should take care of warning user.

**Comment by graybeal** [comment]
closing this in favor of #796 for the nested elements warning.
