### ISSUE TITLE
Re-opening controlled-terms dialog loses context

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#718]
When you enter the Search dialog to find ontology terms, select the Show Details, scroll to end, close the dialog with the X, and re-open the Search dialog, it has lost track of what needs to be displayed. Scrolling 'up' (to previous content) reveals it is confused about saved settings and locations. (Probably need to clear the settings on close?) Screen capture in Box at https://stanfordmedicine.box.com/s/og5fypixzle8t9ap3bvsj0cf9xcyzbsn.

**Comment by willrett** [comment]
It needs scroll to be reset to top and details hidden on dialog open.

**Comment by willrett** [comment]
Branch feature/autopopulate-title-description is a major rework of the controlled-terms dialog and addresses this issue.
