### ISSUE TITLE
non-multiple element shows multi-icon

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#728]
<img width="1009" alt="screen shot 2018-04-28 at 10 56 28 pm" src="https://user-images.githubusercontent.com/1266896/39403725-91fd9190-4b37-11e8-9773-6a07feb7ff1c.png">
The first element in https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F3cedb8a7-fe33-469b-89bf-7ccd27512e57 is not set to multiple, but when you try entering something in the instance, you can see the icon that implies multiple copies are possible. (See image.)

**Comment by willrett** [comment]
I think this must have been fixed along the way somewhere.  I do not see it happening on any of the instances in the specified folder.
