### ISSUE TITLE
instance has recurring bad model icon

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#729]
The instance called "Hounds of love" at https://cedar.metadatacenter.org/instances/edit/https://repo.metadatacenter.org/template-instances/5c571fa8-c6e7-4bd3-8476-f72880106c74?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F84474818-442b-4d57-95a1-b2d990d7f567 shows a yellow triangle (bad model) when opened.

Saving the instance turns the icon into a green check mark.

But when you go back and re-open the instance, the yellow triangle is back.

**Comment by willrett** [comment]
I fixed the validation icon so it shows correctly.  The real problem is probably related to the dot in one of the field names, issue  #762.
