### ISSUE TITLE
Filter settings revert unexpectedly

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#737]
If I turn off a filter setting (e.g., Elements), then refresh my page; then turn on the Element filter (so I can see Elements), go into an Element, then back out of the Element—the filter setting has reverted to off, so I can't see the Elements any more.

**Comment by graybeal** [comment]
Thinking this was an access issue (because I just couldn't see the Elements), I got Atti to come help me, and we found the filter setting issue. He's going to confirm why he hasn't seen this on his browser, so I've assigned it to him for the moment.

**Comment by willrett** [comment]
fix: saving resource filtering in cedarUser
