### ISSUE TITLE
can't save template I copied

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#738]
When I try to save https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.org/templates/1b957b9d-46e6-4122-8572-fd71700ca74d?folderId=https:%2F%2Frepo.staging.metadatacenter.org%2Ffolders%2F4f2be12f-d096-4b45-8dc6-a7ec2e145f37 I get a fail.

I created this template by copying another one as cedar-admin, not that that explains anything.

echnical details of error
Status: 500, Internal Server Error
URL: https://resource.staging.metadatacenter.org/templates/https%3A%2F%2Frepo.staging.metadatacenter.org%2Ftemplates%2F1b957b9d-46e6-4122-8572-fd71700ca74d
Method: PUT

Message: id must not be null
Error key: 
Exception: id must not be null

Stack trace:

org.metadatacenter.server.search.elasticsearch.worker.ElasticsearchIndexingWorker -> addToIndex ( 68 )
org.metadatacenter.server.search.elasticsearch.service.ContentIndexingService -> indexNode ( 80 )
org.metadatacenter.server.search.elasticsearch.service.ContentIndexingService -> indexResource ( 44 )
org.metadatacenter.server.search.elasticsearch.service.ContentIndexingService -> updateResource ( 95 )
org.metadatacenter.cedar.resource.resources.AbstractResourceServerResource -> updateIndexResource ( 747 )
org.metadatacenter.cedar.resource.resources.AbstractResourceServerResource -> executeResourcePutByProxy ( 419 )
org.metadatacenter.cedar.resource.resources.AbstractResourceServerResource -> executeResourcePutByProxy ( 326 )
org.metadatacenter.cedar.resource.resources.TemplatesResource -> updateTemplate ( 145 )
jdk.internal.reflect.NativeMethodAccessorImpl -> invoke0 ( -2 )
jdk.internal.reflect.NativeMethodAccessorImpl -> invoke ( 62 )
jdk.internal.reflect.DelegatingMethodAccessorImpl -> invoke ( 43 )
java.lang.reflect.Method -> invoke ( 564 )
org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1 -> invoke ( 81 )
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1 -> run ( 144 )
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher -> invoke ( 161 )
org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker -> doDispatch ( 160 )
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher -> dispatch ( 99 )
org.glassfish.jersey.server.model.ResourceMethodInvoker -> invoke ( 389 )
org.glassfish.jersey.server.model.ResourceMethodInvoker -> apply ( 347 )
org.glassfish.jersey.server.model.ResourceMethodInvoker -> apply ( 102 )
org.glassfish.jersey.server.ServerRuntime$2 -> run ( 326 )
org.glassfish.jersey.internal.Errors$1 -> call ( 271 )
org.glassfish.jersey.internal.Errors$1 -> call ( 267 )
org.glassfish.jersey.internal.Errors -> process ( 315 )
org.glassfish.jersey.internal.Errors -> process ( 297 )
org.glassfish.jersey.internal.Errors -> process ( 267 )
org.glassfish.jersey.process.internal.RequestScope -> runInScope ( 317 )
org.glassfish.jersey.server.ServerRuntime -> process ( 305 )
org.glassfish.jersey.server.ApplicationHandler -> handle ( 1154 )
org.glassfish.jersey.servlet.WebComponent -> serviceImpl ( 473 )
org.glassfish.jersey.servlet.WebComponent -> service ( 427 )
org.glassfish.jersey.servlet.ServletContainer -> service ( 388 )
org.glassfish.jersey.servlet.ServletContainer -> service ( 341 )
org.glassfish.jersey.servlet.ServletContainer -> service ( 228 )
io.dropwizard.jetty.NonblockingServletHolder -> handle ( 49 )
org.eclipse.jetty.servlet.ServletHandler$CachedChain -> doFilter ( 1650 )
io.dropwizard.servlets.ThreadNameFilter -> doFilter ( 34 )
org.eclipse.jetty.servlet.ServletHandler$CachedChain -> doFilter ( 1637 )
io.dropwizard.jersey.filter.AllowedMethodsFilter -> handle ( 45 )
io.dropwizard.jersey.filter.AllowedMethodsFilter -> doFilter ( 39 )
org.eclipse.jetty.servlet.ServletHandler$CachedChain -> doFilter ( 1637 )
org.eclipse.jetty.servlets.CrossOriginFilter -> handle ( 308 )
org.eclipse.jetty.servlets.CrossOriginFilter -> doFilter ( 262 )
org.eclipse.jetty.servlet.ServletHandler$CachedChain -> doFilter ( 1637 )
org.eclipse.jetty.servlet.ServletHandler -> doHandle ( 533 )
org.eclipse.jetty.server.handler.ScopedHandler -> nextHandle ( 188 )
org.eclipse.jetty.server.handler.ContextHandler -> doHandle ( 1253 )
org.eclipse.jetty.server.handler.ScopedHandler -> nextScope ( 168 )
org.eclipse.jetty.servlet.ServletHandler -> doScope ( 473 )
org.eclipse.jetty.server.handler.ScopedHandler -> nextScope ( 166 )
org.eclipse.jetty.server.handler.ContextHandler -> doScope ( 1155 )
org.eclipse.jetty.server.handler.ScopedHandler -> handle ( 141 )
org.eclipse.jetty.server.handler.HandlerWrapper -> handle ( 132 )
com.codahale.metrics.jetty9.InstrumentedHandler -> handle ( 241 )
io.dropwizard.jetty.RoutingHandler -> handle ( 52 )
org.eclipse.jetty.server.handler.gzip.GzipHandler -> handle ( 455 )
io.dropwizard.jetty.BiDiGzipHandler -> handle ( 68 )
org.eclipse.jetty.server.handler.RequestLogHandler -> handle ( 56 )
org.eclipse.jetty.server.handler.StatisticsHandler -> handle ( 169 )
org.eclipse.jetty.server.handler.HandlerWrapper -> handle ( 132 )
org.eclipse.jetty.server.Server -> handle ( 561 )
org.eclipse.jetty.server.HttpChannel -> handle ( 334 )
org.eclipse.jetty.server.HttpConnection -> onFillable ( 251 )
org.eclipse.jetty.io.AbstractConnection$ReadCallback -> succeeded ( 279 )
org.eclipse.jetty.io.FillInterest -> fillable ( 104 )
org.eclipse.jetty.io.ChannelEndPoint$2 -> run ( 124 )
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill -> doProduce ( 247 )
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill -> produce ( 140 )
org.eclipse.jetty.util.thread.strategy.EatWhatYouKill -> run ( 131 )
org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread -> run ( 243 )
org.eclipse.jetty.util.thread.QueuedThreadPool -> runJob ( 679 )
org.eclipse.jetty.util.thread.QueuedThreadPool$2 -> run ( 597 )
java.lang.Thread -> run ( 844 )

OK

**Comment by graybeal** [comment]
Today I had the same kind of problem, this time after moving and renaming a copied template (as myself). see #739.

**Comment by martinjoconnor** [comment]
Works now in latest code.
