### ISSUE TITLE
Prototype Questioning Authority interface

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#749]
The text below was the original definition that came out of an early task definition from LD4P. A more elegant presentation of this use case is at https://www.youtube.com/watch?v=8yHTbaQHDgI. 

Work Area 2: External authority search and reference
2.2 Prototype a Questioning Authority interface within CEDAR to find and use entities from external authorities. (Figures 2.2a and 2.2b)

Figure 2.2a: Existing lookups are possible only with vocabulary resources in BioPortal; LC Names, for example, is not supported.
<img width="840" alt="screen shot 2018-05-08 at 6 38 03 pm" src="https://user-images.githubusercontent.com/1266896/39791161-fe393fe4-52ee-11e8-87e9-9c608136c15d.png">

Figure 2.2b: New lookup feature uses Questioning Authority (QA) services to allow cataloger to look up and reference entities in any authority source supported by QA.
<img width="841" alt="screen shot 2018-05-08 at 6 38 11 pm" src="https://user-images.githubusercontent.com/1266896/39791167-0359ff54-52ef-11e8-974d-e23326f6d18a.png">

**Comment by graybeal** [comment]
I have been consulting with the QA development teams and hope to define this task in terms of a well-defined, consistent, and stable interface. More details to be provided.

**Comment by graybeal** [comment]
Reference https://github.com/LD4P/requirements/issues/17

**Comment by graybeal** [comment]
This task may be of interest to NLM for their LD4P work.

**Comment by martinjoconnor** [comment]
No longer relevant.
