### ISSUE TITLE
scala.version is hardcoded in pom.xml files

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#75]
The main pom.xml files for all our server projects contain the following xml:

``` xml
<properties>
    <!-- Do Not Remove This! We need it in Pom.scala -->
    <scala.version>2.11.5</scala.version>
</properties>
```

The scala version should be read from the parent project instead of being hardcoded.

**Comment by martinjoconnor** [comment]
Move to Dropwizard removed all Scala dependencies.
