### ISSUE TITLE
Optimize workspace for keyboard

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#751]
Copied from #708 : 
in the workspace, offer keyboard shortcuts for common tasks like populate a template.

Other shortcuts: opening folder, navigate up to parent folder, go to home directory, go to My Shared view, search. 

Adding also:
In the workspace, allow navigation using arrow keys (to move around among templates, instances, etc.)

**Comment by martinjoconnor** [comment]
Merged into https://github.com/metadatacenter/cedar-project/issues/708
