### ISSUE TITLE
Simple provenance and versioning

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#753]
Complete basic provenance and versioning capabilities suitable for the library community. 
"3.1.2 Simple provenance and versioning, to know how templates and metadata have been derived, and when metadata (Works, Instances, and Items) have been updated"

Likely key tasks are providing attributes on templates and instances, indicating if an instance was copied from another, and causing 'Publish' to modify the version of the published entity. This list may be modified upon consultation with the library team.

This task is a tracking task, reflecting the above combination of work items and library review; it is not the primary definition of the corresponding work.

**Comment by martinjoconnor** [comment]
2.0.0 versioning features effectively address these.
