### ISSUE TITLE
Support user-defined mapping for submission

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#757]
Require the user to supply a mapping table as in the link below.  Having the mapping allows   auto-generation of the submission xml for any template on the fly.  This also requires a physical layer for each repository which  structures the the xml and manages the communication.

https://github.com/airr-community/airr-standards/blob/master/NCBI_implementation/mapping_MiAIRR_SRA.tsv

**Comment by martinjoconnor** [comment]
Have written an R01 describing some of the requirements of this task. See text for ideas.

**Comment by martinjoconnor** [comment]
Will be tackled by #616
