### ISSUE TITLE
Fallback location for new instances

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#763]
When a user starts populating a new instance, the save will fail if the user is in a read-only directory. Instead, if directory is read-protected at save time, save to the user's workspace, and put up a warning message saying "Couldn't save to current location. Saved to your workspace."  And if straightforward, a button to take the user to the directory (his or her workspace) where the item is, ideally with the item selected. (See Google image for example.)

This is needed for the production release of the CAIRR template.

![screen shot 2018-05-18 at 10 01 05 am](https://user-images.githubusercontent.com/1266896/40262862-3336d57a-5ac0-11e8-859a-7550175f6f73.png)

**Comment by martinjoconnor** [comment]
We agreed on three things that will provide an initial solution here:

(1) Currently, when we send an edit link for a template without a folder ID we do not correctly default to the user's home folder. We will fix that.

(2) Currently, when we send an edit link for a template with a folder ID for which the user does not have write permission we should default to the user's home folder.

(3) In both cases we need some way to indicate after a user presses save in the instance that the instance has been saved to the user's home folder with perhaps a link to go to that resource.

**Comment by graybeal** [comment]
Interesting fact, possibly related to changes in progress in which case ignore this information.

When you enter a URL like this in the browser now:
 https://cedar.metadatacenter.org/instances/create/https://repo.metadatacenter.org/templates/62c8b5f2-7dc9-4fff-9008-07c95a746411
it creates the metadata editing screen, but when you try to save it there is a very nice message "Folder not found. Please use the UI elements to navigate to an existing folder." 

Unfortunately that's a useless instruction because if you go back to navigate to a folder you can't go forward to where you were trying to save. (But at least there's already a dialog box in the right place in the code!)

**Comment by willrett** [comment]
We now default to the home folder if there is no folder specified or there is a write access error, and we show a warning on the write access error case.
