### ISSUE TITLE
Move CAIRR content to production

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#767]
Copy latest CAIRR templates, elements, and instances to production CEDAR system. Also copy Susanna's template and any instances developed from it.

Rename the template to delete the 'RC2' string.

Make enclosing templates and elements readable by everyone, writable only by CEDAR team. 

Don't delete original artifacts on staging, they can be deleted once we are sure things are working on production.

Depends on metadatacenter/cedar-submission-server#23

**Comment by graybeal** [comment]
* The two instances Susanna and Hailong created, both for future reference (so, not as urgent)
  * The instances are
    * Susanna's instance (https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/c23aacf3-630f-4e1e-b7b4-4d1d67d88e1c) 
    * Hailong's instance (https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/c797b52d-6940-4e0f-9653-6b7741bd19d6)
  * Unfortunately both Susanna and Hailong's instances seem to be based on an old template.
    * That template is the source of Susanna's existing submission in NCBI 
    * The easiest and best thing is to bring that template into the new system also, (https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.org/templates/ade1336d-a292-49f8-8fb9-d62c11997820)
    * Rename it to MiAIRR Original (Deprecated)
    * I will defer this to another task so that if it is at all hard, it can be deferred
Ah, to document the things to move here. 

Templates:
* MiAIRR RC2—please rename to MiAIRR (https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.org/templates/0e8d261c-b1ce-4e42-b043-845a15084a33)
* Elements in MiAIRR RC2 folder (https://cedar.staging.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.staging.metadatacenter.org%2Ffolders%2F62df85e3-3000-414d-a968-93051085315a)

Question about the above—didn't you just change the element/template to pull the new definition for organism? Neither is showing a new timestamp.

Instances:
* The test instance that you created based on Susanna's data
* The two instances Susanna and Hailong created, both for future reference (so, not as urgent)
  * The instances are
    * Susanna's instance (https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/c23aacf3-630f-4e1e-b7b4-4d1d67d88e1c) 
    * Hailong's instance (https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/c797b52d-6940-4e0f-9653-6b7741bd19d6)
  * Unfortunately both Susanna and Hailong's instances seem to be based on an old template.
    * That template is the source of Susanna's existing submission in NCBI 
    * The easiest and best thing is to bring that template into the new system also, (https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.org/templates/ade1336d-a292-49f8-8fb9-d62c11997820)
    * Rename it to MiAIRR Original (Deprecated)
    * I will defer this to another task so that if it is at all hard, it can be deferred

**Comment by marcosmro** [comment]
Done. Here is the link to the MiAIRR folder in production:
https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F4e5ce935-03ea-401a-804c-c38160c560f2

**Comment by marcosmro** [comment]
Regarding your question: "didn't you just change the element/template to pull the new definition for organism?". In the case of the template, I updated it directly in MongoDB so the timestamp was not modified. Regarding the element, I updated it using the UI earlier today, so the timestamp is updated in that case.
