### ISSUE TITLE
Track submission ability by template

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#769]
RIght now CEDAR determines submission privileges based on user ID. Instead, it should determine this based on the template type; only metadata from templates of approved types can be submitted to a repository. 

Will need a way to manage which templates can be submitted to which repositories.

Consensus of those at meeting was that the template itself should not contain this information, but that it should be in some independent resource (a separate database).

Requires https://github.com/metadatacenter/cedar-resource-server/issues/40

**Comment by martinjoconnor** [comment]
We have decided to remove submissions permission entirely. Instead if a user has access to a template that is submittable they can attempt to submit instances. (NCBI, for example, do quite a bit of validation on submissions so the opportunity for CEDAR users to generate garbage submissions is very limited.)

We now plan to store the fact that a template is submittable by storing this information in a submission server-managed database. All calls to the resource server to retrieve an instance will now return extra information obtained from the submission server indicating whether an instance is submittable (based on its template being so)

**Comment by martinjoconnor** [comment]
For the moment we will do a short term fix that will use the isBasedOn field returned for instances (which indicates the template used to created them) to determine if an instance is submittable. 

Requires https://github.com/metadatacenter/cedar-resource-server/issues/40

**Comment by martinjoconnor** [comment]
Code completed. Awaiting testing.
