### ISSUE TITLE
Slow return of content of folders with large number of resources

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#773]
The directory search takes over one second when there are lots of resources.  For example, the CDE directory has over 40,000 resources and the search takes over one second to return

**Comment by martinjoconnor** [comment]
This may be helped by the new Bolt work (https://github.com/metadatacenter/cedar-workspace-server/issues/3).

**Comment by martinjoconnor** [comment]
Another short term option would be to divide CDEs into subfolders based on some CDE characteristic (e.g., datatype). Putting 40k resources into one folder is probably not  a great idea in general (though we should still handle it well).

**Comment by martinjoconnor** [comment]
Moving to 0.3 milestone since Atti is away.

**Comment by martinjoconnor** [comment]
This has been addressed by recent 2.3 performance work.
