### ISSUE TITLE
Make  published first class fields non editable

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#779]
First class fields that are published (with bibo:status of bibo:published) should not be editable in Template Designer.

Particularly relevant for CDEs.

**Comment by willrett** [comment]
What does non-editable mean?  Can you edit the title and description?  Can you make it multiple, required, hidden, or have suggestions?

**Comment by martinjoconnor** [comment]
Title and description are part of the CDE so should not be editable. 

The other options are not part of it so likely should.

There may be deeper questions here in future. For example, some CDEs have multiple display  options I think.

**Comment by willrett** [comment]
Ok, view but not edit control term values for published fields.
