### ISSUE TITLE
Reauthorization error on timeout

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#781]
On authorization timeout, server returns error rather than reauthorizing user.

**Comment by willrett** [comment]
![screen shot 2018-05-17 at 1 45 59 pm](https://user-images.githubusercontent.com/4739879/40340981-3e84b612-5d37-11e8-9695-c7a78aed0382.png)

**Comment by martinjoconnor** [comment]
Seems to happen only locally.
