### ISSUE TITLE
Improve date parsing in date field

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#784]
When you enter a two digit month starting with a zero, the date becomes the prior day, e.g. 2018-05-22 becomes 2018-5-21.

Also, the date should always be displayed as a two digit month, not one digit, e.g. 2018-05-22 rather than 2018-5-22.

Third, add the date picker again.

Fourth, look into using a iso8601 javascript library for date parsing.

**Comment by graybeal** [comment]
Note comments in https://github.com/LD4P/requirements/issues/59. (Also https://github.com/LD4P/requirements/issues/87 and https://github.com/LD4P/requirements/issues/161, but I think those are addressed by the above.)

**Comment by graybeal** [comment]
There are also (somewhat ambiguous) suggestions in https://github.com/LD4P/requirements/issues/59.

**Comment by graybeal** [comment]
Reference/be aware of CEDAR issues #289 and #745.

**Comment by martinjoconnor** [comment]
Need to fix this for the AIRR template release.
