### ISSUE TITLE
Wrong element gets deleted

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#791]
In a template like https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/c04296b6-a045-4743-89e3-b0b2c67585f3?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2Fde5ac011-9f99-4fb6-905c-e22559806243, I added a new DO Funding element, dragged it up above the old one, and modified the name of the field.

Then I clicked on the box to delete the old Funding element. But the element that went away was the new funding element.

The next time I selected the old funding element, before I clicked on its delete icon. But still the new funding element went away.

Movies of this behavior, which seems to be repeatable, are at https://stanfordmedicine.app.box.com/folder/42677472044, titled DeletingWrongElement1.mov and DeletingWrongElement2.mov.

**Comment by willrett** [comment]
fixed
