### ISSUE TITLE
Multi-select looks like MULTIPLE

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#792]
When you create a multi-select like the one shown, in the metadata instance it appears that you can navigate among multiple entries. But you can't, there is only one entry.

![screen shot 2018-06-06 at 7 35 57 pm](https://user-images.githubusercontent.com/1266896/41075373-38e254b2-69c1-11e8-9b53-f74b9c21c454.png)

<img width="792" alt="screen shot 2018-06-06 at 6 48 57 pm" src="https://user-images.githubusercontent.com/1266896/41075374-39072c1a-69c1-11e8-8ded-f9de0026375d.png">

**Comment by willrett** [comment]
It means you can select multiple answers in your entry, which is what you are showing in the second screen shot.

**Comment by graybeal** [comment]
I may not have been clear. There are arrows in the second screen shot. Those arrows serve no purpose, as no navigation is possible. So they should not appear.

**Comment by willrett** [comment]
fixed
