### ISSUE TITLE
em-dash in tip not represented

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#793]
An em-dash ("—") in the original text of a description is morphed into something uglier in the actual tip. See image.  To make an em-dash, hold down option-shift-hyphen.

<img width="378" alt="screen shot 2018-06-07 at 2 40 05 pm" src="https://user-images.githubusercontent.com/1266896/41128459-1124efd2-6a63-11e8-82b3-38faa47f075d.png">

Template is https://cedar.staging.metadatacenter.org/instances/create/https://repo.staging.metadatacenter.org/templates/0e8d261c-b1ce-4e42-b043-845a15084a33?folderId=https:%2F%2Frepo.staging.metadatacenter.org%2Ffolders%2F4f2be12f-d096-4b45-8dc6-a7ec2e145f37

**Comment by willrett** [comment]
fixed
