### ISSUE TITLE
icons not centered

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#795]
At most resolutions, the icons are not centered in their circles. Taking a picture at 100% resolution and then blowing up that picture, you can see (and measure on screen) that the top of each internal icon is closer to the top of the circle than the bottom of the icon is to the bottom of the circle. And similarly, the left side of the icon is a little closer to the left side of the circle than the right side is to the right side of the circle.

When you change resolutions of the screen, the differences are often more obvious, and in once case the inner icon doesn't fit in its space any more, so it isn't shown.

There's a movie of this in the Box Technical Resources/Troubleshooting directory.

![Screen Shot 2018-06-08 at 4.04.33 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56faf7f8d928b91300aff9d1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454fb6b7191a37cf1122f4f5c5c5ecc3c4a4356bcbbd671f3e57862804e0eeb826b5f75c66c18feea824bbc00b9208b4b84b1b4dc1fd2f42f67b6d5db1063474f4dcbed5727a19041c95df443e5445ca117336ae3702431.png)

**Comment by willrett** [comment]
The icons have been updated since this issue was submitted and are on 1.8.3.  Please check the new icons and let me know if you still feel there is a problem.
