### ISSUE TITLE
Create temporary BioPortal ontologies for AIRR branches

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#797]
Often clicking on controlled term drop-downs  produces unexpected delays. I think these are real bioportal delays, not CEDAR delays or bugs. 

This was observed particularly on a drop-down for organism (in NCIT) or maybe disease (in DOID).

**Comment by graybeal** [comment]
see also #711

**Comment by graybeal** [comment]
also observed by AIRR tester IT. Note was accessing Organism.

![Screen Shot 2018-06-10 at 9.47.16 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56faf7f8d928b91300aff9d1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f36b7191a371f1162c4f5e595ecc3c4a4356bcbbd671f3e57862804e0eeb826b5f75c66c18feea824bbc00b9208b4b84b1b4dc1fd2f42f67b6d5db1063474f4dcbed5727a19141c95df443e74457a1123062e6752431.png)

**Comment by graybeal** [comment]
Also observed by AIRR tester JB, on both field and spreadsheet views. Note both were Organism.

![CEDAR_screen9618_808.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56faf7f8d928b91300aff9d1/125516c66e82c728ace21e0d46cbb1be02b0bcba8cfbba46aa04a6c571797f237146ef696097ec22ba416f43554d4baa125e5f45fca88079f4b668738b5f0bedd56c587c906e03b0aac04ee155e57dd205d0f4ae805ec2e93724e2898749371c031a88fe5a32b2d4.png)
![CEDARspreadsheet_screen9618_808.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56faf7f8d928b91300aff9d1/125516c66e82c728ace21e0d46cbb1be02b090b99decbe47b755f5913d7934703b01a62529d3b270801a2b594d435cec03070511afbd9b21b4b33a238c5c0aed80640d26c66912adbb821fbb00bd28dd1c97aaaec81d9ebc6278bec1da0d2c1417198ff55c30a2914dc15af049e64b52a5017b.png)

**Comment by graybeal** [comment]
Re AIRR tester JB, subsequent email and my response:

```
OK, this is much appreciated information (if somewhat disappointing). We have been aware of similar issues but after some improvements were seeing much improved results as of late. 

Just because I know it can help if you know how the system works, let me offer some information. There are two challenges affecting what you see. First, when there are tens of thousands of terms or more (such as organisms), it is not straightforward to show them all in a drop-down menu, and the BioPortal widget doesn't try. 

Second, we have not optimized BIoPortal for searching within large ontology branches. So when it is trying to auto-complete, the first search can take some seconds, especially if BioPortal is at all busy. Such searches may be cached, which can make subsequent tries work very quickly.

We will huddle to consider what we can do in these cases. Any further feedback will continue to be welcome.
```

**Comment by graybeal** [comment]
We may be able to work around this by creating view of the appropriate BioPortal ontologies. Will try to test tomorrow.

**Comment by graybeal** [comment]
we have been working on creating a subset of the Organism ontology. So far it has been really hard.

**Comment by graybeal** [comment]
Jennifer created NCIT-ORG, which is private in BioPortal but now accessible to CEDAR and is working. I replaced the NCIT branch in CCP template with NCIT-ORG ontology. This appears to produce the desired results.

**Comment by graybeal** [comment]
Unfortunately, the AIRR template is using another ontology for Organism and is still having bad effects on BioPortal.

**Comment by martinjoconnor** [comment]
Marcos is going to use ROBOT (http://robot.obolibrary.org/) to extract the requisite branches and create private CEDAR-visible ontologies in BioPortal.

**Comment by marcosmro** [comment]
@graybeal I talked to Jennifer yesterday and she sent me some instructions on how to use ROBOT (http://robot.obolibrary.org/) to extract ontology branches. I will use ROBOT to extract the branches and upload them to BioPortal as independent (and private) ontologies

**Comment by martinjoconnor** [comment]
Great. Will it be ingested/indexed overnight? Can be ask the BioPortal team to force an ingest if not?

**Comment by graybeal** [comment]
If it parses successfully it should be ready to go reasonably quickly, within an hour or two at most. (I think only the Resource Index takes longer.)

**Comment by marcosmro** [comment]
It is already available in BP, it can be seen from CEDAR and it looks good. I will update the template to use it.

**Comment by marcosmro** [comment]
Done. I have updated the Organism field to point to the NCBITAXON-GNA ontology and seems to work fine.
