### ISSUE TITLE
Consistent scheme for all CEDAR subdomains

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#80]
From #76, this is the part about a general cedar pattern:

The goal is to have

```
{auth, cedar, repo, ...}.{cedar-purpose-domain-name}.stanford.edu
```

as a general pattern for the 'cedar-internal' names for machines.

This will give us a consistent scheme for managing our certificates without thinking about aliases. The only aliases cedar team wants to work with are to go from metadatacenter.net to one of these cedar-internal names, and to go from staging.metadatacenter.net to one of these cedar-internal names.

The eventual target is to  have:

```
{auth, cedar, repo, ...}.cedar-production.stanford.edu  # typically production machine; see below
{auth, cedar, repo, ...}.cedar-staging.stanford.edu # typically staging machine; see below
{auth, cedar, repo, ...}.cedar-restore.stanford.edu
{auth, cedar, repo, ...}.cedar-test.stanford.edu # this and next 2 as prove necessary
{auth, cedar, repo, ...}.cedar-dev1.stanford.edu
{auth, cedar, repo, ...}.cedar-dev2.stanford.edu
```

And then cedar team can manage the names
- `metadatacenter.net`, typically pointing to cedar-production.stanford.edu (and so, cedar.metadatacenter.net gets resolved as cedar.cedar-production.stanford.edu); and, 
- `staging.metadatacenter.net`, typically pointing to ceder-staging.stanford.edu (and so on with cedar. prefix to those)

If I've mastered my certificate 101 class, we will want to generate SSH certificates for all the combinations shown, including all the combinations of metadatacenter.net and staging.metadatacenter.net. This allows any of these to be accessed (using certificates) according to their names listed herein. 

A key point is that these names listed above (like cedar-production.stanford.edu) don't have to be the stanford-internal names that the IT group uses for the machines -- there can be one more level of naming behind the scenes for IT management purposes.

**Comment by martinjoconnor** [comment]
Only clarification I would add is that the CEDAR team will create manage the certificates.

**Comment by martinjoconnor** [comment]
In place for quite a while.
