### ISSUE TITLE
better error message on permission issues

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#800]
Give user a pleasant error when they don't have write (or read) permissions, for example when trying to enter a folder without permission, or trying to edit something they can't.

**Comment by martinjoconnor** [comment]
Related to https://github.com/metadatacenter/cedar-template-editor/issues/739

**Comment by willrett** [comment]
Issue #800 deals with editing something they cannot.  I'm not sure how someone enters a folder without permission.

**Comment by graybeal** [comment]
When someone gives them a URL to a folder, or that references a folder as the 'return' folder, then they *try* to enter it (whether they realize it or not). If they don't have write access, a red message pops up that says "permission issue", but they have no idea what just happened. Especially because they aren't actually in the folder they tried to get into.

If they have read access to a folder, so they are viewing the contents, but then they try to write to it (for example by populating a template in that folder and then clicking save), again an error will occur, but it is not obvious why they got the error, because the error isn't specific and they may not realize what folder they are in or that they tried to write to.

#739 is the same kind of scenario. They have tried to do something (in this case, open an instance which they have read or even write access to). For the instance to open, it has to read the template. If the user doesn't have read access to the template, another unclear error message pops up, which the person has no way of understanding or fixing.

There are fixes for #739 that may not be applicable to the first two cases. And some of the other cases maybe are impossible if all the paths are made impossible for users to choose, but that can be hard to get right everywhere all the time.

**Comment by willrett** [comment]
There are multiple ways of responding to an access error:  a server error message with technical details, an acknowledged message which they confirm ok, and a flashed popup that notifies them and goes away. 

If a user cannot open something from a pasted url, you need to respond with appropriate severity and take them to their home folder.  Right now we respond to server errors with server messages, but we can move to a less severe response.   

If they are writing a new resource and get a permission error, the document can be written to their home folder along with a flashed warning.  This does not work if they are updating an existing  document.
