### ISSUE TITLE
notify of issues on first edit

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#801]
If a user can open a template or instance, do not put up warnings about editing then. Instead, put up warnings (can't write to this directory; or This template has metadata instances) when they first try to edit something. Earlier may be irrelevant because they may not be editing, and later may be tragic because they have just spent 30 minutes editing something they can't save.

**Comment by willrett** [comment]
Fixed so warning for lacking write permission or having instances pop up on first edit.  New resources will be written to the user's home directory and a warning given on write permission errors.
