### ISSUE TITLE
Create aliases and SSL certs for Nexus Docker ports

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#818]
Nexus by default uses port 8082 to pull images and 8083 for pushing images. 

As suggested by Alex, use sub-domain aliases for these with appropriate SSL certs.

https://docker-pull.nexus.bmir.stanford.edu for 8082 and http://docker-push.nexus.bmir.stanford.edu for 8083.

**Comment by alexskr** [comment]
deployed 
https://cedar-dockerhub.bmir.stanford.edu
https://cedar-dockerhub-push.bmir.stanford.edu

**Comment by martinjoconnor** [comment]
Certs created but not able to authenticate.

**Comment by martinjoconnor** [comment]
Now works. Example of building and pushing image:

    docker build -t metadatacenter/cedar-nginx:1.8.10 .

    docker tag metadatacenter/cedar-nginx:1.8.10 cedar-dockerhub.bmir.stanford.edu/metadatacenter/cedar-nginx:1.8.10

     docker push cedar-dockerhub.bmir.stanford.edu/metadatacenter/cedar-nginx:1.8.10
