### ISSUE TITLE
Move reference CAIRR content to production

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#826]
The two instances Susanna and Hailong created, both for future reference (so, not as urgent, but definitely to do before they are lost from staging).
* The instances are
  * Susanna's instance (should go to her folder) (https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/c23aacf3-630f-4e1e-b7b4-4d1d67d88e1c) 
  * Hailong's instance (should go to his folder) (https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/c797b52d-6940-4e0f-9653-6b7741bd19d6)
* Unfortunately both Susanna and Hailong's instances seem to be based on an old template.
  * That template is the source of Susanna's existing submission in NCBI 
  * The easiest and best thing is to bring that template into the new system also, (https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.org/templates/ade1336d-a292-49f8-8fb9-d62c11997820)
  * Rename it to MiAIRR Original (Deprecated) in an MiAIRR Archival folder

**Comment by marcosmro** [comment]
I moved the old template and instances to production following those instructions. Find them here:
https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F30c8bffc-b9d1-497c-b4e7-4248cdf7f55c
