### ISSUE TITLE
Creation date sort not working on search

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#827]
Sorting by "Recently Created" doesn't seem to work within a search. See screenshot. Sorting this list by name or Recently Modified works fine.

<img width="530" alt="screen shot 2018-07-06 at 10 32 54 am" src="https://user-images.githubusercontent.com/1266896/42392581-2ea70aac-8108-11e8-998a-e7097981c003.png">

**Comment by egyedia** [comment]
It was fixed previously, but I double-checked, and did a minor modification as well.
