### ISSUE TITLE
vertically align Workspace rows text

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#829]
The text in the Workspace entries is aligned at the bottom of the row, but should be aligned center to look better, especially at larger sizes.

This can be fixed in the CSS by adding to the `.all-items-view .populate-form-boxes .list-view .box-row .cell` section a line
``` 
vertical-align: middle ;
```

**Comment by willrett** [comment]
fixed in the versioning branch which will come out for 2.0
