### ISSUE TITLE
Spreadsheet view shows double

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#835]
In https://cedar.metadatacenter.org/instances/create/https://repo.metadatacenter.org/templates/c81b786a-d77d-45c2-b6aa-8c1aa1fe308f?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2Fe9b5f2d1-e0e2-4879-bc18-ff779743a374 I clicked on spreadsheet full screen view and got 2 copies of the spreadsheet.

<img width="1440" alt="screen shot 2018-07-19 at 12 39 52 am" src="https://user-images.githubusercontent.com/1266896/42928525-62c7380a-8aec-11e8-8207-e700f04b3ae0.png">

**Comment by martinjoconnor** [comment]
I'm not seeing this. Is it still happening after a cache clear?

**Comment by willrett** [comment]
Fixed.
