### ISSUE TITLE
Consistent real-time field validation

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#847]
The validation model is not consistent with regard to what happens to entered data. Some fields don't validate but have a validation symbol as if they are validating; some fields don't validate that should; some fields produce unexpected validation results; all errors show warning even though some issues are more severe; some fields validate but allow invalid data to remain; and some fields validate but silently remove invalid data.

The proposed model is:
- If there is no validation for the field, no validation icon should be shown.
- For required fields that don't have content, a warning is shown.
- For validation that fails for a field given its current content, an error is shown. 
- If the field is abandoned its current content should not be deleted even if it is invalid.
- The validation icon should show the cause of the validation issue (and the meaning of the "OK" icon) as a pop-up. 

Note: For specific fields, some errors may be appropriately considered minor, e.g., a telephone number may include text at the end; this could be a warning, not an error. A IRI could show a warning if the IRI does not resolve. 

The task is to confirm the final model, and conform all field types to the agreed model. 

See also #569, #688, #85, and possibly #262.

Reference LD4P2 issues https://github.com/LD4P/requirements/issues/79, https://github.com/LD4P/requirements/issues/78, and https://github.com/LD4P/requirements/issues/43.

**Comment by graybeal** [comment]
In case not noted elsewhere: a phone number can contain '-' and '+' (for international codes), and if we want to be liberal also '#', '*', and ',' (for dial strings).

**Comment by willrett** [comment]
Fixed.
