### ISSUE TITLE
Protect data on browser back button

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#852]
When browser window is closed (e.g., via closing the tab) or left (e.g., via the back button), if there are unsaved changes, a warning should be generated and confirmation required.

This is the same as will happen with many forms on the web—if you have entered unsaved data, you will get a warning on trying to close the tab or window, or trying to navigate off the form. 

Reference https://github.com/LD4P/requirements/issues/157.

**Comment by willrett** [comment]
Ok, confirmation is now be required for a dirty document on browser back or closing the browser  tab.  The latter is dependent upon browser support but it appears to work in Chrome and Firefox.
