### ISSUE TITLE
General complaint of slow performance

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#853]
Referencing https://github.com/LD4P/requirements/issues/150:  There are complaints about CEDAR being slow, particularly mid-afternoon.

It is not clear whether these complaints are just concerning cedar-template-editor#732, cedar-model-validation-library#34, cedar-template-editor#466, #858, and cedar-teminology-server#13, or additional other slowness. See the original issue for original users.

**Comment by willrett** [comment]
We need to know which part of CEDAR is slow, the controlled term drop downs or something else?

**Comment by martinjoconnor** [comment]
Closing for lack of specificity.

**Comment by martinjoconnor** [comment]
Specific issue relating to slow template performance here:

metadatacenter/cedar-template-editor#732
