### ISSUE TITLE
Spreadsheet entry discrepancies

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#855]
Reference https://github.com/LD4P/requirements/issues/132, and possibly contact Nancy if we can't duplicate:

When entering multiple controlled terms (her "Subject" is  a controlled term) in spreadsheet view, deletions are not persistent. (They may or may not be shown in the form, but they are not reflected when returning to the spreadsheet view.)

**Comment by graybeal** [comment]
This may be a need to refresh the spreadsheet view with each Toggle View command, to get rid of data that may be hanging around in the JS fields.

**Comment by willrett** [comment]
Duplicate: enter invalid value in spreadsheet controlled term dropdown by entering chars and return.  toggle view and back into spreadsheet.  value becomes last valid value.  Also, clear out value in spreadsheet, toggle view twice.  The original value is there.  see #854

**Comment by cedaradmin** [comment]
Duplicate - as per above.
