### ISSUE TITLE
term drop-down too slow

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#858]
General comments that the drop-down for selecting terms is slow. Reference  https://github.com/LD4P/requirements/issues/141 and https://github.com/LD4P/requirements/issues/81. 
These are for metadata entry using an instance like https://cedar.metadatacenter.org/instances/edit/https://repo.metadatacenter.org/template-instances/2ec4f0d6-55ab-445d-9bff-822014f5597d, which includes some big branches.

**Comment by willrett** [comment]
Is this a branch indexing issue or something else?

**Comment by cedaradmin** [comment]
Now addressed by BioPortal branch indexing
