### ISSUE TITLE
MiAIRR Cell Subset field - request additional option

### ISSUE THREAD

**Issue by ahmadchan** [metadatacenter/cedar-project#870]
Received following issue through email from one the CAIRR users.

Hi Ahmed,
 
I’m trying to use the web-based MiAIRR metadata tool to get my data prepped for repository submission. It was going ok but I ran into an issue with the Cell Subset field under Processing. There’s an option called B cell, which I could use, but it doesn’t really differentiate my samples as they are all B cells, just different types (Naïve, memory, GC, etc). The field won’t accept anything typed in (eg. Naïve B cell) that is not part of the drop down list. I type it in, hit OK, but whatever I just typed disappears.  It seems from the help I could type in whatever I wanted, but wanted to check with you.
 
Thanks for your help,

**Comment by martinjoconnor** [comment]
Per John:

We'll have to check what help suggests this, as the suggestion is incorrect. For controlled terms, users may only choose from among the options defined by the template.

You may want to refer this ticket to the metadata working group, since they can recommend a change to the selected terms.

**Comment by ahmadchan** [comment]
I have reported this issue to the MiAIRR standards WG to get their views

**Comment by ahmadchan** [comment]
The field is using Cell ontology. I found naive T cell but not Naive B cell in the drop down. Naive B cell is listed in the cell ontology https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000788. May be field is not parsing ontology correctly.

**Comment by graybeal** [comment]
Thanks for checking this Ahmad. We’ve been having occasional issues with the parsing but thought they were fixed. I’ll work with the BioPortal team to sort this out.

________________________________
