### ISSUE TITLE
Search didn't find shared resource

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#871]
A new user logged in and did a search for 'samples'. The search did not find the folder "Geologic Samples" (https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2Fdb242545-e2e6-420b-a805-70725aaeaeff), although the folder is set to Everybody > read.

By going to Shared With Me, the user was able to see the folder and access it.

**Comment by martinjoconnor** [comment]
New users are not indexed properly in Everybody group. Will need to update Everybody index on new user creation.
