### ISSUE TITLE
Publish mostly fails

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#872]
The Publish command fails with Bad Request on Chrome or Safari, on several different templates. The only two successful outcomes have both been (a) on Chrome, (b) with no changes to the version (i.e., it stayed at 0.0.1), and (c) on a template I haven't failed on before. 

(Hypothesis to test: (1) Changing the minor version # will cause a fail. (2) A previous fail will propagate.)

Movies showing the behaviors are uploaded at https://stanfordmedicine.box.com/s/78jb8wwtkh1lk3sz6bseobigjyisijba and https://stanfordmedicine.box.com/s/3l563r846lviful4gegjdqc7ac5mojdj

Templates that failed:
* https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.org/templates/344fa34b-02ef-4461-b85f-2c70a01a56ec
* https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.net/templates/c3e06971-3074-4ecd-a318-6d642f3c0abe
* https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.org/templates/4c7d16bb-0a74-4673-9be0-60f59112ecaa

Templates that succeeded:
* https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.org/templates/c680ebdf-d2a7-4c42-b6ce-13cd0f7c4a55
* https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.org/templates/dac42f4e-9cf0-4465-baeb-583933331a6b

Error message is 
```
Technical details of error
Status: 400, Bad Request
URL: https://resource.staging.metadatacenter.org/command/publish-resource
Method: POST

Message: 
Error key: versioningOnlyOnLatest
Exception: 

Stack trace:
```

By mucking around with Developer mode I pulled up this message, but no other details:
```
{"errorKey":null,"errorMessage":null,"parameters":{},"errorReasonKey":null,"status":"METHOD_NOT_ALLOWED","statusCode":405}
```

**Comment by willrett** [comment]
Added check of isLatestVersion which should fix it.
