### ISSUE TITLE
Latest must show Draft and Published

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#874]
Per the odd diagram on my whiteboard, when Latest is checked, both the Draft and the Published should be shown. This is needed because the person might want to work with either of those at any given time (for example, to go back and forth comparing the two, or to switch from editing a template to populating it. We want Latest to be on 99% of the time (much cleaner than when it's off), so the latest published template (which is heavily used!) needs to be visible with Latest on.

**Comment by marcosmro** [comment]
This is a backend issue. Here is the REST call when "Latest" is enabled:

https://resource.metadatacenter.orgx/folders/https%3A%2F%2Frepo.metadatacenter.orgx%2Ffolders%2F91c3a54a-4c3c-4592-9f60-05e064fa3969/contents?limit=100&offset=0&publication_status=all&resource_types=element,field,instance,template,folder&sort=name&version=latest

This call looks fine (publication_status=all, version=latest). In this case, the backend should return both the latest draft and the published version.

**Comment by martinjoconnor** [comment]
Will revisit this for next release. Not clear that original choice was a good one - and the caDSR system shows only a draft when latest release is active.

**Comment by martinjoconnor** [comment]
Likely will do in 2.2 based on consensus.
