### ISSUE TITLE
Create Draft causes unexpected UI results

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#879]
I just published something in a subdirectory and then clicked on "Create Draft" (or whatever it is). Now neither the original published version nor my draft is visible (with Latest on).

With Latest off, I can see the two documents.

**Comment by martinjoconnor** [comment]
Tried that and it works fine for me. Is it repeatable for you.

**Comment by graybeal** [comment]
Ah, correction(s). The draft gets created, but it shows no symbol and no version #, and when I clicked on the Version tab nothing was shown there. So it looked like something that had never been published.

**Comment by martinjoconnor** [comment]
The version number does not seem to be shown when it is 0.0.1 even when something is published. Will create an issue for that. Think it should be.

**Comment by willrett** [comment]
The version number is displayed unless the resource is Draft 0.0.1.  There is a separate issue for showing both draft and published latest versions when "Latest" is selected.
