### ISSUE TITLE
Version Info tab not refreshed on publish

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#880]
After publishing or creating Draft, Version info tab is not refreshed (is just white, until I cause a redraw).

**Comment by martinjoconnor** [comment]
I *think* the issue here is lost workspace selection (#798). With nothing selected the Info panel is blank. See if you agree.

**Comment by graybeal** [comment]
no, I have a movie which illustrates this out a slightly different path. The new version is created, I select it, then I open the info tab. The resulting screen looks like this, you can see the selection.
<img width="1185" alt="screen shot 2018-08-30 at 6 24 12 pm" src="https://user-images.githubusercontent.com/1266896/44887664-3fbee080-ac82-11e8-9023-dd43611dd852.png">

If I click on the Info tab and then the version tab, the version info pops up. That's the same symptom—just causing a redraw (by clicking on Info and then Version) makes it appear.
