### ISSUE TITLE
Invalid Create Draft version pop-up text

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#882]
When creating a new draft, all of the language in the pop-up version selector is about creating a Published version. Needs to be modified to be about the Draft version

**Comment by willrett** [comment]
Here's the blurb for creating a draft or published version.  Clicking the read more or read less link shows or hides the extra text.  We could have a different message for creating draft versus publishing draft.   The text is localized and can be easily modified.

Publishing allows you to add a version number to a resource. ...read less
Published resources are not modifiable and cannot be deleted. Create a new version of a published resource by first creating a draft and then modifying it. When you are ready, publish the draft to disable further edits.
