### ISSUE TITLE
Highlight current version in Info Version tab

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#883]
In Version list, would like it to more clearly highlight where the currently selected document appears in that list. Right now the most recent version's name is always bold, but since the top is always most recent that doesn't add anything new. Suggest you could use bold title and a light gray background for the one that is selected, or a left bar would be consistent with the main display.

**Comment by willrett** [comment]
The current selection is displayed with a light gray background in the version table.
