### ISSUE TITLE
version info alignment

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#884]
When the globe icon is missing the version info moves into that space (everything moves left). Better if it can be vertically aligned with the other entries.

**Comment by willrett** [comment]
When the globe is not displayed, the space that it would show in remains.  This makes the digits of the version line up vertically.  Please let me know if you see some other behavior.

**Comment by graybeal** [comment]
This is in the Version Info tab, sorry if that wasn't clear. This is what I see there.

<img width="383" alt="screen shot 2018-09-24 at 2 05 50 pm" src="https://user-images.githubusercontent.com/1266896/45979205-3ae01900-c003-11e8-8230-03a9a723286a.png">
