### ISSUE TITLE
Submit menu option too visible

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#885]
Sometimes the ellipsis Submit menu option stays visible for any old thing. (See images below.)  it doesn't always happen on all objects, I haven't found a pattern yet. 

Sometimes inapplicable menu options appear for as much as a half-second and then are hidden. I think that is a bit too long, but it doesn't seem to explain the above.

If I select the option it actually brings up the submit window regardless of whether it's valid.

Later on, after using CEDAR an hour, I couldn't get the submit window on any artifact, even submittable ones. Reloading the browser window fixed this. (!!)

<img width="990" alt="screen shot 2018-08-30 at 7 54 52 pm" src="https://user-images.githubusercontent.com/1266896/44890414-017bee00-ac8f-11e8-8f3b-91416e75aaf8.png">
<img width="1002" alt="screen shot 2018-08-30 at 7 55 01 pm" src="https://user-images.githubusercontent.com/1266896/44890432-1789ae80-ac8f-11e8-8f4b-eb9e0bf0f9b9.png">

**Comment by willrett** [comment]
Some of the permissions are set from a "report" call.  I made a change to set the permissions as soon as an item is selected and then update them when the report call is returned.  Let's see if that is sufficient.  If these do not reflect in the menu item quick enough, then we need to move them into the basic resource info instead.
