### ISSUE TITLE
Field search sorting

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#886]
I'm in a template searching for fields. I navigate to the CEDAR Admin home directory/CDEs folder. I can search, or I can sort, but sorting seems to reset searching. And any sort selection 
(Title, Created, etc.) can only go down, I can't make it sort up.

**Comment by willrett** [comment]
Searching and sorting are separate tasks and do not reset one another.   Sorting sorts in one direction at this time.
