### ISSUE TITLE
Navigation disappears in element search

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#889]
Once the field/element search display is up (from within a template), if you enter a search term, the location path at the bottom disappears. After that there is no way to get it back, and no way to navigate to somewhere else.

**Comment by willrett** [comment]
When you are searching, whether it is in the workspace or element/field finder, the path is not displayed along with search results.  Instead, the search string is displayed, e.g. Search Results For: 'whatever'.   The way to exit search mode is to click the x in the search box.  

The only thing currently missing is the display of the search string in the element/field finder.

**Comment by willrett** [comment]
Added text for Search Results For : ...
