### ISSUE TITLE
Resource sorting issues

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#89]
(1) "Z" comes before "a" in the sorted by name list.  caps should not be significant.

(2) Click on the sort tool in the toolbar of the workspace. Select recently created or recently modified. No results are returned.

(3) Click on the sort tool in the toolbar of the workspace. Select recently created or recently modified. No results are returned.

**Comment by martinjoconnor** [comment]
Will tentatively put in 0.8 pending an estimate by @marcosmro. Sounds like it might be addressable in combination with 0.8 bugs metadatacenter/cedar-template-editor#496 and metadatacenter/cedar-template-editor#497.
