### ISSUE TITLE
MiAIRR template Synthetic Library field of wrong type

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#892]
Synthetic LIbrary field was set up with a checkbox selection instead of radio buttons, so it can be set to both TRUE and FALSE at the same time.

**Comment by graybeal** [comment]
Note this should only be fixed when we do a major migration to a new MiAIRR template, because the existing instances would break. If anyone checks both boxes it'll probably break something somewhere, and then they'll have to fix their instance.

**Comment by marcosmro** [comment]
So, how should we do this? Let me know if these steps make sense:
1. Publish the current MiAIRR template as version 0.0.1.
2. Create a new draft from the published version.
3. Fix the "Synthetic Library field" and any other open issues, including https://github.com/metadatacenter/cedar-template-editor/issues/805.
4) Publish a new version (0.0.2).
5) Update the front-end to allow submission for the new version of the template too. 
6) Let future submitters know that they should use the latest version of the template.

**Comment by graybeal** [comment]
Well, it won't work as is. We can't publish this template because it is referred to by many outside links (possibly growing all the time), and out publication model changes the IRIs with each publication.  We particularly wouldn't want someone to accidentally fill out the old template. (Reference #838.) 

This might be OK: if we can implement #901, then even if someone is pointed to the old template, they would be notified of the newer template when they try to populate the old one. Then this approach would be fine.
