### ISSUE TITLE
Publish schema.org-embedded metadata for CCP instances

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#898]
Make the Cloud Commons Pilot DataMed data publishable into the Google data sets index (and to a standalone page).

Possible no-dev approach: To start, create a World group. Josef can harvest any "Ready to Index" CCP instance that is World-readable and generate a schema.org-compliant HTML page for that instance. I would work with the CCP folks to contact the authors to get their permission to make their resource descriptions world-readable. And Josef already did a lot of the necessary mappings in the schema.org supplement, though some adjustments will be needed.  His harvesting/publishing tool could run on a cron job, say daily.

**Comment by martinjoconnor** [comment]
Project completed so no longer relevant. However, generating Schema.org markup for OpenView pages is similar task (metadatacenter/cedar-openview#4).
