### ISSUE TITLE
Sorting by name and grouping by type should load by type then by name

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#90]
i am searching by name, and grouping by type with folders shown first.  with pagination, i can get a situation where folders are not displayed on the first page, but will show at the top after a few more page loads.   i should be seeing all the folders ordered by name on the first page.

**Comment by martinjoconnor** [comment]
I'll tentatively put it in 0.8 as a bug pending an estimate by @marcosmro  or @egyedia.

**Comment by martinjoconnor** [comment]
Merged into metadatacenter/cedar-project#89
