### ISSUE TITLE
LINCS metadata field names displaying wrong

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#900]
Danny reports:  anyone know what's going on with the template field names? they're fine in another version of the same template, but something's off in the new version. 

template is https://cedar.metadatacenter.org/instances/create/https://repo.metadatacenter.net/templates/da10e2fd-f534-4574-833f-c7b4e8cb52b1
in folder
https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F3db3d932-e3c6-4079-beb9-5a29a386eb1a

![weirdlincsfields](https://user-images.githubusercontent.com/1266896/45514670-d5ff0600-b75a-11e8-84b7-3e1f7571eaab.png)

**Comment by graybeal** [comment]
Two observations initially: 

(1) The field (and element) names presented in the UI do not match the field names in the template. Sometimes just the viewed name is wrong; sometimes the template name is also wrong in the same way,  sometimes in a different way. The issues are always an extra space (after the first character) and/or random capitalization at the beginning of the field.
(2) Several other templates in the same folder are broken in the same way. (And it's very inconsistent, both how it breaks and how often it breaks.)

One hypothesis is that the names get displayed wrong, then on save any display errors gets saved to the file.

**Comment by graybeal** [comment]
Folder contents at https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F3db3d932-e3c6-4079-beb9-5a29a386eb1a  (All / Shared / LINCS / development / Templates) has exact same issue.

**Comment by johardi** [comment]
Fixed by a manual correction
