### ISSUE TITLE
Saving doesn't run validator

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#906]
(Previously reported but I thought fixed, and I can't find the previous report.)

I open a field or element and the "Validated" check mark is yellow.

I save the document and the check mark becomes white.

I leave the document and re-open it, and the check mark is yellow again.  (Even if I just reload the document, the same thing happens.)

Looking at the network communications with the debugger, it is clear that saving the document does not validate the document. (No validation traffic/response is seen, unless the document is reloaded.)  Changing the valid indication (checkmark color) is therefore inappropriate.

**Comment by willrett** [comment]
Fixed
