### ISSUE TITLE
can't find instances associated with template

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#919]
Jeff writes:
Was following up on the duplicate item request - and was running the commands to double check things and it is now returning 0 records:
	https://resource.metadatacenter.org/search?&is_based_on=https%3A%2F%2Frepo.metadatacenter.org%2Ftemplates%2F62c8b5f2-7dc9-4fff-9008-07c95a746411

{
    "request": {
        "version": "all",
        "publicationStatus": "all",
        "limit": 100,
        "offset": 0,
        "sort": [
            "name"
        ],
        "q": null,
        "id": null,
        "resource_types": [
            "instance"
        ],
        "is_based_on": "https://repo.metadatacenter.org/templates/62c8b5f2-7dc9-4fff-9008-07c95a746411"
    },
    "totalCount": 0,
…

Did something change again?

**Comment by egyedia** [comment]
I changed the call to work with Neo4J data instead of Elasticsearch.
The fix is part of release 2.1.5
