### ISSUE TITLE
Investigate conversion to/from REDCap forms

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#929]
Investigate effort in transforming CEDAR templates to and from REDCap forms.

See the following for caDSR conversion to REDCap forms:

https://starbrite.vanderbilt.edu/rocket/index.php?doc_id=8550&action=download&file_id=107120

Building a REDCap Data Dictionary:

https://www.utsouthwestern.edu/edumedia/edufiles/about_us/admin_offices/academic_information_services/redcap-database-creating-dictionary.pdf

http://www.montana.edu/orc/redcap/documents/REDCapDataDictionary2017_201.pdf

https://www.iths.org/wp-content/uploads/REDCap-Data-Migration-from-MS-Excel-2.pdf

https://www.utsouthwestern.edu/edumedia/edufiles/research/center_translational_medicine/redcap-faq.pdf

Calculated fields:

https://www.ctsi.ufl.edu/files/2017/06/Calculated-Fields-%25E2%2580%2593-REDCap-How.pdf

See pg. 29+ of following document to see how REDCap implements question skipping:

https://bioinformatics.rockefeller.edu/wp-content/uploads/REDCap_guide.pdf

Datatypes:

```
TEXT - single-line text box (for text and numbers)
NOTES - large text box for lots of text
DROPDOWN - dropdown menu with options
RADIO - radio buttons with options
CHECKBOX - checkboxes to allow selection of more than one option
FILE - upload a document
CALC - perform real-time calculations
SQL - select query statement to populate dropdown choices
DESCRIPTIVE- text displayed with no data entry and optional image/file
attachment
SLIDER - visual analogue scale; coded as 0-100
YESNO - radio buttons with yes and no options; coded as 1, Yes | 0, No
TRUEFALSE - radio butto
```

Text validation types:

```
DATE_YMD - (2008-12-31)
DATE_MDY - (12-31-2008)
DATE_DMY - (31-12-2008)
TIME - (19:30, 04:15) - Military time
DATETIME_YMD - (2011-02-16 17:45)
DATETIME_MDY - (02-16-2011 17:45)
DATETIME_DMY - (16-02-2011 17:45)
DATETIME_SECONDS_Y
MD - (2011-02-16 17:45:23)
DATETIME_SECONDS_M
DY - (02-16-2011 17:45:23)
DATETIME_SECONDS_D
MY - (16-02-2011 17:45:23)
PHONE - (615-322-2222)*
EMAIL - ( john.doe@vanderbilt.edu)
NUMBER - (1.3, 22, -6.28) a general number
INTEGER - (1, 4, -10) whole number with no decimal
ZIPCODE - (37212, 90210) 5-digit zipcode
Letters only - (name)
MRN - (0123456789)10 digits
Number (1 decimal place) - (1.2)
Number (2 decimal places) - (1.23)
Number (3 decimal places) - (1.234)
Number (4 decimal places) - (1.2345)
Phone (Australia) - ((03) 1234 1234)
Postal Code (Australia) - (2150,7799)4-digit number
Postal Code (Canada) - (K1A 0B1, K0H 9Z0) format: A0A 0A0 where A is a letter and 0 is a digit
Social Security Number (US) - (111-11-1111)
Time (MM:SS) - (31:22) time in minutes and seconds
```

REDCap also supports functions in expressions:

```
round(number,decimal places)
roundup(number,decimal places)
rounddown(number,decimal places)
sqrt(number)
abs(number)
min(number,number,...)
max(number,number,...)	
mean(number,number,...)	
median(number,number,...) 
sum(number,number,...)	
stdev(number,number,...)
datediff
```

**Comment by gaurav** [comment]
What is the current state of CEDAR/REDCap integration? This issue is one of the top search results on Google, so I thought I'd ask here so we can point people to the appropriate documentation if it exists.

**Comment by martinjoconnor** [comment]
This task describes scope analysis only. We don't currently have a timeline to carry out this interoperation task, though it is something that we agree would be useful.

**Comment by graybeal** [comment]
We're now actively working on this task
