### ISSUE TITLE
can't navigate to end of users folder

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#932]
Go to the Users folder, and navigate to the end. I can only get to user 700/600/700 (out of 775) in three tests over two days.

And even though I allegedly got to 700, if I copy/paste the list into a text file, there are only 600 entries there.

**Comment by graybeal** [comment]
Where it stops. (I confirmed my copied text stopped in the same place, and started at the top.)

<img width="1113" alt="screen shot 2018-10-24 at 7 59 18 am" src="https://user-images.githubusercontent.com/1266896/47440600-5bff6b00-d763-11e8-94d8-dff3323bf79b.png">

**Comment by willrett** [comment]
fixed
