### ISSUE TITLE
Take a Look at Nagios Core

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-project#958]
It is a free monitoring option
https://www.nagios.org/downloads/

It has paid versions as well, we could probably use the free one for now.

**Comment by graybeal** [comment]
Your friendly BMIR IT team (including me in that team) has been working for the last month to establish an up-to-date Nagios monitoring capability for all our systems. The only reason we haven't done it yet with CEDAR is that we haven't had the chance to talk with the CEDAR team about appropriate monitoring configurations, and appropriate actions to take when we can't raise a CEDAR person. I'll connect with Martin to set up a meeting, also to cover how we will do monitoring over the break.

**Comment by martinjoconnor** [comment]
IT team to add monitoring for CEDAR machines  and add Slack notification.

**Comment by martinjoconnor** [comment]
Atti to send list of microservices to monitor.
