### ISSUE TITLE
GRID ontology doesn't work in CEDAR

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#966]
We debugged an  ontology in BIoPortal called GRID so that it is now available to CEDAR. This ontology is called flat in BioPortal, which means there are a very large number of terms at the second level, with very few levels overall.

When CEDAR tries to access this ontology, either to do a search in it or to browse it, errors occur. (A BioPortal Connection Failed message if its trying to search for a term; or an error attempting to browse the content because there are too many terms.

Misha said the following, which may be relevant:
* CEDAR should be using the /roots_paged endpoint that we've developed for them for this very purpose. It does not time out
http://data.bioontology.org/ontologies/GRID/classes/roots_paged

**Comment by marcosmro** [comment]
The cause of the search issues was that the GRID ontology was not shared with the right BioPortal user: cedar-test. I have fixed it.

Regarding the browse issue, Misha is right. We have an open task about it: https://github.com/metadatacenter/cedar-project/issues/647
