### ISSUE TITLE
Provide CEDAR ElasticSearch training

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#974]
Provide basic training in CEDAR's elastic search content and features, as currently implemented and envisioned. Target audience is NLM (curious CEDAR people can attend).

May not be needed/useful until newly prototyped interfaces are available (#70).

**Comment by martinjoconnor** [comment]
NLM team seem to have a good understanding of this so not currently needed.

They will experiment with new field-based search (metadatacenter/cedar-resource-server#70).
