### ISSUE TITLE
CCP instance not found in parent template's sidebar

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#979]
The instance "CCP TubeTK" has this metadata:
```
  "schema:isBasedOn": "https://repo.metadatacenter.org/templates/62c8b5f2-7dc9-4fff-9008-07c95a746411",
  "schema:name": "CCP TubeTK",
```
but is not found in the list of instances for that template in the info sidebar (not possible to give you a URL for that sidebar view, but search that contains it looks like 
```
https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/62c8b5f2-7dc9-4fff-9008-07c95a746411?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F6ab640b2-942e-40e4-bbd3-458b26e0a907&search=CCP&t=1550532524395
``` 

and a direct URL to the template in the editor is 
```
https://cedar.metadatacenter.org/templates/edit/https://repo.metadatacenter.org/templates/62c8b5f2-7dc9-4fff-9008-07c95a746411
```

It may be relevant that the Derived From field is set in this particular instance (CCP TubeTK), and points to the CCP ParaView Glance instance.
```
  "pav:derivedFrom": "https://repo.metadatacenter.org/template-instances/6a7aafb2-8e31-4210-8c57-9b63477ceb9f",

**Comment by martinjoconnor** [comment]
Some missing internal properties found in Neo4J.  Now fixed.

Task to detect this issue in future: https://github.com/metadatacenter/cedar-resource-server/issues/73
