### ISSUE TITLE
ARRANGE pop-up doesn't work on big lists

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#981]
If you have the human disease ontology as the ontology selected for the values, and click on ARRANGE, the resulting dialog can't really be used. It only shows 25 or so terms at a time, the order appears random, and any hierarchy is lost.

If you add the disease branch of SNOMEDCT, clicking on ARRANGE takes a long time and produces a Can't connect to BioPortal message (the one time I tried it). Eventually 25 or so terms are displayed, all from the first ontology.

**Comment by graybeal** [comment]
I think this has been fixed as part of the recent caDSR form import release.

**Comment by marcosmro** [comment]
Yes. I tried and it works now. The following screenshot show how the dropdown looks after constraining a field to DOID + the disease branch of SNOMEDCT, and moving one term from DOID and another from SNOMEDCT to the 1st and 2nd positions, respectively. I'll close this issue.

![Screen Shot 2021-04-09 at 11.15.36 AM.png](https://images.zenhubusercontent.com/5cc8da556c1fd80bacaab6cd/e6131daa-7a0d-4c59-8aa2-640a7f1e4bd8)

![Screen Shot 2021-04-09 at 11.16.14 AM.png](https://images.zenhubusercontent.com/5cc8da556c1fd80bacaab6cd/3fa86ed2-5224-435a-83c9-86fba1e334ef)
